// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthChallenge = `-- name: ConsumeAuthChallenge :one
UPDATE auth_challenges
   SET consumed_at = now()
 WHERE id = $1 AND kind = $2 AND consumed_at IS NULL AND expires_at > now()
RETURNING id, kind, user_id, email, challenge, session_data, consumed_at, expires_at, created_at
`

type ConsumeAuthChallengeParams struct {
	ID   uuid.UUID         `json:"id"`
	Kind AuthChallengeKind `json:"kind"`
}

// Single-use by construction: the `consumed_at IS NULL` predicate makes a
// concurrent replay lose the race and return zero rows.
func (q *Queries) ConsumeAuthChallenge(ctx context.Context, arg ConsumeAuthChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, consumeAuthChallenge, arg.ID, arg.Kind)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.Email,
		&i.Challenge,
		&i.SessionData,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const countAuthAttemptsSince = `-- name: CountAuthAttemptsSince :one
SELECT count(*) FROM auth_attempts
 WHERE bucket_key = $1 AND kind = $2 AND created_at > $3
`

type CountAuthAttemptsSinceParams struct {
	BucketKey string             `json:"bucket_key"`
	Kind      AuthChallengeKind  `json:"kind"`
	Since     pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountAuthAttemptsSince(ctx context.Context, arg CountAuthAttemptsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthAttemptsSince, arg.BucketKey, arg.Kind, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthChallenge = `-- name: CreateAuthChallenge :one

INSERT INTO auth_challenges (kind, user_id, email, challenge, session_data, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, kind, user_id, email, challenge, session_data, consumed_at, expires_at, created_at
`

type CreateAuthChallengeParams struct {
	Kind        AuthChallengeKind  `json:"kind"`
	UserID      pgtype.UUID        `json:"user_id"`
	Email       *string            `json:"email"`
	Challenge   []byte             `json:"challenge"`
	SessionData []byte             `json:"session_data"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// ---- Auth ceremonies --------------------------------------------------------
func (q *Queries) CreateAuthChallenge(ctx context.Context, arg CreateAuthChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, createAuthChallenge,
		arg.Kind,
		arg.UserID,
		arg.Email,
		arg.Challenge,
		arg.SessionData,
		arg.ExpiresAt,
	)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.Email,
		&i.Challenge,
		&i.SessionData,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id, token_hash, user_agent, ip_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, user_agent, ip_hash, expires_at, created_at, revoked_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	UserAgent *string            `json:"user_agent"`
	IpHash    []byte             `json:"ip_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// ---- Sessions ---------------------------------------------------------------
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, email_verified, password_hash, role, reputation, created_at, updated_at, deleted_at, suspended_until, last_login_at
`

type CreateUserParams struct {
	Username     string  `json:"username"`
	Email        string  `json:"email"`
	PasswordHash *string `json:"password_hash"`
}

// Identity, authentication ceremonies, and sessions.
//
// Conventions used throughout packages/db/queries:
//   - time windows are passed as timestamptz boundaries computed in Go
//     (`created_at > @since`), never as interval strings. That keeps the
//     predicate sargable and avoids coupling SQL to Go's duration formatting.
//   - every destructive ceremony is a single atomic conditional UPDATE, so
//     "single use" cannot be violated by two concurrent requests.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Role,
		&i.Reputation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuspendedUntil,
		&i.LastLoginAt,
	)
	return i, err
}

const credentialIDExists = `-- name: CredentialIDExists :one
SELECT EXISTS (SELECT 1 FROM webauthn_credentials WHERE id = $1) AS exists
`

func (q *Queries) CredentialIDExists(ctx context.Context, id []byte) (bool, error) {
	row := q.db.QueryRow(ctx, credentialIDExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteExpiredChallenges = `-- name: DeleteExpiredChallenges :execrows
DELETE FROM auth_challenges WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredChallenges(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredChallenges, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleSessions = `-- name: DeleteStaleSessions :execrows
DELETE FROM sessions
 WHERE (revoked_at IS NOT NULL AND revoked_at < $1)
    OR (revoked_at IS NULL AND expires_at < $1)
`

// Sessions revoked or expired more than @since are garbage; removing them keeps
// the lookup index small without ever touching a live session.
func (q *Queries) DeleteStaleSessions(ctx context.Context, since pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleSessions, since)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :execrows
DELETE FROM webauthn_credentials WHERE id = $1 AND user_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	ID     []byte    `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const emailIsTaken = `-- name: EmailIsTaken :one
SELECT EXISTS (SELECT 1 FROM users WHERE email = $1) AS taken
`

func (q *Queries) EmailIsTaken(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailIsTaken, email)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const extendSession = `-- name: ExtendSession :execrows
UPDATE sessions SET expires_at = $1
 WHERE id = $2 AND revoked_at IS NULL
`

type ExtendSessionParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendSession, arg.ExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fetchPendingEmails = `-- name: FetchPendingEmails :many
SELECT id, to_email, template, payload, attempts, sent_at, last_error, created_at FROM email_outbox
 WHERE sent_at IS NULL AND attempts < $1
 ORDER BY id
 LIMIT $2
`

type FetchPendingEmailsParams struct {
	MaxAttempts int32 `json:"max_attempts"`
	Lim         int32 `json:"lim"`
}

func (q *Queries) FetchPendingEmails(ctx context.Context, arg FetchPendingEmailsParams) ([]EmailOutbox, error) {
	rows, err := q.db.Query(ctx, fetchPendingEmails, arg.MaxAttempts, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutbox{}
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ToEmail,
			&i.Template,
			&i.Payload,
			&i.Attempts,
			&i.SentAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByCredentialID = `-- name: FindUserByCredentialID :one
SELECT u.id, u.username, u.email, u.email_verified, u.password_hash, u.role, u.reputation, u.created_at, u.updated_at, u.deleted_at, u.suspended_until, u.last_login_at FROM users u
  JOIN webauthn_credentials c ON c.user_id = u.id
 WHERE c.id = $1 AND u.deleted_at IS NULL
`

// Login resolves the account from the asserted credential, because a passkey
// ceremony begins before we know who is signing in.
func (q *Queries) FindUserByCredentialID(ctx context.Context, credentialID []byte) (User, error) {
	row := q.db.QueryRow(ctx, findUserByCredentialID, credentialID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Role,
		&i.Reputation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuspendedUntil,
		&i.LastLoginAt,
	)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT s.id, s.user_id, s.expires_at, s.created_at,
       u.username, u.email, u.role, u.reputation, u.email_verified,
       u.suspended_until, u.deleted_at AS user_deleted_at
  FROM sessions s
  JOIN users u ON u.id = s.user_id
 WHERE s.token_hash = $1
   AND s.revoked_at IS NULL
   AND s.expires_at > now()
`

type GetActiveSessionRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	Role           UserRole           `json:"role"`
	Reputation     int32              `json:"reputation"`
	EmailVerified  bool               `json:"email_verified"`
	SuspendedUntil pgtype.Timestamptz `json:"suspended_until"`
	UserDeletedAt  pgtype.Timestamptz `json:"user_deleted_at"`
}

// The single query behind session middleware. Suspension and soft-deletion are
// resolved here so no handler can forget to check them.
func (q *Queries) GetActiveSession(ctx context.Context, tokenHash []byte) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, tokenHash)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Reputation,
		&i.EmailVerified,
		&i.SuspendedUntil,
		&i.UserDeletedAt,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT user_id, display_name, bio, avatar_key, pronouns, location, is_private, updated_at FROM profiles WHERE user_id = $1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarKey,
		&i.Pronouns,
		&i.Location,
		&i.IsPrivate,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicProfileByUsername = `-- name: GetPublicProfileByUsername :one
SELECT u.id, u.username, u.created_at, u.role,
       p.display_name, p.bio, p.pronouns, p.location, p.avatar_key, p.is_private
  FROM users u
  LEFT JOIN profiles p ON p.user_id = u.id
 WHERE u.username = $1 AND u.deleted_at IS NULL
`

type GetPublicProfileByUsernameRow struct {
	ID          uuid.UUID          `json:"id"`
	Username    string             `json:"username"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Role        UserRole           `json:"role"`
	DisplayName *string            `json:"display_name"`
	Bio         *string            `json:"bio"`
	Pronouns    *string            `json:"pronouns"`
	Location    *string            `json:"location"`
	AvatarKey   *string            `json:"avatar_key"`
	IsPrivate   *bool              `json:"is_private"`
}

// The public projection: never exposes email, reputation internals, or a
// private account's details beyond what the profile page needs.
func (q *Queries) GetPublicProfileByUsername(ctx context.Context, username string) (GetPublicProfileByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfileByUsername, username)
	var i GetPublicProfileByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.Role,
		&i.DisplayName,
		&i.Bio,
		&i.Pronouns,
		&i.Location,
		&i.AvatarKey,
		&i.IsPrivate,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, email_verified, password_hash, role, reputation, created_at, updated_at, deleted_at, suspended_until, last_login_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Role,
		&i.Reputation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuspendedUntil,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, email_verified, password_hash, role, reputation, created_at, updated_at, deleted_at, suspended_until, last_login_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Role,
		&i.Reputation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuspendedUntil,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, email_verified, password_hash, role, reputation, created_at, updated_at, deleted_at, suspended_until, last_login_at FROM users WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Role,
		&i.Reputation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuspendedUntil,
		&i.LastLoginAt,
	)
	return i, err
}

const getWebAuthnCredential = `-- name: GetWebAuthnCredential :one
SELECT id, user_id, public_key, attestation_aaguid, sign_count, transports, nickname, created_at, last_used_at, flags, clone_detected FROM webauthn_credentials WHERE id = $1
`

func (q *Queries) GetWebAuthnCredential(ctx context.Context, id []byte) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredential, id)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.AttestationAaguid,
		&i.SignCount,
		&i.Transports,
		&i.Nickname,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Flags,
		&i.CloneDetected,
	)
	return i, err
}

const insertWebAuthnCredential = `-- name: InsertWebAuthnCredential :exec

INSERT INTO webauthn_credentials
  (id, user_id, public_key, attestation_aaguid, sign_count, transports, nickname, flags)
VALUES
  ($1, $2, $3, $4,
   $5, $6, $7, $8)
`

type InsertWebAuthnCredentialParams struct {
	ID                []byte      `json:"id"`
	UserID            uuid.UUID   `json:"user_id"`
	PublicKey         []byte      `json:"public_key"`
	AttestationAaguid pgtype.UUID `json:"attestation_aaguid"`
	SignCount         int64       `json:"sign_count"`
	Transports        []string    `json:"transports"`
	Nickname          string      `json:"nickname"`
	Flags             []byte      `json:"flags"`
}

// ---- WebAuthn credentials ---------------------------------------------------
func (q *Queries) InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, insertWebAuthnCredential,
		arg.ID,
		arg.UserID,
		arg.PublicKey,
		arg.AttestationAaguid,
		arg.SignCount,
		arg.Transports,
		arg.Nickname,
		arg.Flags,
	)
	return err
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT id, user_agent, ip_hash, created_at, expires_at, revoked_at
  FROM sessions
 WHERE user_id = $1
 ORDER BY created_at DESC
 LIMIT $2
`

type ListSessionsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Lim    int32     `json:"lim"`
}

type ListSessionsForUserRow struct {
	ID        uuid.UUID          `json:"id"`
	UserAgent *string            `json:"user_agent"`
	IpHash    []byte             `json:"ip_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]ListSessionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listSessionsForUser, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsForUserRow{}
	for rows.Next() {
		var i ListSessionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserAgent,
			&i.IpHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebAuthnCredentialsForUser = `-- name: ListWebAuthnCredentialsForUser :many
SELECT id, user_id, public_key, attestation_aaguid, sign_count, transports, nickname, created_at, last_used_at, flags, clone_detected FROM webauthn_credentials WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWebAuthnCredentialsForUser(ctx context.Context, userID uuid.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentialsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.AttestationAaguid,
			&i.SignCount,
			&i.Transports,
			&i.Nickname,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Flags,
			&i.CloneDetected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailFailed = `-- name: MarkEmailFailed :execrows
UPDATE email_outbox SET attempts = attempts + 1, last_error = $1 WHERE id = $2
`

type MarkEmailFailedParams struct {
	LastError *string `json:"last_error"`
	ID        int64   `json:"id"`
}

func (q *Queries) MarkEmailFailed(ctx context.Context, arg MarkEmailFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailFailed, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEmailSent = `-- name: MarkEmailSent :execrows
UPDATE email_outbox SET sent_at = now(), attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) MarkEmailSent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailSent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const queueEmail = `-- name: QueueEmail :exec

INSERT INTO email_outbox (to_email, template, payload) VALUES ($1, $2, $3)
`

type QueueEmailParams struct {
	ToEmail  string `json:"to_email"`
	Template string `json:"template"`
	Payload  []byte `json:"payload"`
}

// ---- Transactional email outbox --------------------------------------------
func (q *Queries) QueueEmail(ctx context.Context, arg QueueEmailParams) error {
	_, err := q.db.Exec(ctx, queueEmail, arg.ToEmail, arg.Template, arg.Payload)
	return err
}

const recordAuthAttempt = `-- name: RecordAuthAttempt :exec
INSERT INTO auth_attempts (kind, bucket_key, allowed) VALUES ($1, $2, $3)
`

type RecordAuthAttemptParams struct {
	Kind      AuthChallengeKind `json:"kind"`
	BucketKey string            `json:"bucket_key"`
	Allowed   bool              `json:"allowed"`
}

func (q *Queries) RecordAuthAttempt(ctx context.Context, arg RecordAuthAttemptParams) error {
	_, err := q.db.Exec(ctx, recordAuthAttempt, arg.Kind, arg.BucketKey, arg.Allowed)
	return err
}

const recordLogin = `-- name: RecordLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) RecordLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordLogin, id)
	return err
}

const revokeOtherSessions = `-- name: RevokeOtherSessions :execrows
UPDATE sessions SET revoked_at = now()
 WHERE user_id = $1 AND token_hash <> $2 AND revoked_at IS NULL
`

type RevokeOtherSessionsParams struct {
	UserID        uuid.UUID `json:"user_id"`
	KeepTokenHash []byte    `json:"keep_token_hash"`
}

func (q *Queries) RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOtherSessions, arg.UserID, arg.KeepTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionByToken = `-- name: RevokeSessionByToken :execrows
UPDATE sessions SET revoked_at = now()
 WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByToken(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :execrows
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = true WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateWebAuthnCredentialAfterAssertion = `-- name: UpdateWebAuthnCredentialAfterAssertion :exec
UPDATE webauthn_credentials
   SET sign_count = $1, last_used_at = now()
 WHERE id = $2
`

type UpdateWebAuthnCredentialAfterAssertionParams struct {
	SignCount int64  `json:"sign_count"`
	ID        []byte `json:"id"`
}

func (q *Queries) UpdateWebAuthnCredentialAfterAssertion(ctx context.Context, arg UpdateWebAuthnCredentialAfterAssertionParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialAfterAssertion, arg.SignCount, arg.ID)
	return err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO profiles (user_id, display_name, bio, pronouns, location, is_private)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  bio          = EXCLUDED.bio,
  pronouns     = EXCLUDED.pronouns,
  location     = EXCLUDED.location,
  is_private   = EXCLUDED.is_private
RETURNING user_id, display_name, bio, avatar_key, pronouns, location, is_private, updated_at
`

type UpsertProfileParams struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Bio         string    `json:"bio"`
	Pronouns    *string   `json:"pronouns"`
	Location    *string   `json:"location"`
	IsPrivate   bool      `json:"is_private"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.UserID,
		arg.DisplayName,
		arg.Bio,
		arg.Pronouns,
		arg.Location,
		arg.IsPrivate,
	)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarKey,
		&i.Pronouns,
		&i.Location,
		&i.IsPrivate,
		&i.UpdatedAt,
	)
	return i, err
}

const usernameIsTaken = `-- name: UsernameIsTaken :one
SELECT EXISTS (SELECT 1 FROM users WHERE username = $1) AS taken
`

func (q *Queries) UsernameIsTaken(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameIsTaken, username)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}
