// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: clubs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const channelIsSpoilerGatedFor = `-- name: ChannelIsSpoilerGatedFor :one
SELECT
  ch.spoiler_threshold_bp IS NULL AS ungated,
  coalesce((SELECT r.progress_bp FROM reading_sessions r
             WHERE r.user_id = $1 AND r.work_id = ch.work_id
             ORDER BY r.updated_at DESC LIMIT 1), 0)::integer AS progress_bp,
  ch.spoiler_threshold_bp
  FROM channels ch
 WHERE ch.id = $2
`

type ChannelIsSpoilerGatedForParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ChannelID uuid.UUID `json:"channel_id"`
}

type ChannelIsSpoilerGatedForRow struct {
	Ungated            interface{} `json:"ungated"`
	ProgressBp         int32       `json:"progress_bp"`
	SpoilerThresholdBp *int32      `json:"spoiler_threshold_bp"`
}

// The authorization question the message and channel endpoints must ask before
// returning content: has this reader passed the channel's spoiler threshold?
func (q *Queries) ChannelIsSpoilerGatedFor(ctx context.Context, arg ChannelIsSpoilerGatedForParams) (ChannelIsSpoilerGatedForRow, error) {
	row := q.db.QueryRow(ctx, channelIsSpoilerGatedFor, arg.UserID, arg.ChannelID)
	var i ChannelIsSpoilerGatedForRow
	err := row.Scan(&i.Ungated, &i.ProgressBp, &i.SpoilerThresholdBp)
	return i, err
}

const clearCurrentClubRead = `-- name: ClearCurrentClubRead :execrows
UPDATE club_reads SET is_current = false WHERE club_id = $1 AND is_current
`

func (q *Queries) ClearCurrentClubRead(ctx context.Context, clubID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearCurrentClubRead, clubID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (club_id, kind, name, topic, work_id, spoiler_threshold_bp, position)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
RETURNING id, club_id, kind, name, topic, work_id, spoiler_threshold_bp, position, created_at
`

type CreateChannelParams struct {
	ClubID             uuid.UUID   `json:"club_id"`
	Kind               ChannelKind `json:"kind"`
	Name               string      `json:"name"`
	Topic              string      `json:"topic"`
	WorkID             pgtype.UUID `json:"work_id"`
	SpoilerThresholdBp *int32      `json:"spoiler_threshold_bp"`
	Position           int32       `json:"position"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ClubID,
		arg.Kind,
		arg.Name,
		arg.Topic,
		arg.WorkID,
		arg.SpoilerThresholdBp,
		arg.Position,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.WorkID,
		&i.SpoilerThresholdBp,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createClub = `-- name: CreateClub :one

INSERT INTO clubs (slug, name, description, is_private, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, name, description, is_private, created_by, created_at, updated_at, deleted_at
`

type CreateClubParams struct {
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	IsPrivate   bool        `json:"is_private"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

// Book clubs: memberships, roles, channels, messages, and spoiler gating.
//
// Spoiler gating is data, not UI: a channel carries spoiler_threshold_bp, and
// the read path joins the member's progress on the club's current work so the
// API can refuse to return content the reader has not reached yet. Hiding
// spoilers only in the client would leak them through the network response.
func (q *Queries) CreateClub(ctx context.Context, arg CreateClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, createClub,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.IsPrivate,
		arg.CreatedBy,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (channel_id, user_id, body, reply_to, has_spoilers)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, channel_id, user_id, body, reply_to, has_spoilers, created_at, edited_at, deleted_at
`

type CreateMessageParams struct {
	ChannelID   uuid.UUID   `json:"channel_id"`
	UserID      uuid.UUID   `json:"user_id"`
	Body        string      `json:"body"`
	ReplyTo     pgtype.UUID `json:"reply_to"`
	HasSpoilers bool        `json:"has_spoilers"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ChannelID,
		arg.UserID,
		arg.Body,
		arg.ReplyTo,
		arg.HasSpoilers,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.Body,
		&i.ReplyTo,
		&i.HasSpoilers,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, club_id, kind, name, topic, work_id, spoiler_threshold_bp, position, created_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.WorkID,
		&i.SpoilerThresholdBp,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getClubByID = `-- name: GetClubByID :one
SELECT id, slug, name, description, is_private, created_by, created_at, updated_at, deleted_at FROM clubs WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetClubByID(ctx context.Context, id uuid.UUID) (Club, error) {
	row := q.db.QueryRow(ctx, getClubByID, id)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getClubBySlug = `-- name: GetClubBySlug :one
SELECT c.id, c.slug, c.name, c.description, c.is_private, c.created_by, c.created_at, c.updated_at, c.deleted_at, u.username AS organizer_username,
       (SELECT count(*)::bigint FROM club_memberships cm WHERE cm.club_id = c.id) AS member_count
  FROM clubs c
  LEFT JOIN users u ON u.id = c.created_by
 WHERE c.slug = $1 AND c.deleted_at IS NULL
`

type GetClubBySlugRow struct {
	ID                uuid.UUID          `json:"id"`
	Slug              string             `json:"slug"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	IsPrivate         bool               `json:"is_private"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	OrganizerUsername *string            `json:"organizer_username"`
	MemberCount       int64              `json:"member_count"`
}

func (q *Queries) GetClubBySlug(ctx context.Context, slug string) (GetClubBySlugRow, error) {
	row := q.db.QueryRow(ctx, getClubBySlug, slug)
	var i GetClubBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrganizerUsername,
		&i.MemberCount,
	)
	return i, err
}

const getClubMembership = `-- name: GetClubMembership :one
SELECT club_id, user_id, role, joined_at FROM club_memberships WHERE club_id = $1 AND user_id = $2
`

type GetClubMembershipParams struct {
	ClubID uuid.UUID `json:"club_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetClubMembership(ctx context.Context, arg GetClubMembershipParams) (ClubMembership, error) {
	row := q.db.QueryRow(ctx, getClubMembership, arg.ClubID, arg.UserID)
	var i ClubMembership
	err := row.Scan(
		&i.ClubID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getCurrentClubRead = `-- name: GetCurrentClubRead :one
SELECT cr.id, cr.club_id, cr.work_id, cr.starts_on, cr.ends_on, cr.is_current, w.slug AS work_slug, w.title AS work_title
  FROM club_reads cr JOIN works w ON w.id = cr.work_id
 WHERE cr.club_id = $1 AND cr.is_current
`

type GetCurrentClubReadRow struct {
	ID        uuid.UUID   `json:"id"`
	ClubID    uuid.UUID   `json:"club_id"`
	WorkID    uuid.UUID   `json:"work_id"`
	StartsOn  pgtype.Date `json:"starts_on"`
	EndsOn    pgtype.Date `json:"ends_on"`
	IsCurrent bool        `json:"is_current"`
	WorkSlug  string      `json:"work_slug"`
	WorkTitle string      `json:"work_title"`
}

func (q *Queries) GetCurrentClubRead(ctx context.Context, clubID uuid.UUID) (GetCurrentClubReadRow, error) {
	row := q.db.QueryRow(ctx, getCurrentClubRead, clubID)
	var i GetCurrentClubReadRow
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.WorkID,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
		&i.WorkSlug,
		&i.WorkTitle,
	)
	return i, err
}

const joinClub = `-- name: JoinClub :one
INSERT INTO club_memberships (club_id, user_id, role) VALUES ($1, $2, 'member')
ON CONFLICT (club_id, user_id) DO UPDATE SET role = club_memberships.role
RETURNING club_id, user_id, role, joined_at
`

type JoinClubParams struct {
	ClubID uuid.UUID `json:"club_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) JoinClub(ctx context.Context, arg JoinClubParams) (ClubMembership, error) {
	row := q.db.QueryRow(ctx, joinClub, arg.ClubID, arg.UserID)
	var i ClubMembership
	err := row.Scan(
		&i.ClubID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const leaveClub = `-- name: LeaveClub :execrows
DELETE FROM club_memberships WHERE club_id = $1 AND user_id = $2
`

type LeaveClubParams struct {
	ClubID uuid.UUID `json:"club_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) LeaveClub(ctx context.Context, arg LeaveClubParams) (int64, error) {
	result, err := q.db.Exec(ctx, leaveClub, arg.ClubID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listChannelsForClub = `-- name: ListChannelsForClub :many
SELECT ch.id, ch.club_id, ch.kind, ch.name, ch.topic, ch.work_id, ch.spoiler_threshold_bp, ch.position, ch.created_at,
       -- The reader's own progress on this channel's work, so the API can
       -- decide whether the channel is spoiler-gated for them.
       coalesce((SELECT r.progress_bp FROM reading_sessions r
                  WHERE r.user_id = $1 AND r.work_id = ch.work_id
                  ORDER BY r.updated_at DESC LIMIT 1), 0)::integer AS viewer_progress_bp
  FROM channels ch
 WHERE ch.club_id = $2
 ORDER BY ch.position, ch.name
`

type ListChannelsForClubParams struct {
	ViewerID pgtype.UUID `json:"viewer_id"`
	ClubID   uuid.UUID   `json:"club_id"`
}

type ListChannelsForClubRow struct {
	ID                 uuid.UUID          `json:"id"`
	ClubID             uuid.UUID          `json:"club_id"`
	Kind               ChannelKind        `json:"kind"`
	Name               string             `json:"name"`
	Topic              string             `json:"topic"`
	WorkID             pgtype.UUID        `json:"work_id"`
	SpoilerThresholdBp *int32             `json:"spoiler_threshold_bp"`
	Position           int32              `json:"position"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ViewerProgressBp   int32              `json:"viewer_progress_bp"`
}

func (q *Queries) ListChannelsForClub(ctx context.Context, arg ListChannelsForClubParams) ([]ListChannelsForClubRow, error) {
	rows, err := q.db.Query(ctx, listChannelsForClub, arg.ViewerID, arg.ClubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelsForClubRow{}
	for rows.Next() {
		var i ListChannelsForClubRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Kind,
			&i.Name,
			&i.Topic,
			&i.WorkID,
			&i.SpoilerThresholdBp,
			&i.Position,
			&i.CreatedAt,
			&i.ViewerProgressBp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClubMemberships = `-- name: ListClubMemberships :many
SELECT cm.club_id, cm.user_id, cm.role, cm.joined_at, u.username, p.display_name
  FROM club_memberships cm
  JOIN users u ON u.id = cm.user_id
  LEFT JOIN profiles p ON p.user_id = u.id
 WHERE cm.club_id = $1
 ORDER BY cm.role DESC, cm.joined_at
 LIMIT $3 OFFSET $2
`

type ListClubMembershipsParams struct {
	ClubID uuid.UUID `json:"club_id"`
	Off    int32     `json:"off"`
	Lim    int32     `json:"lim"`
}

type ListClubMembershipsRow struct {
	ClubID      uuid.UUID          `json:"club_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        ClubRole           `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
}

func (q *Queries) ListClubMemberships(ctx context.Context, arg ListClubMembershipsParams) ([]ListClubMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listClubMemberships, arg.ClubID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClubMembershipsRow{}
	for rows.Next() {
		var i ListClubMembershipsRow
		if err := rows.Scan(
			&i.ClubID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClubs = `-- name: ListClubs :many
SELECT c.id, c.slug, c.name, c.description, c.is_private, c.created_by, c.created_at, c.updated_at, c.deleted_at,
       (SELECT count(*)::bigint FROM club_memberships cm WHERE cm.club_id = c.id) AS member_count,
       (SELECT w.title FROM club_reads cr JOIN works w ON w.id = cr.work_id
         WHERE cr.club_id = c.id AND cr.is_current LIMIT 1) AS current_read_title,
       (SELECT w.slug FROM club_reads cr JOIN works w ON w.id = cr.work_id
         WHERE cr.club_id = c.id AND cr.is_current LIMIT 1) AS current_read_slug
  FROM clubs c
 WHERE c.deleted_at IS NULL
   AND (NOT c.is_private OR EXISTS (SELECT 1 FROM club_memberships cm
                                     WHERE cm.club_id = c.id AND cm.user_id = $1))
   AND ($2::text IS NULL OR c.name ILIKE '%' || $2 || '%')
 ORDER BY
   CASE WHEN $1::uuid IS NOT NULL AND EXISTS (
          SELECT 1 FROM club_memberships cm WHERE cm.club_id = c.id
            AND cm.user_id = $1) THEN 0 ELSE 1 END,
   member_count DESC, c.created_at DESC
 LIMIT $4 OFFSET $3
`

type ListClubsParams struct {
	ViewerID pgtype.UUID `json:"viewer_id"`
	Query    *string     `json:"query"`
	Off      int32       `json:"off"`
	Lim      int32       `json:"lim"`
}

type ListClubsRow struct {
	ID               uuid.UUID          `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Description      string             `json:"description"`
	IsPrivate        bool               `json:"is_private"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	MemberCount      int64              `json:"member_count"`
	CurrentReadTitle string             `json:"current_read_title"`
	CurrentReadSlug  string             `json:"current_read_slug"`
}

func (q *Queries) ListClubs(ctx context.Context, arg ListClubsParams) ([]ListClubsRow, error) {
	rows, err := q.db.Query(ctx, listClubs,
		arg.ViewerID,
		arg.Query,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClubsRow{}
	for rows.Next() {
		var i ListClubsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MemberCount,
			&i.CurrentReadTitle,
			&i.CurrentReadSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClubsForUser = `-- name: ListClubsForUser :many
SELECT c.id, c.slug, c.name, c.description, c.is_private, c.created_by, c.created_at, c.updated_at, c.deleted_at, cm.role,
       (SELECT count(*)::bigint FROM club_memberships x WHERE x.club_id = c.id) AS member_count
  FROM club_memberships cm JOIN clubs c ON c.id = cm.club_id
 WHERE cm.user_id = $1 AND c.deleted_at IS NULL
 ORDER BY cm.joined_at DESC
`

type ListClubsForUserRow struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	IsPrivate   bool               `json:"is_private"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Role        ClubRole           `json:"role"`
	MemberCount int64              `json:"member_count"`
}

func (q *Queries) ListClubsForUser(ctx context.Context, userID uuid.UUID) ([]ListClubsForUserRow, error) {
	rows, err := q.db.Query(ctx, listClubsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClubsForUserRow{}
	for rows.Next() {
		var i ListClubsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT m.id, m.channel_id, m.user_id, m.body, m.reply_to, m.has_spoilers, m.created_at, m.edited_at, m.deleted_at, u.username, p.display_name
  FROM messages m
  JOIN users u ON u.id = m.user_id
  LEFT JOIN profiles p ON p.user_id = u.id
 WHERE m.channel_id = $1
   AND m.deleted_at IS NULL
   AND ($2::timestamptz IS NULL OR m.created_at < $2)
   AND ($3::uuid IS NULL OR m.id <> $3)
 ORDER BY m.created_at DESC
 LIMIT $4
`

type ListMessagesParams struct {
	ChannelID       uuid.UUID          `json:"channel_id"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        uuid.UUID          `json:"before_id"`
	Lim             int32              `json:"lim"`
}

type ListMessagesRow struct {
	ID          uuid.UUID          `json:"id"`
	ChannelID   uuid.UUID          `json:"channel_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Body        string             `json:"body"`
	ReplyTo     pgtype.UUID        `json:"reply_to"`
	HasSpoilers bool               `json:"has_spoilers"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EditedAt    pgtype.Timestamptz `json:"edited_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
}

// Keyset pagination on (created_at, id): chat history is unbounded and OFFSET
// would get slower the deeper a reader scrolls.
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.ChannelID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Body,
			&i.ReplyTo,
			&i.HasSpoilers,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClubMemberRole = `-- name: SetClubMemberRole :execrows
UPDATE club_memberships SET role = $1
 WHERE club_id = $2 AND user_id = $3
`

type SetClubMemberRoleParams struct {
	Role   ClubRole  `json:"role"`
	ClubID uuid.UUID `json:"club_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SetClubMemberRole(ctx context.Context, arg SetClubMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setClubMemberRole, arg.Role, arg.ClubID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCurrentClubRead = `-- name: SetCurrentClubRead :one
INSERT INTO club_reads (club_id, work_id, starts_on, ends_on, is_current)
VALUES ($1, $2, $3, $4, true)
RETURNING id, club_id, work_id, starts_on, ends_on, is_current
`

type SetCurrentClubReadParams struct {
	ClubID   uuid.UUID   `json:"club_id"`
	WorkID   uuid.UUID   `json:"work_id"`
	StartsOn pgtype.Date `json:"starts_on"`
	EndsOn   pgtype.Date `json:"ends_on"`
}

func (q *Queries) SetCurrentClubRead(ctx context.Context, arg SetCurrentClubReadParams) (ClubRead, error) {
	row := q.db.QueryRow(ctx, setCurrentClubRead,
		arg.ClubID,
		arg.WorkID,
		arg.StartsOn,
		arg.EndsOn,
	)
	var i ClubRead
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.WorkID,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
	)
	return i, err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :execrows
UPDATE messages SET deleted_at = now()
 WHERE id = $1 AND (user_id = $2 OR $3::boolean)
   AND deleted_at IS NULL
`

type SoftDeleteMessageParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	IsModerator *bool     `json:"is_moderator"`
}

func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMessage, arg.ID, arg.UserID, arg.IsModerator)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
