// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: gutenberg.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimIngestJob = `-- name: ClaimIngestJob :one
UPDATE ingest_jobs
   SET status = 'running', attempts = attempts + 1, started_at = now()
 WHERE id = (
   SELECT j.id FROM ingest_jobs j
    WHERE j.status = 'queued'
       OR (j.status = 'running' AND j.started_at < $1)
    ORDER BY j.scheduled_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1)
RETURNING id, kind, idem_key, payload, status, attempts, last_error, scheduled_at, started_at, finished_at, created_at
`

// Atomic claim: two workers cannot take the same job, and a job stuck in
// `running` past its lease is reclaimable.
func (q *Queries) ClaimIngestJob(ctx context.Context, leaseExpiredBefore pgtype.Timestamptz) (IngestJob, error) {
	row := q.db.QueryRow(ctx, claimIngestJob, leaseExpiredBefore)
	var i IngestJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.IdemKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countGutenbergTexts = `-- name: CountGutenbergTexts :one
SELECT count(*) FROM gutenberg_texts
`

func (q *Queries) CountGutenbergTexts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGutenbergTexts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueIngestJob = `-- name: EnqueueIngestJob :one

INSERT INTO ingest_jobs (kind, idem_key, payload)
VALUES ($1, $2, $3)
ON CONFLICT (idem_key) DO UPDATE SET idem_key = ingest_jobs.idem_key  -- no-op; returns the existing row
RETURNING id, kind, idem_key, payload, status, attempts, last_error, scheduled_at, started_at, finished_at, created_at
`

type EnqueueIngestJobParams struct {
	Kind    string `json:"kind"`
	IdemKey string `json:"idem_key"`
	Payload []byte `json:"payload"`
}

// ---- Ingestion job bookkeeping ---------------------------------------------
func (q *Queries) EnqueueIngestJob(ctx context.Context, arg EnqueueIngestJobParams) (IngestJob, error) {
	row := q.db.QueryRow(ctx, enqueueIngestJob, arg.Kind, arg.IdemKey, arg.Payload)
	var i IngestJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.IdemKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const finishIngestJob = `-- name: FinishIngestJob :execrows
UPDATE ingest_jobs SET status = $1, last_error = $2, finished_at = now()
 WHERE id = $3
`

type FinishIngestJobParams struct {
	Status    IngestJobStatus `json:"status"`
	LastError *string         `json:"last_error"`
	ID        uuid.UUID       `json:"id"`
}

func (q *Queries) FinishIngestJob(ctx context.Context, arg FinishIngestJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishIngestJob, arg.Status, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGutenbergText = `-- name: GetGutenbergText :one
SELECT gutenberg_id, title, authors, language, subjects, formats, edition_id, ingested_at FROM gutenberg_texts WHERE gutenberg_id = $1
`

func (q *Queries) GetGutenbergText(ctx context.Context, gutenbergID int32) (GutenbergText, error) {
	row := q.db.QueryRow(ctx, getGutenbergText, gutenbergID)
	var i GutenbergText
	err := row.Scan(
		&i.GutenbergID,
		&i.Title,
		&i.Authors,
		&i.Language,
		&i.Subjects,
		&i.Formats,
		&i.EditionID,
		&i.IngestedAt,
	)
	return i, err
}

const ingestJobStats = `-- name: IngestJobStats :one
SELECT status, count(*)::bigint AS n FROM ingest_jobs GROUP BY status ORDER BY status
`

type IngestJobStatsRow struct {
	Status IngestJobStatus `json:"status"`
	N      int64           `json:"n"`
}

func (q *Queries) IngestJobStats(ctx context.Context) (IngestJobStatsRow, error) {
	row := q.db.QueryRow(ctx, ingestJobStats)
	var i IngestJobStatsRow
	err := row.Scan(&i.Status, &i.N)
	return i, err
}

const linkGutenbergEdition = `-- name: LinkGutenbergEdition :execrows
UPDATE gutenberg_texts SET edition_id = $1 WHERE gutenberg_id = $2
`

type LinkGutenbergEditionParams struct {
	EditionID   pgtype.UUID `json:"edition_id"`
	GutenbergID int32       `json:"gutenberg_id"`
}

func (q *Queries) LinkGutenbergEdition(ctx context.Context, arg LinkGutenbergEditionParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkGutenbergEdition, arg.EditionID, arg.GutenbergID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listGutenbergTexts = `-- name: ListGutenbergTexts :many
SELECT g.gutenberg_id, g.title, g.authors, g.language, g.subjects, g.formats, g.edition_id, g.ingested_at, w.slug AS work_slug, w.id AS work_id
  FROM gutenberg_texts g
  LEFT JOIN editions e ON e.gutenberg_id = g.gutenberg_id AND e.deleted_at IS NULL
  LEFT JOIN works w ON w.id = e.work_id AND w.deleted_at IS NULL
 WHERE ($1::text IS NULL OR g.language = $1)
   AND ($2::text IS NULL OR g.title ILIKE $2 || '%')
   AND ($3::integer IS NULL OR g.gutenberg_id > $3)
 ORDER BY g.gutenberg_id
 LIMIT $4
`

type ListGutenbergTextsParams struct {
	Language    string  `json:"language"`
	TitlePrefix *string `json:"title_prefix"`
	AfterID     int32   `json:"after_id"`
	Lim         int32   `json:"lim"`
}

type ListGutenbergTextsRow struct {
	GutenbergID int32              `json:"gutenberg_id"`
	Title       string             `json:"title"`
	Authors     []string           `json:"authors"`
	Language    string             `json:"language"`
	Subjects    []string           `json:"subjects"`
	Formats     []byte             `json:"formats"`
	EditionID   pgtype.UUID        `json:"edition_id"`
	IngestedAt  pgtype.Timestamptz `json:"ingested_at"`
	WorkSlug    *string            `json:"work_slug"`
	WorkID      pgtype.UUID        `json:"work_id"`
}

func (q *Queries) ListGutenbergTexts(ctx context.Context, arg ListGutenbergTextsParams) ([]ListGutenbergTextsRow, error) {
	rows, err := q.db.Query(ctx, listGutenbergTexts,
		arg.Language,
		arg.TitlePrefix,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGutenbergTextsRow{}
	for rows.Next() {
		var i ListGutenbergTextsRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Authors,
			&i.Language,
			&i.Subjects,
			&i.Formats,
			&i.EditionID,
			&i.IngestedAt,
			&i.WorkSlug,
			&i.WorkID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestJobsByStatus = `-- name: ListIngestJobsByStatus :many
SELECT id, kind, idem_key, payload, status, attempts, last_error, scheduled_at, started_at, finished_at, created_at FROM ingest_jobs WHERE status = ANY($1::ingest_job_status[])
 ORDER BY scheduled_at LIMIT $2
`

type ListIngestJobsByStatusParams struct {
	Statuses []IngestJobStatus `json:"statuses"`
	Lim      int32             `json:"lim"`
}

func (q *Queries) ListIngestJobsByStatus(ctx context.Context, arg ListIngestJobsByStatusParams) ([]IngestJob, error) {
	rows, err := q.db.Query(ctx, listIngestJobsByStatus, arg.Statuses, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestJob{}
	for rows.Next() {
		var i IngestJob
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.IdemKey,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxAppend = `-- name: OutboxAppend :exec

INSERT INTO outbox (subject, payload) VALUES ($1, $2)
`

type OutboxAppendParams struct {
	Subject string `json:"subject"`
	Payload []byte `json:"payload"`
}

// ---- Transactional outbox ---------------------------------------------------
func (q *Queries) OutboxAppend(ctx context.Context, arg OutboxAppendParams) error {
	_, err := q.db.Exec(ctx, outboxAppend, arg.Subject, arg.Payload)
	return err
}

const outboxDelete = `-- name: OutboxDelete :exec
DELETE FROM outbox WHERE id = ANY($1::bigint[])
`

func (q *Queries) OutboxDelete(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, outboxDelete, ids)
	return err
}

const outboxDepth = `-- name: OutboxDepth :one
SELECT count(*) FROM outbox
`

func (q *Queries) OutboxDepth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, outboxDepth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const outboxPeek = `-- name: OutboxPeek :many
SELECT id, subject, payload, created_at FROM outbox ORDER BY id LIMIT $1
`

func (q *Queries) OutboxPeek(ctx context.Context, lim int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, outboxPeek, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueIngestJob = `-- name: RequeueIngestJob :execrows
UPDATE ingest_jobs
   SET status = 'queued',
       scheduled_at = $1,
       last_error = $2
 WHERE id = $3 AND attempts < $4
`

type RequeueIngestJobParams struct {
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	LastError   *string            `json:"last_error"`
	ID          uuid.UUID          `json:"id"`
	MaxAttempts int32              `json:"max_attempts"`
}

// The retry-at timestamp is computed by the caller so the backoff policy lives
// in one testable place (internal/ingest) instead of in SQL arithmetic.
func (q *Queries) RequeueIngestJob(ctx context.Context, arg RequeueIngestJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueIngestJob,
		arg.ScheduledAt,
		arg.LastError,
		arg.ID,
		arg.MaxAttempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertGutenbergText = `-- name: UpsertGutenbergText :one

INSERT INTO gutenberg_texts (gutenberg_id, title, authors, language, subjects, formats, edition_id)
VALUES ($1, $2, $3, $4, $5, $6,
        $7)
ON CONFLICT (gutenberg_id) DO UPDATE SET
  title      = EXCLUDED.title,
  authors    = EXCLUDED.authors,
  language   = EXCLUDED.language,
  subjects   = EXCLUDED.subjects,
  formats    = gutenberg_texts.formats || EXCLUDED.formats,
  edition_id = COALESCE(EXCLUDED.edition_id, gutenberg_texts.edition_id),
  ingested_at = now()
RETURNING gutenberg_id, title, authors, language, subjects, formats, edition_id, ingested_at
`

type UpsertGutenbergTextParams struct {
	GutenbergID int32       `json:"gutenberg_id"`
	Title       string      `json:"title"`
	Authors     []string    `json:"authors"`
	Language    string      `json:"language"`
	Subjects    []string    `json:"subjects"`
	Formats     []byte      `json:"formats"`
	EditionID   pgtype.UUID `json:"edition_id"`
}

// Project Gutenberg ingestion and public-domain text access.
//
// Compliance shape, mirrored in internal/ingest/gutenberg.go:
//   - we consume Gutenberg's OFFICIAL offline catalog feeds, never the website
//   - each text is downloaded once and cached to our own object storage; we do
//     not hotlink or proxy gutenberg.org at read time
//   - the Gutenberg trademark notice and license header are preserved in
//     metadata, and the reading text is stripped of boilerplate separately
//     (stored apart from the notice, so the notice is never lost)
func (q *Queries) UpsertGutenbergText(ctx context.Context, arg UpsertGutenbergTextParams) (GutenbergText, error) {
	row := q.db.QueryRow(ctx, upsertGutenbergText,
		arg.GutenbergID,
		arg.Title,
		arg.Authors,
		arg.Language,
		arg.Subjects,
		arg.Formats,
		arg.EditionID,
	)
	var i GutenbergText
	err := row.Scan(
		&i.GutenbergID,
		&i.Title,
		&i.Authors,
		&i.Language,
		&i.Subjects,
		&i.Formats,
		&i.EditionID,
		&i.IngestedAt,
	)
	return i, err
}
