// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: imports.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countImportsSince = `-- name: CountImportsSince :one
SELECT count(*) FROM auth_attempts
 WHERE bucket_key = $1 AND kind = 'import' AND created_at > $2
`

type CountImportsSinceParams struct {
	BucketKey string             `json:"bucket_key"`
	Since     pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountImportsSince(ctx context.Context, arg CountImportsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImportsSince, arg.BucketKey, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const customShelfByName = `-- name: CustomShelfByName :one
SELECT id, user_id, kind, name, is_private, created_at, updated_at FROM shelves WHERE user_id = $1 AND kind = 'custom' AND name = $2
`

type CustomShelfByNameParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CustomShelfByName(ctx context.Context, arg CustomShelfByNameParams) (Shelf, error) {
	row := q.db.QueryRow(ctx, customShelfByName, arg.UserID, arg.Name)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findEditionByISBN13 = `-- name: FindEditionByISBN13 :one
SELECT e.id, e.work_id, e.title, e.isbn10, e.isbn13, e.format, e.publisher, e.published_on, e.language, e.page_count, e.gutenberg_id, e.openlibrary_id, e.metadata, e.created_at, e.updated_at, e.deleted_at, w.id AS work_id FROM editions e
  JOIN works w ON w.id = e.work_id
 WHERE e.isbn13 = $1 AND e.deleted_at IS NULL
`

type FindEditionByISBN13Row struct {
	ID            uuid.UUID          `json:"id"`
	WorkID        uuid.UUID          `json:"work_id"`
	Title         string             `json:"title"`
	Isbn10        *string            `json:"isbn10"`
	Isbn13        *string            `json:"isbn13"`
	Format        EditionFormat      `json:"format"`
	Publisher     *string            `json:"publisher"`
	PublishedOn   pgtype.Date        `json:"published_on"`
	Language      string             `json:"language"`
	PageCount     *int32             `json:"page_count"`
	GutenbergID   *int32             `json:"gutenberg_id"`
	OpenlibraryID *string            `json:"openlibrary_id"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	WorkID_2      uuid.UUID          `json:"work_id_2"`
}

func (q *Queries) FindEditionByISBN13(ctx context.Context, isbn13 *string) (FindEditionByISBN13Row, error) {
	row := q.db.QueryRow(ctx, findEditionByISBN13, isbn13)
	var i FindEditionByISBN13Row
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.Title,
		&i.Isbn10,
		&i.Isbn13,
		&i.Format,
		&i.Publisher,
		&i.PublishedOn,
		&i.Language,
		&i.PageCount,
		&i.GutenbergID,
		&i.OpenlibraryID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.WorkID_2,
	)
	return i, err
}

const findWorksByNormalizedTitle = `-- name: FindWorksByNormalizedTitle :many

SELECT w.id, w.slug, w.title, w.subtitle, w.original_language, w.first_published, w.description, w.is_public_domain, w.openlibrary_id, w.rating_sum, w.rating_count, w.created_at, w.updated_at, w.deleted_at FROM works w
 WHERE w.deleted_at IS NULL
   AND lower(regexp_replace(w.title, '^(the|a|an)\s+', '', 'i')) = $1
 ORDER BY w.rating_count DESC
 LIMIT 5
`

// Import support: matching and provenance-stamped writes.
// Matching is conservative — exact normalized title, or ISBN13 — and unmatched
// rows are reported to the reader, never invented as new works.
func (q *Queries) FindWorksByNormalizedTitle(ctx context.Context, needle string) ([]Work, error) {
	rows, err := q.db.Query(ctx, findWorksByNormalizedTitle, needle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Work{}
	for rows.Next() {
		var i Work
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.OriginalLanguage,
			&i.FirstPublished,
			&i.Description,
			&i.IsPublicDomain,
			&i.OpenlibraryID,
			&i.RatingSum,
			&i.RatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importClosedSession = `-- name: ImportClosedSession :one
INSERT INTO reading_sessions (user_id, work_id, edition_id, format, started_on, finished_on, progress_bp)
VALUES ($1, $2, $3, $4,
        $5, $6, 10000)
ON CONFLICT DO NOTHING
RETURNING id, user_id, work_id, edition_id, format, started_on, finished_on, dnf, progress_bp, created_at, updated_at
`

type ImportClosedSessionParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	WorkID     uuid.UUID      `json:"work_id"`
	EditionID  pgtype.UUID    `json:"edition_id"`
	Format     NullReadFormat `json:"format"`
	StartedOn  pgtype.Date    `json:"started_on"`
	FinishedOn pgtype.Date    `json:"finished_on"`
}

// A finished read from another platform: closed on arrival, with the reader's
// own dates. The partial unique index only constrains OPEN sessions, so
// imported history never collides with a current read.
func (q *Queries) ImportClosedSession(ctx context.Context, arg ImportClosedSessionParams) (ReadingSession, error) {
	row := q.db.QueryRow(ctx, importClosedSession,
		arg.UserID,
		arg.WorkID,
		arg.EditionID,
		arg.Format,
		arg.StartedOn,
		arg.FinishedOn,
	)
	var i ReadingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkID,
		&i.EditionID,
		&i.Format,
		&i.StartedOn,
		&i.FinishedOn,
		&i.Dnf,
		&i.ProgressBp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAnnotationImported = `-- name: MarkAnnotationImported :execrows
UPDATE annotations SET imported_from = $1 WHERE id = $2
`

type MarkAnnotationImportedParams struct {
	ImportedFrom *string   `json:"imported_from"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) MarkAnnotationImported(ctx context.Context, arg MarkAnnotationImportedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAnnotationImported, arg.ImportedFrom, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordImportAttempt = `-- name: RecordImportAttempt :exec
INSERT INTO auth_attempts (kind, bucket_key, allowed) VALUES ('import', $1, $2)
`

type RecordImportAttemptParams struct {
	BucketKey string `json:"bucket_key"`
	Allowed   bool   `json:"allowed"`
}

func (q *Queries) RecordImportAttempt(ctx context.Context, arg RecordImportAttemptParams) error {
	_, err := q.db.Exec(ctx, recordImportAttempt, arg.BucketKey, arg.Allowed)
	return err
}

const setShelfItemRating = `-- name: SetShelfItemRating :execrows
UPDATE shelf_items SET rating = $1, imported_from = $2
 WHERE id = $3
`

type SetShelfItemRatingParams struct {
	Rating       *int32    `json:"rating"`
	ImportedFrom *string   `json:"imported_from"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) SetShelfItemRating(ctx context.Context, arg SetShelfItemRatingParams) (int64, error) {
	result, err := q.db.Exec(ctx, setShelfItemRating, arg.Rating, arg.ImportedFrom, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
