// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: library.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToShelf = `-- name: AddToShelf :one
INSERT INTO shelf_items (shelf_id, work_id, edition_id, format)
VALUES ($1, $2, $3, $4)
ON CONFLICT (shelf_id, work_id) DO UPDATE SET
  edition_id = COALESCE(EXCLUDED.edition_id, shelf_items.edition_id),
  format     = COALESCE(EXCLUDED.format, shelf_items.format)
RETURNING id, shelf_id, work_id, edition_id, format, added_at
`

type AddToShelfParams struct {
	ShelfID   uuid.UUID      `json:"shelf_id"`
	WorkID    uuid.UUID      `json:"work_id"`
	EditionID pgtype.UUID    `json:"edition_id"`
	Format    NullReadFormat `json:"format"`
}

func (q *Queries) AddToShelf(ctx context.Context, arg AddToShelfParams) (ShelfItem, error) {
	row := q.db.QueryRow(ctx, addToShelf,
		arg.ShelfID,
		arg.WorkID,
		arg.EditionID,
		arg.Format,
	)
	var i ShelfItem
	err := row.Scan(
		&i.ID,
		&i.ShelfID,
		&i.WorkID,
		&i.EditionID,
		&i.Format,
		&i.AddedAt,
	)
	return i, err
}

const createAnnotation = `-- name: CreateAnnotation :one

INSERT INTO annotations (user_id, edition_id, chapter_idx, start_off, end_off, kind, body, is_private)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, edition_id, chapter_idx, start_off, end_off, kind, body, is_private, created_at, updated_at
`

type CreateAnnotationParams struct {
	UserID     uuid.UUID `json:"user_id"`
	EditionID  uuid.UUID `json:"edition_id"`
	ChapterIdx int32     `json:"chapter_idx"`
	StartOff   int32     `json:"start_off"`
	EndOff     int32     `json:"end_off"`
	Kind       string    `json:"kind"`
	Body       string    `json:"body"`
	IsPrivate  bool      `json:"is_private"`
}

// ---- Annotations ------------------------------------------------------------
func (q *Queries) CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (Annotation, error) {
	row := q.db.QueryRow(ctx, createAnnotation,
		arg.UserID,
		arg.EditionID,
		arg.ChapterIdx,
		arg.StartOff,
		arg.EndOff,
		arg.Kind,
		arg.Body,
		arg.IsPrivate,
	)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EditionID,
		&i.ChapterIdx,
		&i.StartOff,
		&i.EndOff,
		&i.Kind,
		&i.Body,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomShelf = `-- name: CreateCustomShelf :one
INSERT INTO shelves (user_id, kind, name, is_private)
VALUES ($1, 'custom', $2, $3)
RETURNING id, user_id, kind, name, is_private, created_at, updated_at
`

type CreateCustomShelfParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	IsPrivate bool      `json:"is_private"`
}

func (q *Queries) CreateCustomShelf(ctx context.Context, arg CreateCustomShelfParams) (Shelf, error) {
	row := q.db.QueryRow(ctx, createCustomShelf, arg.UserID, arg.Name, arg.IsPrivate)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnnotation = `-- name: DeleteAnnotation :execrows
DELETE FROM annotations WHERE id = $1 AND user_id = $2
`

type DeleteAnnotationParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAnnotation(ctx context.Context, arg DeleteAnnotationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnotation, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCustomShelf = `-- name: DeleteCustomShelf :execrows
DELETE FROM shelves WHERE id = $1 AND user_id = $2 AND kind = 'custom'
`

type DeleteCustomShelfParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// System shelves are permanent (the library's shape depends on them); only
// custom shelves can be removed. Items cascade with the shelf.
func (q *Queries) DeleteCustomShelf(ctx context.Context, arg DeleteCustomShelfParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomShelf, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureSystemShelves = `-- name: EnsureSystemShelves :exec

INSERT INTO shelves (user_id, kind, name)
VALUES ($1, 'want_to_read', 'Want to Read'),
       ($1, 'reading',      'Currently Reading'),
       ($1, 'read',         'Read'),
       ($1, 'dnf',          'Did Not Finish'),
       ($1, 'favorites',    'Favorites')
ON CONFLICT DO NOTHING
`

// Personal library: shelves, shelf items, reading sessions, annotations.
//
// Every query here runs under Row-Level Security (migration 0011) AND filters
// on user_id explicitly. That duplication is intentional: RLS is the last line
// of defense, and an explicit predicate keeps the plan index-driven and the
// intent readable in review.
// Called once at registration. Idempotent, so it is safe to retry.
func (q *Queries) EnsureSystemShelves(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureSystemShelves, userID)
	return err
}

const finishSession = `-- name: FinishSession :execrows
UPDATE reading_sessions
   SET progress_bp = 10000, finished_on = coalesce($1, CURRENT_DATE)
 WHERE user_id = $2 AND work_id = $3 AND finished_on IS NULL AND NOT dnf
`

type FinishSessionParams struct {
	FinishedOn pgtype.Date `json:"finished_on"`
	UserID     uuid.UUID   `json:"user_id"`
	WorkID     uuid.UUID   `json:"work_id"`
}

func (q *Queries) FinishSession(ctx context.Context, arg FinishSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishSession, arg.FinishedOn, arg.UserID, arg.WorkID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLibraryEntry = `-- name: GetLibraryEntry :one
SELECT si.id AS shelf_item_id, s.kind AS shelf_kind, si.format, si.added_at,
       rs.id AS session_id, rs.progress_bp, rs.started_on, rs.finished_on, rs.dnf
  FROM shelves s
  JOIN shelf_items si ON si.shelf_id = s.id AND si.work_id = $1
  LEFT JOIN LATERAL (
        SELECT r.id, r.progress_bp, r.started_on, r.finished_on, r.dnf
          FROM reading_sessions r
         WHERE r.user_id = s.user_id AND r.work_id = $1
         ORDER BY r.updated_at DESC LIMIT 1
       ) rs ON true
 WHERE s.user_id = $2
 ORDER BY CASE s.kind WHEN 'reading' THEN 0 WHEN 'read' THEN 1 ELSE 2 END
 LIMIT 1
`

type GetLibraryEntryParams struct {
	WorkID uuid.UUID `json:"work_id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetLibraryEntryRow struct {
	ShelfItemID uuid.UUID          `json:"shelf_item_id"`
	ShelfKind   ShelfKind          `json:"shelf_kind"`
	Format      NullReadFormat     `json:"format"`
	AddedAt     pgtype.Timestamptz `json:"added_at"`
	SessionID   uuid.UUID          `json:"session_id"`
	ProgressBp  int32              `json:"progress_bp"`
	StartedOn   pgtype.Date        `json:"started_on"`
	FinishedOn  pgtype.Date        `json:"finished_on"`
	Dnf         bool               `json:"dnf"`
}

// What the book page needs to render the caller's own state.
func (q *Queries) GetLibraryEntry(ctx context.Context, arg GetLibraryEntryParams) (GetLibraryEntryRow, error) {
	row := q.db.QueryRow(ctx, getLibraryEntry, arg.WorkID, arg.UserID)
	var i GetLibraryEntryRow
	err := row.Scan(
		&i.ShelfItemID,
		&i.ShelfKind,
		&i.Format,
		&i.AddedAt,
		&i.SessionID,
		&i.ProgressBp,
		&i.StartedOn,
		&i.FinishedOn,
		&i.Dnf,
	)
	return i, err
}

const getOpenSession = `-- name: GetOpenSession :one
SELECT id, user_id, work_id, edition_id, format, started_on, finished_on, dnf, progress_bp, created_at, updated_at FROM reading_sessions
 WHERE user_id = $1 AND work_id = $2 AND finished_on IS NULL AND NOT dnf
`

type GetOpenSessionParams struct {
	UserID uuid.UUID `json:"user_id"`
	WorkID uuid.UUID `json:"work_id"`
}

func (q *Queries) GetOpenSession(ctx context.Context, arg GetOpenSessionParams) (ReadingSession, error) {
	row := q.db.QueryRow(ctx, getOpenSession, arg.UserID, arg.WorkID)
	var i ReadingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkID,
		&i.EditionID,
		&i.Format,
		&i.StartedOn,
		&i.FinishedOn,
		&i.Dnf,
		&i.ProgressBp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShelfByID = `-- name: GetShelfByID :one
SELECT id, user_id, kind, name, is_private, created_at, updated_at FROM shelves WHERE id = $1 AND user_id = $2
`

type GetShelfByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetShelfByID(ctx context.Context, arg GetShelfByIDParams) (Shelf, error) {
	row := q.db.QueryRow(ctx, getShelfByID, arg.ID, arg.UserID)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShelfItem = `-- name: GetShelfItem :one
SELECT id, shelf_id, work_id, edition_id, format, added_at FROM shelf_items WHERE id = $1
`

func (q *Queries) GetShelfItem(ctx context.Context, id uuid.UUID) (ShelfItem, error) {
	row := q.db.QueryRow(ctx, getShelfItem, id)
	var i ShelfItem
	err := row.Scan(
		&i.ID,
		&i.ShelfID,
		&i.WorkID,
		&i.EditionID,
		&i.Format,
		&i.AddedAt,
	)
	return i, err
}

const getSystemShelf = `-- name: GetSystemShelf :one
SELECT id, user_id, kind, name, is_private, created_at, updated_at FROM shelves WHERE user_id = $1 AND kind = $2
`

type GetSystemShelfParams struct {
	UserID uuid.UUID `json:"user_id"`
	Kind   ShelfKind `json:"kind"`
}

func (q *Queries) GetSystemShelf(ctx context.Context, arg GetSystemShelfParams) (Shelf, error) {
	row := q.db.QueryRow(ctx, getSystemShelf, arg.UserID, arg.Kind)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const libraryCountsForUser = `-- name: LibraryCountsForUser :many
SELECT s.kind, count(si.id)::bigint AS n
  FROM shelves s LEFT JOIN shelf_items si ON si.shelf_id = s.id
 WHERE s.user_id = $1
 GROUP BY s.kind
`

type LibraryCountsForUserRow struct {
	Kind ShelfKind `json:"kind"`
	N    int64     `json:"n"`
}

func (q *Queries) LibraryCountsForUser(ctx context.Context, userID uuid.UUID) ([]LibraryCountsForUserRow, error) {
	rows, err := q.db.Query(ctx, libraryCountsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryCountsForUserRow{}
	for rows.Next() {
		var i LibraryCountsForUserRow
		if err := rows.Scan(&i.Kind, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnotationsForEdition = `-- name: ListAnnotationsForEdition :many
SELECT id, user_id, edition_id, chapter_idx, start_off, end_off, kind, body, is_private, created_at, updated_at FROM annotations
 WHERE user_id = $1 AND edition_id = $2
   AND ($3::integer IS NULL OR chapter_idx = $3)
 ORDER BY chapter_idx, start_off
`

type ListAnnotationsForEditionParams struct {
	UserID     uuid.UUID `json:"user_id"`
	EditionID  uuid.UUID `json:"edition_id"`
	ChapterIdx *int32    `json:"chapter_idx"`
}

func (q *Queries) ListAnnotationsForEdition(ctx context.Context, arg ListAnnotationsForEditionParams) ([]Annotation, error) {
	rows, err := q.db.Query(ctx, listAnnotationsForEdition, arg.UserID, arg.EditionID, arg.ChapterIdx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Annotation{}
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EditionID,
			&i.ChapterIdx,
			&i.StartOff,
			&i.EndOff,
			&i.Kind,
			&i.Body,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentlyReading = `-- name: ListCurrentlyReading :many
SELECT rs.id, rs.user_id, rs.work_id, rs.edition_id, rs.format, rs.started_on, rs.finished_on, rs.dnf, rs.progress_bp, rs.created_at, rs.updated_at, w.slug AS work_slug, w.title AS work_title,
       e.gutenberg_id,
       (SELECT a.name FROM work_authors wa JOIN authors a ON a.id = wa.author_id
         WHERE wa.work_id = w.id ORDER BY wa.position LIMIT 1) AS primary_author,
       (SELECT ca.object_key FROM editions e2
          JOIN cover_assets ca ON ca.edition_id = e2.id AND ca.is_primary
         WHERE e2.work_id = w.id AND e2.deleted_at IS NULL LIMIT 1) AS cover_key
  FROM reading_sessions rs
  JOIN works w ON w.id = rs.work_id AND w.deleted_at IS NULL
  LEFT JOIN editions e ON e.id = rs.edition_id
 WHERE rs.user_id = $1 AND rs.finished_on IS NULL AND NOT rs.dnf
 ORDER BY rs.updated_at DESC
 LIMIT $2
`

type ListCurrentlyReadingParams struct {
	UserID uuid.UUID `json:"user_id"`
	Lim    int32     `json:"lim"`
}

type ListCurrentlyReadingRow struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	WorkID        uuid.UUID          `json:"work_id"`
	EditionID     pgtype.UUID        `json:"edition_id"`
	Format        NullReadFormat     `json:"format"`
	StartedOn     pgtype.Date        `json:"started_on"`
	FinishedOn    pgtype.Date        `json:"finished_on"`
	Dnf           bool               `json:"dnf"`
	ProgressBp    int32              `json:"progress_bp"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	WorkSlug      string             `json:"work_slug"`
	WorkTitle     string             `json:"work_title"`
	GutenbergID   *int32             `json:"gutenberg_id"`
	PrimaryAuthor string             `json:"primary_author"`
	CoverKey      *string            `json:"cover_key"`
}

// "Continue reading" on the home page: open sessions, most recently touched
// first. Chronological by activity — never by engagement.
func (q *Queries) ListCurrentlyReading(ctx context.Context, arg ListCurrentlyReadingParams) ([]ListCurrentlyReadingRow, error) {
	rows, err := q.db.Query(ctx, listCurrentlyReading, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentlyReadingRow{}
	for rows.Next() {
		var i ListCurrentlyReadingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkID,
			&i.EditionID,
			&i.Format,
			&i.StartedOn,
			&i.FinishedOn,
			&i.Dnf,
			&i.ProgressBp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkSlug,
			&i.WorkTitle,
			&i.GutenbergID,
			&i.PrimaryAuthor,
			&i.CoverKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingSessions = `-- name: ListReadingSessions :many
SELECT id, user_id, work_id, edition_id, format, started_on, finished_on, dnf, progress_bp, created_at, updated_at FROM reading_sessions
 WHERE user_id = $1 AND ($2::uuid IS NULL OR work_id = $2)
 ORDER BY updated_at DESC
 LIMIT $4 OFFSET $3
`

type ListReadingSessionsParams struct {
	UserID uuid.UUID   `json:"user_id"`
	WorkID pgtype.UUID `json:"work_id"`
	Off    int32       `json:"off"`
	Lim    int32       `json:"lim"`
}

func (q *Queries) ListReadingSessions(ctx context.Context, arg ListReadingSessionsParams) ([]ReadingSession, error) {
	rows, err := q.db.Query(ctx, listReadingSessions,
		arg.UserID,
		arg.WorkID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingSession{}
	for rows.Next() {
		var i ReadingSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkID,
			&i.EditionID,
			&i.Format,
			&i.StartedOn,
			&i.FinishedOn,
			&i.Dnf,
			&i.ProgressBp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShelfItemsWithWork = `-- name: ListShelfItemsWithWork :many
SELECT si.id, si.shelf_id, si.work_id, si.edition_id, si.format, si.added_at,
       s.kind AS shelf_kind, s.name AS shelf_name, s.is_private,
       w.slug AS work_slug, w.title AS work_title, w.first_published,
       w.rating_sum, w.rating_count, w.is_public_domain,
       rs.id AS session_id, rs.progress_bp, rs.started_on, rs.finished_on, rs.dnf,
       (SELECT a.name FROM work_authors wa JOIN authors a ON a.id = wa.author_id
         WHERE wa.work_id = w.id ORDER BY wa.position LIMIT 1) AS primary_author,
       (SELECT ca.object_key FROM editions e
          JOIN cover_assets ca ON ca.edition_id = e.id AND ca.is_primary
         WHERE e.work_id = w.id AND e.deleted_at IS NULL LIMIT 1) AS cover_key
  FROM shelf_items si
  JOIN shelves s ON s.id = si.shelf_id
  JOIN works w   ON w.id = si.work_id AND w.deleted_at IS NULL
  LEFT JOIN LATERAL (
        SELECT r.id, r.progress_bp, r.started_on, r.finished_on, r.dnf
          FROM reading_sessions r
         WHERE r.user_id = s.user_id AND r.work_id = si.work_id
         ORDER BY r.updated_at DESC
         LIMIT 1
       ) rs ON true
 WHERE s.user_id = $1
   AND ($2::shelf_kind IS NULL OR s.kind = $2)
 ORDER BY si.added_at DESC
 LIMIT $4 OFFSET $3
`

type ListShelfItemsWithWorkParams struct {
	UserID    uuid.UUID     `json:"user_id"`
	ShelfKind NullShelfKind `json:"shelf_kind"`
	Off       int32         `json:"off"`
	Lim       int32         `json:"lim"`
}

type ListShelfItemsWithWorkRow struct {
	ID             uuid.UUID          `json:"id"`
	ShelfID        uuid.UUID          `json:"shelf_id"`
	WorkID         uuid.UUID          `json:"work_id"`
	EditionID      pgtype.UUID        `json:"edition_id"`
	Format         NullReadFormat     `json:"format"`
	AddedAt        pgtype.Timestamptz `json:"added_at"`
	ShelfKind      ShelfKind          `json:"shelf_kind"`
	ShelfName      string             `json:"shelf_name"`
	IsPrivate      bool               `json:"is_private"`
	WorkSlug       string             `json:"work_slug"`
	WorkTitle      string             `json:"work_title"`
	FirstPublished *int32             `json:"first_published"`
	RatingSum      int64              `json:"rating_sum"`
	RatingCount    int64              `json:"rating_count"`
	IsPublicDomain bool               `json:"is_public_domain"`
	SessionID      uuid.UUID          `json:"session_id"`
	ProgressBp     int32              `json:"progress_bp"`
	StartedOn      pgtype.Date        `json:"started_on"`
	FinishedOn     pgtype.Date        `json:"finished_on"`
	Dnf            bool               `json:"dnf"`
	PrimaryAuthor  string             `json:"primary_author"`
	CoverKey       *string            `json:"cover_key"`
}

// The library view. One row per shelved work, with the most recent reading
// session joined laterally so rereads never multiply rows.
func (q *Queries) ListShelfItemsWithWork(ctx context.Context, arg ListShelfItemsWithWorkParams) ([]ListShelfItemsWithWorkRow, error) {
	rows, err := q.db.Query(ctx, listShelfItemsWithWork,
		arg.UserID,
		arg.ShelfKind,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShelfItemsWithWorkRow{}
	for rows.Next() {
		var i ListShelfItemsWithWorkRow
		if err := rows.Scan(
			&i.ID,
			&i.ShelfID,
			&i.WorkID,
			&i.EditionID,
			&i.Format,
			&i.AddedAt,
			&i.ShelfKind,
			&i.ShelfName,
			&i.IsPrivate,
			&i.WorkSlug,
			&i.WorkTitle,
			&i.FirstPublished,
			&i.RatingSum,
			&i.RatingCount,
			&i.IsPublicDomain,
			&i.SessionID,
			&i.ProgressBp,
			&i.StartedOn,
			&i.FinishedOn,
			&i.Dnf,
			&i.PrimaryAuthor,
			&i.CoverKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShelvesForUser = `-- name: ListShelvesForUser :many
SELECT s.id, s.user_id, s.kind, s.name, s.is_private, s.created_at, s.updated_at,
       (SELECT count(*) FROM shelf_items si WHERE si.shelf_id = s.id) AS item_count
  FROM shelves s
 WHERE s.user_id = $1
 ORDER BY
   CASE s.kind
     WHEN 'reading'      THEN 0
     WHEN 'want_to_read' THEN 1
     WHEN 'read'         THEN 2
     WHEN 'favorites'    THEN 3
     WHEN 'dnf'          THEN 4
     ELSE 5
   END,
   s.name
`

type ListShelvesForUserRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Kind      ShelfKind          `json:"kind"`
	Name      string             `json:"name"`
	IsPrivate bool               `json:"is_private"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ItemCount int64              `json:"item_count"`
}

func (q *Queries) ListShelvesForUser(ctx context.Context, userID uuid.UUID) ([]ListShelvesForUserRow, error) {
	rows, err := q.db.Query(ctx, listShelvesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShelvesForUserRow{}
	for rows.Next() {
		var i ListShelvesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Name,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionDNF = `-- name: MarkSessionDNF :execrows
UPDATE reading_sessions
   SET dnf = true, finished_on = coalesce($1, CURRENT_DATE)
 WHERE user_id = $2 AND work_id = $3 AND finished_on IS NULL
`

type MarkSessionDNFParams struct {
	FinishedOn pgtype.Date `json:"finished_on"`
	UserID     uuid.UUID   `json:"user_id"`
	WorkID     uuid.UUID   `json:"work_id"`
}

func (q *Queries) MarkSessionDNF(ctx context.Context, arg MarkSessionDNFParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionDNF, arg.FinishedOn, arg.UserID, arg.WorkID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const readingStatsForUser = `-- name: ReadingStatsForUser :one
SELECT
  count(*) FILTER (WHERE finished_on IS NOT NULL AND NOT dnf)::bigint AS books_finished,
  count(*) FILTER (WHERE dnf)::bigint                                 AS books_dnf,
  count(*) FILTER (WHERE finished_on IS NULL AND NOT dnf)::bigint     AS books_in_progress,
  coalesce(sum(progress_bp) FILTER (WHERE finished_on IS NULL AND NOT dnf), 0)::bigint AS open_progress_bp
FROM reading_sessions
WHERE user_id = $1
`

type ReadingStatsForUserRow struct {
	BooksFinished   int64 `json:"books_finished"`
	BooksDnf        int64 `json:"books_dnf"`
	BooksInProgress int64 `json:"books_in_progress"`
	OpenProgressBp  int64 `json:"open_progress_bp"`
}

func (q *Queries) ReadingStatsForUser(ctx context.Context, userID uuid.UUID) (ReadingStatsForUserRow, error) {
	row := q.db.QueryRow(ctx, readingStatsForUser, userID)
	var i ReadingStatsForUserRow
	err := row.Scan(
		&i.BooksFinished,
		&i.BooksDnf,
		&i.BooksInProgress,
		&i.OpenProgressBp,
	)
	return i, err
}

const removeFromShelf = `-- name: RemoveFromShelf :execrows
DELETE FROM shelf_items WHERE shelf_id = $1 AND work_id = $2
`

type RemoveFromShelfParams struct {
	ShelfID uuid.UUID `json:"shelf_id"`
	WorkID  uuid.UUID `json:"work_id"`
}

func (q *Queries) RemoveFromShelf(ctx context.Context, arg RemoveFromShelfParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFromShelf, arg.ShelfID, arg.WorkID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeWorkFromUserShelves = `-- name: RemoveWorkFromUserShelves :execrows
DELETE FROM shelf_items
 WHERE work_id = $1
   AND shelf_id IN (SELECT s.id FROM shelves s
                     WHERE s.user_id = $2
                       AND s.kind IN ('want_to_read', 'reading', 'read', 'dnf')
                       AND s.kind <> $3)
`

type RemoveWorkFromUserShelvesParams struct {
	WorkID   uuid.UUID `json:"work_id"`
	UserID   uuid.UUID `json:"user_id"`
	KeepKind ShelfKind `json:"keep_kind"`
}

// Moving a book between reading states must not leave it on two shelves at
// once ("Currently Reading" and "Read" simultaneously is a data bug, not a
// user preference). Favorites is exempt: it is orthogonal to reading state.
func (q *Queries) RemoveWorkFromUserShelves(ctx context.Context, arg RemoveWorkFromUserShelvesParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeWorkFromUserShelves, arg.WorkID, arg.UserID, arg.KeepKind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startReread = `-- name: StartReread :one
INSERT INTO reading_sessions (user_id, work_id, edition_id, format, started_on, progress_bp)
VALUES ($1, $2, $3, $4, CURRENT_DATE, 0)
RETURNING id, user_id, work_id, edition_id, format, started_on, finished_on, dnf, progress_bp, created_at, updated_at
`

type StartRereadParams struct {
	UserID    uuid.UUID      `json:"user_id"`
	WorkID    uuid.UUID      `json:"work_id"`
	EditionID pgtype.UUID    `json:"edition_id"`
	Format    NullReadFormat `json:"format"`
}

// Closes any open session, then opens a fresh one: a reread is a new row, never
// a mutation of history.
func (q *Queries) StartReread(ctx context.Context, arg StartRereadParams) (ReadingSession, error) {
	row := q.db.QueryRow(ctx, startReread,
		arg.UserID,
		arg.WorkID,
		arg.EditionID,
		arg.Format,
	)
	var i ReadingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkID,
		&i.EditionID,
		&i.Format,
		&i.StartedOn,
		&i.FinishedOn,
		&i.Dnf,
		&i.ProgressBp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAnnotationBody = `-- name: UpdateAnnotationBody :execrows
UPDATE annotations SET body = $1, kind = $2
 WHERE id = $3 AND user_id = $4
`

type UpdateAnnotationBodyParams struct {
	Body   string    `json:"body"`
	Kind   string    `json:"kind"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateAnnotationBody(ctx context.Context, arg UpdateAnnotationBodyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAnnotationBody,
		arg.Body,
		arg.Kind,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateShelfPrivacy = `-- name: UpdateShelfPrivacy :execrows
UPDATE shelves SET is_private = $1
 WHERE id = $2 AND user_id = $3 AND kind = 'custom'
`

type UpdateShelfPrivacyParams struct {
	IsPrivate bool      `json:"is_private"`
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateShelfPrivacy(ctx context.Context, arg UpdateShelfPrivacyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateShelfPrivacy, arg.IsPrivate, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :one

INSERT INTO reading_sessions (user_id, work_id, edition_id, format, started_on, progress_bp)
VALUES ($1, $2, $3, $4,
        CURRENT_DATE, $5)
ON CONFLICT (user_id, work_id) WHERE finished_on IS NULL AND NOT dnf
DO UPDATE SET
  progress_bp = EXCLUDED.progress_bp,
  edition_id  = COALESCE(EXCLUDED.edition_id, reading_sessions.edition_id),
  format      = COALESCE(EXCLUDED.format, reading_sessions.format),
  finished_on = CASE WHEN EXCLUDED.progress_bp >= 10000 THEN CURRENT_DATE ELSE NULL END
RETURNING id, user_id, work_id, edition_id, format, started_on, finished_on, dnf, progress_bp, created_at, updated_at
`

type UpsertReadingProgressParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	WorkID     uuid.UUID      `json:"work_id"`
	EditionID  pgtype.UUID    `json:"edition_id"`
	Format     NullReadFormat `json:"format"`
	ProgressBp int32          `json:"progress_bp"`
}

// ---- Reading sessions -------------------------------------------------------
// Upserts the single open session for (user, work). Reaching 100% closes it and
// stamps the finish date; the partial unique index guarantees one open session.
func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) (ReadingSession, error) {
	row := q.db.QueryRow(ctx, upsertReadingProgress,
		arg.UserID,
		arg.WorkID,
		arg.EditionID,
		arg.Format,
		arg.ProgressBp,
	)
	var i ReadingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkID,
		&i.EditionID,
		&i.Format,
		&i.StartedOn,
		&i.FinishedOn,
		&i.Dnf,
		&i.ProgressBp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
