// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthChallengeKind string

const (
	AuthChallengeKindWebauthnRegistration AuthChallengeKind = "webauthn_registration"
	AuthChallengeKindWebauthnLogin        AuthChallengeKind = "webauthn_login"
	AuthChallengeKindMagicLink            AuthChallengeKind = "magic_link"
	AuthChallengeKindEmailVerification    AuthChallengeKind = "email_verification"
	AuthChallengeKindImport               AuthChallengeKind = "import"
)

func (e *AuthChallengeKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthChallengeKind(s)
	case string:
		*e = AuthChallengeKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthChallengeKind: %T", src)
	}
	return nil
}

type NullAuthChallengeKind struct {
	AuthChallengeKind AuthChallengeKind `json:"auth_challenge_kind"`
	Valid             bool              `json:"valid"` // Valid is true if AuthChallengeKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthChallengeKind) Scan(value interface{}) error {
	if value == nil {
		ns.AuthChallengeKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthChallengeKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthChallengeKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthChallengeKind), nil
}

type ChannelKind string

const (
	ChannelKindText          ChannelKind = "text"
	ChannelKindVoice         ChannelKind = "voice"
	ChannelKindVideo         ChannelKind = "video"
	ChannelKindAnnouncements ChannelKind = "announcements"
)

func (e *ChannelKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChannelKind(s)
	case string:
		*e = ChannelKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ChannelKind: %T", src)
	}
	return nil
}

type NullChannelKind struct {
	ChannelKind ChannelKind `json:"channel_kind"`
	Valid       bool        `json:"valid"` // Valid is true if ChannelKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannelKind) Scan(value interface{}) error {
	if value == nil {
		ns.ChannelKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChannelKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannelKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChannelKind), nil
}

type ClubRole string

const (
	ClubRoleMember    ClubRole = "member"
	ClubRoleModerator ClubRole = "moderator"
	ClubRoleOrganizer ClubRole = "organizer"
)

func (e *ClubRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClubRole(s)
	case string:
		*e = ClubRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ClubRole: %T", src)
	}
	return nil
}

type NullClubRole struct {
	ClubRole ClubRole `json:"club_role"`
	Valid    bool     `json:"valid"` // Valid is true if ClubRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClubRole) Scan(value interface{}) error {
	if value == nil {
		ns.ClubRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClubRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClubRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClubRole), nil
}

type CoverLicense string

const (
	CoverLicensePublicDomain     CoverLicense = "public_domain"
	CoverLicenseCc0              CoverLicense = "cc0"
	CoverLicenseCcBy             CoverLicense = "cc_by"
	CoverLicenseCcBySa           CoverLicense = "cc_by_sa"
	CoverLicenseFairUseThumbnail CoverLicense = "fair_use_thumbnail"
	CoverLicenseUserUpload       CoverLicense = "user_upload"
	CoverLicenseUnknown          CoverLicense = "unknown"
)

func (e *CoverLicense) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoverLicense(s)
	case string:
		*e = CoverLicense(s)
	default:
		return fmt.Errorf("unsupported scan type for CoverLicense: %T", src)
	}
	return nil
}

type NullCoverLicense struct {
	CoverLicense CoverLicense `json:"cover_license"`
	Valid        bool         `json:"valid"` // Valid is true if CoverLicense is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoverLicense) Scan(value interface{}) error {
	if value == nil {
		ns.CoverLicense, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoverLicense.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoverLicense) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoverLicense), nil
}

type EditionFormat string

const (
	EditionFormatHardcover EditionFormat = "hardcover"
	EditionFormatPaperback EditionFormat = "paperback"
	EditionFormatEbook     EditionFormat = "ebook"
	EditionFormatAudiobook EditionFormat = "audiobook"
	EditionFormatGutenberg EditionFormat = "gutenberg"
	EditionFormatOther     EditionFormat = "other"
)

func (e *EditionFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EditionFormat(s)
	case string:
		*e = EditionFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for EditionFormat: %T", src)
	}
	return nil
}

type NullEditionFormat struct {
	EditionFormat EditionFormat `json:"edition_format"`
	Valid         bool          `json:"valid"` // Valid is true if EditionFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEditionFormat) Scan(value interface{}) error {
	if value == nil {
		ns.EditionFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EditionFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEditionFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EditionFormat), nil
}

type IngestJobStatus string

const (
	IngestJobStatusQueued    IngestJobStatus = "queued"
	IngestJobStatusRunning   IngestJobStatus = "running"
	IngestJobStatusSucceeded IngestJobStatus = "succeeded"
	IngestJobStatusFailed    IngestJobStatus = "failed"
	IngestJobStatusDead      IngestJobStatus = "dead"
)

func (e *IngestJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IngestJobStatus(s)
	case string:
		*e = IngestJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IngestJobStatus: %T", src)
	}
	return nil
}

type NullIngestJobStatus struct {
	IngestJobStatus IngestJobStatus `json:"ingest_job_status"`
	Valid           bool            `json:"valid"` // Valid is true if IngestJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIngestJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IngestJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IngestJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIngestJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IngestJobStatus), nil
}

type ModerationActionKind string

const (
	ModerationActionKindWarning        ModerationActionKind = "warning"
	ModerationActionKindContentRemoval ModerationActionKind = "content_removal"
	ModerationActionKindTempSuspension ModerationActionKind = "temp_suspension"
	ModerationActionKindPermanentBan   ModerationActionKind = "permanent_ban"
	ModerationActionKindRestore        ModerationActionKind = "restore"
	ModerationActionKindNote           ModerationActionKind = "note"
)

func (e *ModerationActionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModerationActionKind(s)
	case string:
		*e = ModerationActionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ModerationActionKind: %T", src)
	}
	return nil
}

type NullModerationActionKind struct {
	ModerationActionKind ModerationActionKind `json:"moderation_action_kind"`
	Valid                bool                 `json:"valid"` // Valid is true if ModerationActionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModerationActionKind) Scan(value interface{}) error {
	if value == nil {
		ns.ModerationActionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModerationActionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModerationActionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModerationActionKind), nil
}

type NoteStatus string

const (
	NoteStatusDraft     NoteStatus = "draft"
	NoteStatusInReview  NoteStatus = "in_review"
	NoteStatusPublished NoteStatus = "published"
	NoteStatusRetracted NoteStatus = "retracted"
)

func (e *NoteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NoteStatus(s)
	case string:
		*e = NoteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NoteStatus: %T", src)
	}
	return nil
}

type NullNoteStatus struct {
	NoteStatus NoteStatus `json:"note_status"`
	Valid      bool       `json:"valid"` // Valid is true if NoteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNoteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NoteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NoteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNoteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NoteStatus), nil
}

type ReadFormat string

const (
	ReadFormatPhysical     ReadFormat = "physical"
	ReadFormatEbook        ReadFormat = "ebook"
	ReadFormatAudiobook    ReadFormat = "audiobook"
	ReadFormatPublicDomain ReadFormat = "public_domain"
	ReadFormatLibraryCopy  ReadFormat = "library_copy"
	ReadFormatOther        ReadFormat = "other"
)

func (e *ReadFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReadFormat(s)
	case string:
		*e = ReadFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for ReadFormat: %T", src)
	}
	return nil
}

type NullReadFormat struct {
	ReadFormat ReadFormat `json:"read_format"`
	Valid      bool       `json:"valid"` // Valid is true if ReadFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReadFormat) Scan(value interface{}) error {
	if value == nil {
		ns.ReadFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReadFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReadFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReadFormat), nil
}

type ReportReason string

const (
	ReportReasonSpam           ReportReason = "spam"
	ReportReasonAiSlop         ReportReason = "ai_slop"
	ReportReasonHarassment     ReportReason = "harassment"
	ReportReasonHate           ReportReason = "hate"
	ReportReasonThreat         ReportReason = "threat"
	ReportReasonSexualContent  ReportReason = "sexual_content"
	ReportReasonMisinformation ReportReason = "misinformation"
	ReportReasonCopyright      ReportReason = "copyright"
	ReportReasonImpersonation  ReportReason = "impersonation"
	ReportReasonFakeReview     ReportReason = "fake_review"
	ReportReasonOther          ReportReason = "other"
)

func (e *ReportReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportReason(s)
	case string:
		*e = ReportReason(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportReason: %T", src)
	}
	return nil
}

type NullReportReason struct {
	ReportReason ReportReason `json:"report_reason"`
	Valid        bool         `json:"valid"` // Valid is true if ReportReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportReason) Scan(value interface{}) error {
	if value == nil {
		ns.ReportReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportReason), nil
}

type ReportStatus string

const (
	ReportStatusOpen      ReportStatus = "open"
	ReportStatusInReview  ReportStatus = "in_review"
	ReportStatusActioned  ReportStatus = "actioned"
	ReportStatusDismissed ReportStatus = "dismissed"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus `json:"report_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type ScholarStatus string

const (
	ScholarStatusPending  ScholarStatus = "pending"
	ScholarStatusVerified ScholarStatus = "verified"
	ScholarStatusRejected ScholarStatus = "rejected"
	ScholarStatusRevoked  ScholarStatus = "revoked"
)

func (e *ScholarStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScholarStatus(s)
	case string:
		*e = ScholarStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScholarStatus: %T", src)
	}
	return nil
}

type NullScholarStatus struct {
	ScholarStatus ScholarStatus `json:"scholar_status"`
	Valid         bool          `json:"valid"` // Valid is true if ScholarStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScholarStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScholarStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScholarStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScholarStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScholarStatus), nil
}

type ShelfKind string

const (
	ShelfKindWantToRead ShelfKind = "want_to_read"
	ShelfKindReading    ShelfKind = "reading"
	ShelfKindRead       ShelfKind = "read"
	ShelfKindDnf        ShelfKind = "dnf"
	ShelfKindFavorites  ShelfKind = "favorites"
	ShelfKindCustom     ShelfKind = "custom"
)

func (e *ShelfKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShelfKind(s)
	case string:
		*e = ShelfKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ShelfKind: %T", src)
	}
	return nil
}

type NullShelfKind struct {
	ShelfKind ShelfKind `json:"shelf_kind"`
	Valid     bool      `json:"valid"` // Valid is true if ShelfKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShelfKind) Scan(value interface{}) error {
	if value == nil {
		ns.ShelfKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShelfKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShelfKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShelfKind), nil
}

type UserRole string

const (
	UserRoleReader        UserRole = "reader"
	UserRoleTrustedReader UserRole = "trusted_reader"
	UserRoleScholar       UserRole = "scholar"
	UserRoleModerator     UserRole = "moderator"
	UserRoleAdmin         UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AffiliateLink struct {
	ID         uuid.UUID          `json:"id"`
	EditionID  uuid.UUID          `json:"edition_id"`
	Vendor     string             `json:"vendor"`
	Url        string             `json:"url"`
	Region     string             `json:"region"`
	Disclosure string             `json:"disclosure"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Annotation struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	EditionID    uuid.UUID          `json:"edition_id"`
	ChapterIdx   int32              `json:"chapter_idx"`
	StartOff     int32              `json:"start_off"`
	EndOff       int32              `json:"end_off"`
	Kind         string             `json:"kind"`
	Body         string             `json:"body"`
	IsPrivate    bool               `json:"is_private"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ImportedFrom *string            `json:"imported_from"`
}

type AuthAttempt struct {
	ID        int64              `json:"id"`
	Kind      AuthChallengeKind  `json:"kind"`
	BucketKey string             `json:"bucket_key"`
	Allowed   bool               `json:"allowed"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuthChallenge struct {
	ID          uuid.UUID          `json:"id"`
	Kind        AuthChallengeKind  `json:"kind"`
	UserID      pgtype.UUID        `json:"user_id"`
	Email       *string            `json:"email"`
	Challenge   []byte             `json:"challenge"`
	SessionData []byte             `json:"session_data"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Author struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	SortName      string             `json:"sort_name"`
	Bio           string             `json:"bio"`
	BirthYear     *int32             `json:"birth_year"`
	DeathYear     *int32             `json:"death_year"`
	OpenlibraryID *string            `json:"openlibrary_id"`
	WikidataID    *string            `json:"wikidata_id"`
	IsClaimed     bool               `json:"is_claimed"`
	ClaimedBy     pgtype.UUID        `json:"claimed_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	Slug          string             `json:"slug"`
}

type Channel struct {
	ID                 uuid.UUID          `json:"id"`
	ClubID             uuid.UUID          `json:"club_id"`
	Kind               ChannelKind        `json:"kind"`
	Name               string             `json:"name"`
	Topic              string             `json:"topic"`
	WorkID             pgtype.UUID        `json:"work_id"`
	SpoilerThresholdBp *int32             `json:"spoiler_threshold_bp"`
	Position           int32              `json:"position"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Club struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	IsPrivate   bool               `json:"is_private"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ClubMembership struct {
	ClubID   uuid.UUID          `json:"club_id"`
	UserID   uuid.UUID          `json:"user_id"`
	Role     ClubRole           `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type ClubRead struct {
	ID        uuid.UUID   `json:"id"`
	ClubID    uuid.UUID   `json:"club_id"`
	WorkID    uuid.UUID   `json:"work_id"`
	StartsOn  pgtype.Date `json:"starts_on"`
	EndsOn    pgtype.Date `json:"ends_on"`
	IsCurrent bool        `json:"is_current"`
}

type ContributionLedger struct {
	ID        int64              `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Kind      string             `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CoverAsset struct {
	ID              uuid.UUID          `json:"id"`
	EditionID       uuid.UUID          `json:"edition_id"`
	Source          string             `json:"source"`
	SourceUrl       *string            `json:"source_url"`
	License         CoverLicense       `json:"license"`
	LicenseUrl      *string            `json:"license_url"`
	AttributionText *string            `json:"attribution_text"`
	ObjectKey       *string            `json:"object_key"`
	Cacheable       bool               `json:"cacheable"`
	CacheExpiresAt  pgtype.Timestamptz `json:"cache_expires_at"`
	UploadedBy      pgtype.UUID        `json:"uploaded_by"`
	IsPrimary       bool               `json:"is_primary"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Edition struct {
	ID            uuid.UUID          `json:"id"`
	WorkID        uuid.UUID          `json:"work_id"`
	Title         string             `json:"title"`
	Isbn10        *string            `json:"isbn10"`
	Isbn13        *string            `json:"isbn13"`
	Format        EditionFormat      `json:"format"`
	Publisher     *string            `json:"publisher"`
	PublishedOn   pgtype.Date        `json:"published_on"`
	Language      string             `json:"language"`
	PageCount     *int32             `json:"page_count"`
	GutenbergID   *int32             `json:"gutenberg_id"`
	OpenlibraryID *string            `json:"openlibrary_id"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type EmailOutbox struct {
	ID        int64              `json:"id"`
	ToEmail   string             `json:"to_email"`
	Template  string             `json:"template"`
	Payload   []byte             `json:"payload"`
	Attempts  int32              `json:"attempts"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	LastError *string            `json:"last_error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ExternalIdentifier struct {
	ID        uuid.UUID `json:"id"`
	EditionID uuid.UUID `json:"edition_id"`
	Namespace string    `json:"namespace"`
	Value     string    `json:"value"`
}

type Follow struct {
	FollowerID uuid.UUID          `json:"follower_id"`
	FolloweeID uuid.UUID          `json:"followee_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type GutenbergText struct {
	GutenbergID int32              `json:"gutenberg_id"`
	Title       string             `json:"title"`
	Authors     []string           `json:"authors"`
	Language    string             `json:"language"`
	Subjects    []string           `json:"subjects"`
	Formats     []byte             `json:"formats"`
	EditionID   pgtype.UUID        `json:"edition_id"`
	IngestedAt  pgtype.Timestamptz `json:"ingested_at"`
}

type IngestJob struct {
	ID          uuid.UUID          `json:"id"`
	Kind        string             `json:"kind"`
	IdemKey     string             `json:"idem_key"`
	Payload     []byte             `json:"payload"`
	Status      IngestJobStatus    `json:"status"`
	Attempts    int32              `json:"attempts"`
	LastError   *string            `json:"last_error"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID          uuid.UUID          `json:"id"`
	ChannelID   uuid.UUID          `json:"channel_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Body        string             `json:"body"`
	ReplyTo     pgtype.UUID        `json:"reply_to"`
	HasSpoilers bool               `json:"has_spoilers"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EditedAt    pgtype.Timestamptz `json:"edited_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ModerationAction struct {
	ID          uuid.UUID            `json:"id"`
	ModeratorID pgtype.UUID          `json:"moderator_id"`
	TargetUser  pgtype.UUID          `json:"target_user"`
	ReportID    pgtype.UUID          `json:"report_id"`
	Kind        ModerationActionKind `json:"kind"`
	Rationale   string               `json:"rationale"`
	ExpiresAt   pgtype.Timestamptz   `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz   `json:"created_at"`
}

type NoteCitation struct {
	ID       uuid.UUID `json:"id"`
	NoteID   uuid.UUID `json:"note_id"`
	Citation string    `json:"citation"`
	Url      *string   `json:"url"`
	Position int32     `json:"position"`
}

type NoteReview struct {
	NoteID     uuid.UUID          `json:"note_id"`
	ReviewerID uuid.UUID          `json:"reviewer_id"`
	Approved   bool               `json:"approved"`
	Comments   string             `json:"comments"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type NoteRevision struct {
	ID        uuid.UUID          `json:"id"`
	NoteID    uuid.UUID          `json:"note_id"`
	Version   int32              `json:"version"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	EditedBy  pgtype.UUID        `json:"edited_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Kind      string             `json:"kind"`
	Payload   []byte             `json:"payload"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Outbox struct {
	ID        int64              `json:"id"`
	Subject   string             `json:"subject"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	UserID      uuid.UUID          `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Bio         string             `json:"bio"`
	AvatarKey   *string            `json:"avatar_key"`
	Pronouns    *string            `json:"pronouns"`
	Location    *string            `json:"location"`
	IsPrivate   bool               `json:"is_private"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PushSubscription struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Endpoint     string             `json:"endpoint"`
	P256dh       []byte             `json:"p256dh"`
	Auth         []byte             `json:"auth"`
	UserAgent    *string            `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastPushedAt pgtype.Timestamptz `json:"last_pushed_at"`
}

type ReadingSession struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	WorkID     uuid.UUID          `json:"work_id"`
	EditionID  pgtype.UUID        `json:"edition_id"`
	Format     NullReadFormat     `json:"format"`
	StartedOn  pgtype.Date        `json:"started_on"`
	FinishedOn pgtype.Date        `json:"finished_on"`
	Dnf        bool               `json:"dnf"`
	ProgressBp int32              `json:"progress_bp"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Report struct {
	ID          uuid.UUID          `json:"id"`
	ReporterID  pgtype.UUID        `json:"reporter_id"`
	SubjectType string             `json:"subject_type"`
	SubjectID   uuid.UUID          `json:"subject_id"`
	Reason      ReportReason       `json:"reason"`
	Details     string             `json:"details"`
	Status      ReportStatus       `json:"status"`
	AssignedTo  pgtype.UUID        `json:"assigned_to"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
}

type Review struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	WorkID      uuid.UUID          `json:"work_id"`
	EditionID   pgtype.UUID        `json:"edition_id"`
	Rating      int32              `json:"rating"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	HasSpoilers bool               `json:"has_spoilers"`
	PromptWhy   string             `json:"prompt_why"`
	LikeCount   int32              `json:"like_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ReviewComment struct {
	ID        uuid.UUID          `json:"id"`
	ReviewID  uuid.UUID          `json:"review_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type ReviewLike struct {
	ReviewID  uuid.UUID          `json:"review_id"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ScholarNote struct {
	ID          uuid.UUID          `json:"id"`
	WorkID      uuid.UUID          `json:"work_id"`
	AuthorID    uuid.UUID          `json:"author_id"`
	ChapterRef  string             `json:"chapter_ref"`
	AnchorQuote string             `json:"anchor_quote"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Kind        string             `json:"kind"`
	Status      NoteStatus         `json:"status"`
	IsCommunity bool               `json:"is_community"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ScholarProfile struct {
	UserID       uuid.UUID          `json:"user_id"`
	Field        string             `json:"field"`
	Affiliation  *string            `json:"affiliation"`
	Orcid        *string            `json:"orcid"`
	Status       ScholarStatus      `json:"status"`
	VerifiedBy   pgtype.UUID        `json:"verified_by"`
	VerifiedAt   pgtype.Timestamptz `json:"verified_at"`
	CoiStatement string             `json:"coi_statement"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	UserAgent *string            `json:"user_agent"`
	IpHash    []byte             `json:"ip_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Shelf struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Kind      ShelfKind          `json:"kind"`
	Name      string             `json:"name"`
	IsPrivate bool               `json:"is_private"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ShelfItem struct {
	ID           uuid.UUID          `json:"id"`
	ShelfID      uuid.UUID          `json:"shelf_id"`
	WorkID       uuid.UUID          `json:"work_id"`
	EditionID    pgtype.UUID        `json:"edition_id"`
	Format       NullReadFormat     `json:"format"`
	AddedAt      pgtype.Timestamptz `json:"added_at"`
	Rating       *int32             `json:"rating"`
	ImportedFrom *string            `json:"imported_from"`
}

type Subject struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
	Kind string    `json:"kind"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	EmailVerified  bool               `json:"email_verified"`
	PasswordHash   *string            `json:"password_hash"`
	Role           UserRole           `json:"role"`
	Reputation     int32              `json:"reputation"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	SuspendedUntil pgtype.Timestamptz `json:"suspended_until"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
}

type UserBlock struct {
	BlockerID uuid.UUID          `json:"blocker_id"`
	BlockedID uuid.UUID          `json:"blocked_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WebauthnCredential struct {
	ID                []byte             `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	PublicKey         []byte             `json:"public_key"`
	AttestationAaguid pgtype.UUID        `json:"attestation_aaguid"`
	SignCount         int64              `json:"sign_count"`
	Transports        []string           `json:"transports"`
	Nickname          string             `json:"nickname"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	Flags             []byte             `json:"flags"`
	CloneDetected     bool               `json:"clone_detected"`
}

type Work struct {
	ID               uuid.UUID          `json:"id"`
	Slug             string             `json:"slug"`
	Title            string             `json:"title"`
	Subtitle         *string            `json:"subtitle"`
	OriginalLanguage string             `json:"original_language"`
	FirstPublished   *int32             `json:"first_published"`
	Description      string             `json:"description"`
	IsPublicDomain   bool               `json:"is_public_domain"`
	OpenlibraryID    *string            `json:"openlibrary_id"`
	RatingSum        int64              `json:"rating_sum"`
	RatingCount      int64              `json:"rating_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type WorkAuthor struct {
	WorkID   uuid.UUID `json:"work_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Role     string    `json:"role"`
	Position int32     `json:"position"`
}

type WorkSubject struct {
	WorkID    uuid.UUID `json:"work_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}
