// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: moderation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adjustReputation = `-- name: AdjustReputation :execrows
UPDATE users SET reputation = GREATEST(0, reputation + $1) WHERE id = $2
`

type AdjustReputationParams struct {
	Delta  int32     `json:"delta"`
	UserID uuid.UUID `json:"user_id"`
}

// Reputation gates posting limits. It moves only through explicit, recorded
// events (a moderator action, a published scholar note, a sustained history of
// un-reported reviews) — never from likes or follower counts, which are the
// gamification vectors Alexandria refuses to build.
func (q *Queries) AdjustReputation(ctx context.Context, arg AdjustReputationParams) (int64, error) {
	result, err := q.db.Exec(ctx, adjustReputation, arg.Delta, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const assignReport = `-- name: AssignReport :execrows
UPDATE reports SET assigned_to = $1, status = 'in_review'
 WHERE id = $2 AND status IN ('open', 'in_review')
`

type AssignReportParams struct {
	ModeratorID pgtype.UUID `json:"moderator_id"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) AssignReport(ctx context.Context, arg AssignReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignReport, arg.ModeratorID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countReportsAgainstSubject = `-- name: CountReportsAgainstSubject :one
SELECT count(*) FROM reports
 WHERE subject_type = $1 AND subject_id = $2
   AND status IN ('open', 'in_review')
`

type CountReportsAgainstSubjectParams struct {
	SubjectType string    `json:"subject_type"`
	SubjectID   uuid.UUID `json:"subject_id"`
}

func (q *Queries) CountReportsAgainstSubject(ctx context.Context, arg CountReportsAgainstSubjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsAgainstSubject, arg.SubjectType, arg.SubjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one

INSERT INTO reports (reporter_id, subject_type, subject_id, reason, details)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, reporter_id, subject_type, subject_id, reason, details, status, assigned_to, created_at, resolved_at
`

type CreateReportParams struct {
	ReporterID  pgtype.UUID  `json:"reporter_id"`
	SubjectType string       `json:"subject_type"`
	SubjectID   uuid.UUID    `json:"subject_id"`
	Reason      ReportReason `json:"reason"`
	Details     string       `json:"details"`
}

// Moderation, trust, and account lifecycle enforcement.
//
// Human-first by construction: every action row requires a written rationale
// (CHECK constraint in migration 0008), reports are routed to a queue rather
// than auto-resolved, and there is no automated content classifier anywhere in
// this file.
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Reason,
		arg.Details,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const deleteStaleAuthChallenges = `-- name: DeleteStaleAuthChallenges :execrows
DELETE FROM auth_challenges WHERE expires_at < $1
`

func (q *Queries) DeleteStaleAuthChallenges(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleAuthChallenges, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleContributions = `-- name: DeleteStaleContributions :execrows
DELETE FROM contribution_ledger WHERE created_at < $1
`

// The ledger only ever needs its trailing window for cap checks; pruning keeps
// the index tight without losing auditability (reviews themselves remain).
func (q *Queries) DeleteStaleContributions(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleContributions, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMessage = `-- name: GetMessage :one
SELECT id, channel_id, user_id, body, reply_to, has_spoilers, created_at, edited_at, deleted_at FROM messages WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.Body,
		&i.ReplyTo,
		&i.HasSpoilers,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, reporter_id, subject_type, subject_id, reason, details, status, assigned_to, created_at, resolved_at FROM reports WHERE id = $1
`

func (q *Queries) GetReport(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReport, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const liftSuspension = `-- name: LiftSuspension :execrows
UPDATE users SET suspended_until = NULL WHERE id = $1
`

func (q *Queries) LiftSuspension(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, liftSuspension, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveSuspensions = `-- name: ListActiveSuspensions :many
SELECT id, username, suspended_until FROM users
 WHERE suspended_until IS NOT NULL AND suspended_until > now() AND deleted_at IS NULL
`

type ListActiveSuspensionsRow struct {
	ID             uuid.UUID          `json:"id"`
	Username       string             `json:"username"`
	SuspendedUntil pgtype.Timestamptz `json:"suspended_until"`
}

func (q *Queries) ListActiveSuspensions(ctx context.Context) ([]ListActiveSuspensionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSuspensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSuspensionsRow{}
	for rows.Next() {
		var i ListActiveSuspensionsRow
		if err := rows.Scan(&i.ID, &i.Username, &i.SuspendedUntil); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModerationActionsForUser = `-- name: ListModerationActionsForUser :many
SELECT ma.id, ma.moderator_id, ma.target_user, ma.report_id, ma.kind, ma.rationale, ma.expires_at, ma.created_at, u.username AS moderator_username
  FROM moderation_actions ma
  LEFT JOIN users u ON u.id = ma.moderator_id
 WHERE ma.target_user = $1
 ORDER BY ma.created_at DESC
 LIMIT $2
`

type ListModerationActionsForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Lim    int32       `json:"lim"`
}

type ListModerationActionsForUserRow struct {
	ID                uuid.UUID            `json:"id"`
	ModeratorID       pgtype.UUID          `json:"moderator_id"`
	TargetUser        pgtype.UUID          `json:"target_user"`
	ReportID          pgtype.UUID          `json:"report_id"`
	Kind              ModerationActionKind `json:"kind"`
	Rationale         string               `json:"rationale"`
	ExpiresAt         pgtype.Timestamptz   `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz   `json:"created_at"`
	ModeratorUsername *string              `json:"moderator_username"`
}

func (q *Queries) ListModerationActionsForUser(ctx context.Context, arg ListModerationActionsForUserParams) ([]ListModerationActionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listModerationActionsForUser, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModerationActionsForUserRow{}
	for rows.Next() {
		var i ListModerationActionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ModeratorID,
			&i.TargetUser,
			&i.ReportID,
			&i.Kind,
			&i.Rationale,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModeratorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenReports = `-- name: ListOpenReports :many
SELECT r.id, r.reporter_id, r.subject_type, r.subject_id, r.reason, r.details, r.status, r.assigned_to, r.created_at, r.resolved_at, u.username AS reporter_username,
       m.username AS assigned_username
  FROM reports r
  LEFT JOIN users u ON u.id = r.reporter_id
  LEFT JOIN users m ON m.id = r.assigned_to
 -- pgx cannot encode a slice of a custom enum; compare as text instead.
 WHERE r.status::text = ANY($1::text[])
 ORDER BY
   CASE r.reason
     WHEN 'threat' THEN 0 WHEN 'hate' THEN 1 WHEN 'harassment' THEN 2
     WHEN 'sexual_content' THEN 3 WHEN 'copyright' THEN 4 ELSE 5
   END,
   r.created_at ASC
 LIMIT $3 OFFSET $2
`

type ListOpenReportsParams struct {
	Statuses []string `json:"statuses"`
	Off      int32    `json:"off"`
	Lim      int32    `json:"lim"`
}

type ListOpenReportsRow struct {
	ID               uuid.UUID          `json:"id"`
	ReporterID       pgtype.UUID        `json:"reporter_id"`
	SubjectType      string             `json:"subject_type"`
	SubjectID        uuid.UUID          `json:"subject_id"`
	Reason           ReportReason       `json:"reason"`
	Details          string             `json:"details"`
	Status           ReportStatus       `json:"status"`
	AssignedTo       pgtype.UUID        `json:"assigned_to"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	ReporterUsername *string            `json:"reporter_username"`
	AssignedUsername *string            `json:"assigned_username"`
}

func (q *Queries) ListOpenReports(ctx context.Context, arg ListOpenReportsParams) ([]ListOpenReportsRow, error) {
	rows, err := q.db.Query(ctx, listOpenReports, arg.Statuses, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenReportsRow{}
	for rows.Next() {
		var i ListOpenReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Reason,
			&i.Details,
			&i.Status,
			&i.AssignedTo,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ReporterUsername,
			&i.AssignedUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrustedReaders = `-- name: ListTrustedReaders :many
SELECT id, username, reputation FROM users
 WHERE reputation >= $1 AND deleted_at IS NULL
 ORDER BY reputation DESC
 LIMIT $2
`

type ListTrustedReadersParams struct {
	Threshold int32 `json:"threshold"`
	Lim       int32 `json:"lim"`
}

type ListTrustedReadersRow struct {
	ID         uuid.UUID `json:"id"`
	Username   string    `json:"username"`
	Reputation int32     `json:"reputation"`
}

func (q *Queries) ListTrustedReaders(ctx context.Context, arg ListTrustedReadersParams) ([]ListTrustedReadersRow, error) {
	rows, err := q.db.Query(ctx, listTrustedReaders, arg.Threshold, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrustedReadersRow{}
	for rows.Next() {
		var i ListTrustedReadersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Reputation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordModerationAction = `-- name: RecordModerationAction :one
INSERT INTO moderation_actions (moderator_id, target_user, report_id, kind, rationale, expires_at)
VALUES ($1, $2, $3, $4, $5,
        $6)
RETURNING id, moderator_id, target_user, report_id, kind, rationale, expires_at, created_at
`

type RecordModerationActionParams struct {
	ModeratorID pgtype.UUID          `json:"moderator_id"`
	TargetUser  pgtype.UUID          `json:"target_user"`
	ReportID    pgtype.UUID          `json:"report_id"`
	Kind        ModerationActionKind `json:"kind"`
	Rationale   string               `json:"rationale"`
	ExpiresAt   pgtype.Timestamptz   `json:"expires_at"`
}

func (q *Queries) RecordModerationAction(ctx context.Context, arg RecordModerationActionParams) (ModerationAction, error) {
	row := q.db.QueryRow(ctx, recordModerationAction,
		arg.ModeratorID,
		arg.TargetUser,
		arg.ReportID,
		arg.Kind,
		arg.Rationale,
		arg.ExpiresAt,
	)
	var i ModerationAction
	err := row.Scan(
		&i.ID,
		&i.ModeratorID,
		&i.TargetUser,
		&i.ReportID,
		&i.Kind,
		&i.Rationale,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const resolveReport = `-- name: ResolveReport :execrows
UPDATE reports SET status = $1, resolved_at = now()
 WHERE id = $2 AND status <> 'actioned'
`

type ResolveReportParams struct {
	Status ReportStatus `json:"status"`
	ID     uuid.UUID    `json:"id"`
}

func (q *Queries) ResolveReport(ctx context.Context, arg ResolveReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveReport, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suspendUser = `-- name: SuspendUser :execrows
UPDATE users SET suspended_until = $1 WHERE id = $2
`

type SuspendUserParams struct {
	Until  pgtype.Timestamptz `json:"until"`
	UserID uuid.UUID          `json:"user_id"`
}

func (q *Queries) SuspendUser(ctx context.Context, arg SuspendUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, suspendUser, arg.Until, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
