// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: push.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPushSubscription = `-- name: AddPushSubscription :one
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth, user_agent)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, endpoint) DO UPDATE SET
  p256dh = EXCLUDED.p256dh,
  auth   = EXCLUDED.auth
RETURNING id, user_id, endpoint, p256dh, auth, user_agent, created_at, last_pushed_at
`

type AddPushSubscriptionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Endpoint  string    `json:"endpoint"`
	P256dh    []byte    `json:"p256dh"`
	Auth      []byte    `json:"auth"`
	UserAgent *string   `json:"user_agent"`
}

func (q *Queries) AddPushSubscription(ctx context.Context, arg AddPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, addPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserAgent,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastPushedAt,
	)
	return i, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM push_subscriptions WHERE user_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Endpoint string    `json:"endpoint"`
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscription, arg.UserID, arg.Endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotificationsSince = `-- name: ListNotificationsSince :many
SELECT id, user_id, kind, payload, read_at, created_at FROM notifications
 WHERE user_id = $1 AND created_at > $2
 ORDER BY created_at DESC
 LIMIT $3
`

type ListNotificationsSinceParams struct {
	UserID uuid.UUID          `json:"user_id"`
	Since  pgtype.Timestamptz `json:"since"`
	Lim    int32              `json:"lim"`
}

func (q *Queries) ListNotificationsSince(ctx context.Context, arg ListNotificationsSinceParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsSince, arg.UserID, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushDue = `-- name: ListPushDue :many
SELECT s.id, s.user_id, s.endpoint, s.p256dh, s.auth, s.user_agent, s.created_at, s.last_pushed_at FROM push_subscriptions s
 WHERE EXISTS (
   SELECT 1 FROM notifications n
    WHERE n.user_id = s.user_id
      AND n.created_at > coalesce(s.last_pushed_at, 'epoch'::timestamptz))
 ORDER BY s.created_at
 LIMIT $1
`

// Subscriptions with anything notified since their last push. 'epoch' as the
// floor means a fresh subscription is due immediately, which is what a
// reader expects when they flip the switch.
func (q *Queries) ListPushDue(ctx context.Context, lim int32) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushDue, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastPushedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptionsForUser = `-- name: ListPushSubscriptionsForUser :many
SELECT id, user_id, endpoint, p256dh, auth, user_agent, created_at, last_pushed_at FROM push_subscriptions WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPushSubscriptionsForUser(ctx context.Context, userID uuid.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastPushedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPushed = `-- name: MarkPushed :execrows
UPDATE push_subscriptions SET last_pushed_at = $1 WHERE id = $2
`

type MarkPushedParams struct {
	PushedAt pgtype.Timestamptz `json:"pushed_at"`
	ID       uuid.UUID          `json:"id"`
}

func (q *Queries) MarkPushed(ctx context.Context, arg MarkPushedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPushed, arg.PushedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
