// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddNoteCitation(ctx context.Context, arg AddNoteCitationParams) error
	AddToShelf(ctx context.Context, arg AddToShelfParams) (ShelfItem, error)
	// Reputation gates posting limits. It moves only through explicit, recorded
	// events (a moderator action, a published scholar note, a sustained history of
	// un-reported reviews) — never from likes or follower counts, which are the
	// gamification vectors Alexandria refuses to build.
	AdjustReputation(ctx context.Context, arg AdjustReputationParams) (int64, error)
	AssignReport(ctx context.Context, arg AssignReportParams) (int64, error)
	AuthorSearchDocuments(ctx context.Context, arg AuthorSearchDocumentsParams) ([]AuthorSearchDocumentsRow, error)
	BlockUser(ctx context.Context, arg BlockUserParams) (int64, error)
	// The authorization question the message and channel endpoints must ask before
	// returning content: has this reader passed the channel's spoiler threshold?
	ChannelIsSpoilerGatedFor(ctx context.Context, arg ChannelIsSpoilerGatedForParams) (ChannelIsSpoilerGatedForRow, error)
	// Indie authors claim an author record; claims are audited, never paid.
	ClaimAuthorProfile(ctx context.Context, arg ClaimAuthorProfileParams) (int64, error)
	// Atomic claim: two workers cannot take the same job, and a job stuck in
	// `running` past its lease is reclaimable.
	ClaimIngestJob(ctx context.Context, leaseExpiredBefore pgtype.Timestamptz) (IngestJob, error)
	ClearCurrentClubRead(ctx context.Context, clubID uuid.UUID) (int64, error)
	ClearPrimaryCover(ctx context.Context, editionID uuid.UUID) error
	ClubSearchDocuments(ctx context.Context, arg ClubSearchDocumentsParams) ([]ClubSearchDocumentsRow, error)
	// Single-use by construction: the `consumed_at IS NULL` predicate makes a
	// concurrent replay lose the race and return zero rows.
	ConsumeAuthChallenge(ctx context.Context, arg ConsumeAuthChallengeParams) (AuthChallenge, error)
	CountAuthAttemptsSince(ctx context.Context, arg CountAuthAttemptsSinceParams) (int64, error)
	// Posting caps are computed by counting ledger rows in a trailing window:
	// cheap, transparent, and impossible to game without actually posting.
	CountContributionsSince(ctx context.Context, arg CountContributionsSinceParams) (int64, error)
	CountFollows(ctx context.Context, userID uuid.UUID) (CountFollowsRow, error)
	CountGutenbergTexts(ctx context.Context) (int64, error)
	// Distinct verified scholars, excluding the author: the peer-review gate.
	CountNoteApprovals(ctx context.Context, arg CountNoteApprovalsParams) (int64, error)
	CountNoteCitations(ctx context.Context, noteID uuid.UUID) (int64, error)
	CountReportsAgainstSubject(ctx context.Context, arg CountReportsAgainstSubjectParams) (int64, error)
	CountReviewsForWork(ctx context.Context, workID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountWorks(ctx context.Context) (int64, error)
	// ---- Annotations ------------------------------------------------------------
	CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (Annotation, error)
	// ---- Auth ceremonies --------------------------------------------------------
	CreateAuthChallenge(ctx context.Context, arg CreateAuthChallengeParams) (AuthChallenge, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	// Book clubs: memberships, roles, channels, messages, and spoiler gating.
	//
	// Spoiler gating is data, not UI: a channel carries spoiler_threshold_bp, and
	// the read path joins the member's progress on the club's current work so the
	// API can refuse to return content the reader has not reached yet. Hiding
	// spoilers only in the client would leak them through the network response.
	CreateClub(ctx context.Context, arg CreateClubParams) (Club, error)
	CreateCustomShelf(ctx context.Context, arg CreateCustomShelfParams) (Shelf, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// ---- Notifications ----------------------------------------------------------
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// Moderation, trust, and account lifecycle enforcement.
	//
	// Human-first by construction: every action row requires a written rationale
	// (CHECK constraint in migration 0008), reports are routed to a queue rather
	// than auto-resolved, and there is no automated content classifier anywhere in
	// this file.
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	// Reviews, likes, and comments — the human-written core of Alexandria.
	//
	// The rating aggregate (works.rating_sum / rating_count) is maintained by the
	// apply_review_rating() trigger from migration 0005, so no query here recomputes
	// it and none can drift from it.
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	// ---- Comments ---------------------------------------------------------------
	CreateReviewComment(ctx context.Context, arg CreateReviewCommentParams) (ReviewComment, error)
	CreateScholarNote(ctx context.Context, arg CreateScholarNoteParams) (ScholarNote, error)
	// ---- Sessions ---------------------------------------------------------------
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Identity, authentication ceremonies, and sessions.
	//
	// Conventions used throughout packages/db/queries:
	//   * time windows are passed as timestamptz boundaries computed in Go
	//     (`created_at > @since`), never as interval strings. That keeps the
	//     predicate sargable and avoids coupling SQL to Go's duration formatting.
	//   * every destructive ceremony is a single atomic conditional UPDATE, so
	//     "single use" cannot be violated by two concurrent requests.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CredentialIDExists(ctx context.Context, id []byte) (bool, error)
	DeleteAnnotation(ctx context.Context, arg DeleteAnnotationParams) (int64, error)
	// System shelves are permanent (the library's shape depends on them); only
	// custom shelves can be removed. Items cascade with the shelf.
	DeleteCustomShelf(ctx context.Context, arg DeleteCustomShelfParams) (int64, error)
	DeleteExpiredChallenges(ctx context.Context, now pgtype.Timestamptz) (int64, error)
	DeleteNoteCitation(ctx context.Context, arg DeleteNoteCitationParams) (int64, error)
	DeleteStaleAuthChallenges(ctx context.Context, now pgtype.Timestamptz) (int64, error)
	// The ledger only ever needs its trailing window for cap checks; pruning keeps
	// the index tight without losing auditability (reviews themselves remain).
	DeleteStaleContributions(ctx context.Context, before pgtype.Timestamptz) (int64, error)
	// Sessions revoked or expired more than @since are garbage; removing them keeps
	// the lookup index small without ever touching a live session.
	DeleteStaleSessions(ctx context.Context, since pgtype.Timestamptz) (int64, error)
	DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) (int64, error)
	EmailIsTaken(ctx context.Context, email string) (bool, error)
	// ---- Ingestion job bookkeeping ---------------------------------------------
	EnqueueIngestJob(ctx context.Context, arg EnqueueIngestJobParams) (IngestJob, error)
	// Personal library: shelves, shelf items, reading sessions, annotations.
	//
	// Every query here runs under Row-Level Security (migration 0011) AND filters
	// on user_id explicitly. That duplication is intentional: RLS is the last line
	// of defense, and an explicit predicate keeps the plan index-driven and the
	// intent readable in review.
	// Called once at registration. Idempotent, so it is safe to retry.
	EnsureSystemShelves(ctx context.Context, userID uuid.UUID) error
	ExtendSession(ctx context.Context, arg ExtendSessionParams) (int64, error)
	FetchPendingEmails(ctx context.Context, arg FetchPendingEmailsParams) ([]EmailOutbox, error)
	// Login resolves the account from the asserted credential, because a passkey
	// ceremony begins before we know who is signing in.
	FindUserByCredentialID(ctx context.Context, credentialID []byte) (User, error)
	FinishIngestJob(ctx context.Context, arg FinishIngestJobParams) (int64, error)
	FinishSession(ctx context.Context, arg FinishSessionParams) (int64, error)
	// Social graph and the chronological feed.
	//
	// The feed is a UNION over activity types ordered by time. There is no score
	// column, no engagement weighting, and no ranking function — that absence is
	// the product decision. "Community Picks" elsewhere is collaborative filtering
	// over co-occurrence (readers of X also read Y), which is computed in the
	// worker and stored, never blended into this stream.
	FollowUser(ctx context.Context, arg FollowUserParams) (int64, error)
	// The single query behind session middleware. Suspension and soft-deletion are
	// resolved here so no handler can forget to check them.
	GetActiveSession(ctx context.Context, tokenHash []byte) (GetActiveSessionRow, error)
	GetAuthorByID(ctx context.Context, id uuid.UUID) (Author, error)
	// Dedup key for authors that arrive without a stable external identifier
	// (Gutenberg catalog names, indie authors). Exact match, case-insensitive.
	GetAuthorByName(ctx context.Context, name string) (Author, error)
	GetAuthorBySlug(ctx context.Context, slug string) (Author, error)
	GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error)
	GetClubByID(ctx context.Context, id uuid.UUID) (Club, error)
	GetClubBySlug(ctx context.Context, slug string) (GetClubBySlugRow, error)
	GetClubMembership(ctx context.Context, arg GetClubMembershipParams) (ClubMembership, error)
	GetCurrentClubRead(ctx context.Context, clubID uuid.UUID) (GetCurrentClubReadRow, error)
	GetEditionByGutenbergID(ctx context.Context, gutenbergID *int32) (Edition, error)
	GetEditionByID(ctx context.Context, id uuid.UUID) (GetEditionByIDRow, error)
	GetGutenbergText(ctx context.Context, gutenbergID int32) (GutenbergText, error)
	// What the book page needs to render the caller's own state.
	GetLibraryEntry(ctx context.Context, arg GetLibraryEntryParams) (GetLibraryEntryRow, error)
	GetOpenSession(ctx context.Context, arg GetOpenSessionParams) (ReadingSession, error)
	GetPrimaryCoverForEdition(ctx context.Context, editionID uuid.UUID) (CoverAsset, error)
	GetProfileByUserID(ctx context.Context, userID uuid.UUID) (Profile, error)
	// The public projection: never exposes email, reputation internals, or a
	// private account's details beyond what the profile page needs.
	GetPublicProfileByUsername(ctx context.Context, username string) (GetPublicProfileByUsernameRow, error)
	GetReport(ctx context.Context, id uuid.UUID) (Report, error)
	GetReviewByID(ctx context.Context, id uuid.UUID) (GetReviewByIDRow, error)
	GetReviewByUserAndWork(ctx context.Context, arg GetReviewByUserAndWorkParams) (Review, error)
	GetReviewComment(ctx context.Context, id uuid.UUID) (ReviewComment, error)
	GetScholarNote(ctx context.Context, id uuid.UUID) (GetScholarNoteRow, error)
	GetScholarProfile(ctx context.Context, userID uuid.UUID) (ScholarProfile, error)
	GetShelfByID(ctx context.Context, arg GetShelfByIDParams) (Shelf, error)
	GetShelfItem(ctx context.Context, id uuid.UUID) (ShelfItem, error)
	GetSystemShelf(ctx context.Context, arg GetSystemShelfParams) (Shelf, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWebAuthnCredential(ctx context.Context, id []byte) (WebauthnCredential, error)
	GetWorkByID(ctx context.Context, id uuid.UUID) (Work, error)
	GetWorkByOpenLibraryID(ctx context.Context, openlibraryID *string) (Work, error)
	// Bibliography: the FRBR core (Work → Edition) plus authors and subjects.
	//
	// Duplicate books are the failure mode that kills every community-maintained
	// catalogue, so every write path here is an idempotent upsert keyed on a
	// stable external identifier, never on a title string.
	GetWorkBySlug(ctx context.Context, slug string) (Work, error)
	HasUserLikedReview(ctx context.Context, arg HasUserLikedReviewParams) (bool, error)
	IngestJobStats(ctx context.Context) (IngestJobStatsRow, error)
	// ---- Covers (rights-aware) --------------------------------------------------
	InsertCoverAsset(ctx context.Context, arg InsertCoverAssetParams) (CoverAsset, error)
	// ---- WebAuthn credentials ---------------------------------------------------
	InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) error
	// For works with no external identifier yet (indie authors, Gutenberg texts
	// whose Open Library work record is missing). Slug uniqueness is enforced by
	// the schema; callers resolve collisions before inserting.
	InsertWork(ctx context.Context, arg InsertWorkParams) (Work, error)
	// Checked in BOTH directions: a block is not an invitation to be replied to.
	IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error)
	IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error)
	IsVerifiedScholar(ctx context.Context, userID uuid.UUID) (bool, error)
	JoinClub(ctx context.Context, arg JoinClubParams) (ClubMembership, error)
	LeaveClub(ctx context.Context, arg LeaveClubParams) (int64, error)
	LibraryCountsForUser(ctx context.Context, userID uuid.UUID) ([]LibraryCountsForUserRow, error)
	LiftSuspension(ctx context.Context, userID uuid.UUID) (int64, error)
	// ---- Likes ------------------------------------------------------------------
	LikeReview(ctx context.Context, arg LikeReviewParams) (int64, error)
	LinkGutenbergEdition(ctx context.Context, arg LinkGutenbergEditionParams) (int64, error)
	LinkWorkAuthor(ctx context.Context, arg LinkWorkAuthorParams) error
	LinkWorkSubject(ctx context.Context, arg LinkWorkSubjectParams) error
	ListActiveSuspensions(ctx context.Context) ([]ListActiveSuspensionsRow, error)
	// Distinct days on which the reader touched a session, note, or review.
	// The streak is computed in Go so the rule ("consecutive, today or yesterday
	// anchored") lives in one testable place instead of in SQL date arithmetic.
	ListActivityDays(ctx context.Context, arg ListActivityDaysParams) ([]pgtype.Date, error)
	ListAnnotationsForEdition(ctx context.Context, arg ListAnnotationsForEditionParams) ([]Annotation, error)
	// The reader's margin notes across every edition, for the Notes page.
	// RLS-scoped like all annotation reads: only the caller's rows can appear.
	ListAnnotationsForUser(ctx context.Context, arg ListAnnotationsForUserParams) ([]ListAnnotationsForUserRow, error)
	ListAuthorsForWork(ctx context.Context, workID uuid.UUID) ([]ListAuthorsForWorkRow, error)
	ListBlockedUsers(ctx context.Context, userID uuid.UUID) ([]ListBlockedUsersRow, error)
	ListChannelsForClub(ctx context.Context, arg ListChannelsForClubParams) ([]ListChannelsForClubRow, error)
	ListClubMemberships(ctx context.Context, arg ListClubMembershipsParams) ([]ListClubMembershipsRow, error)
	ListClubs(ctx context.Context, arg ListClubsParams) ([]ListClubsRow, error)
	ListClubsForUser(ctx context.Context, userID uuid.UUID) ([]ListClubsForUserRow, error)
	// "Readers of this also read", computed from shared shelves. Collaborative
	// filtering over co-occurrence, not engagement: a book ranks here because
	// people who shelved X also shelved Y, weighted by how selective Y is
	// (inverse popularity), which is what keeps blockbusters from swallowing every
	// recommendation slot.
	ListCoOccurringWorks(ctx context.Context, arg ListCoOccurringWorksParams) ([]ListCoOccurringWorksRow, error)
	ListCommentsForReview(ctx context.Context, arg ListCommentsForReviewParams) ([]ListCommentsForReviewRow, error)
	ListCoversForWork(ctx context.Context, workID uuid.UUID) ([]ListCoversForWorkRow, error)
	// "Continue reading" on the home page: open sessions, most recently touched
	// first. Chronological by activity — never by engagement.
	ListCurrentlyReading(ctx context.Context, arg ListCurrentlyReadingParams) ([]ListCurrentlyReadingRow, error)
	// ---- Editions ---------------------------------------------------------------
	ListEditionsForWork(ctx context.Context, workID uuid.UUID) ([]ListEditionsForWorkRow, error)
	ListExternalIdentifiers(ctx context.Context, editionID uuid.UUID) ([]ExternalIdentifier, error)
	ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error)
	ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error)
	// ---- Feed -------------------------------------------------------------------
	// Chronological activity from accounts the reader follows. Blocked accounts are
	// excluded in both directions; private shelves never appear.
	ListFollowingFeed(ctx context.Context, arg ListFollowingFeedParams) ([]ListFollowingFeedRow, error)
	ListGutenbergTexts(ctx context.Context, arg ListGutenbergTextsParams) ([]ListGutenbergTextsRow, error)
	ListIndexedWorkIDs(ctx context.Context, arg ListIndexedWorkIDsParams) ([]uuid.UUID, error)
	ListIngestJobsByStatus(ctx context.Context, arg ListIngestJobsByStatusParams) ([]IngestJob, error)
	ListLikedReviewIDsForUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	// Keyset pagination on (created_at, id): chat history is unbounded and OFFSET
	// would get slower the deeper a reader scrolls.
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error)
	ListModerationActionsForUser(ctx context.Context, arg ListModerationActionsForUserParams) ([]ListModerationActionsForUserRow, error)
	ListNoteCitations(ctx context.Context, noteID uuid.UUID) ([]NoteCitation, error)
	ListNoteReviews(ctx context.Context, noteID uuid.UUID) ([]ListNoteReviewsRow, error)
	ListNoteRevisions(ctx context.Context, noteID uuid.UUID) ([]NoteRevision, error)
	ListNotesAwaitingReview(ctx context.Context, arg ListNotesAwaitingReviewParams) ([]ListNotesAwaitingReviewRow, error)
	// Readers see published notes, plus their own drafts so an author can resume
	// editing. Community-contributor notes are returned with is_community set, and
	// the UI labels them differently from verified-scholar notes — no elitism, but
	// no false equivalence either.
	ListNotesForWork(ctx context.Context, arg ListNotesForWorkParams) ([]ListNotesForWorkRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListOpenReports(ctx context.Context, arg ListOpenReportsParams) ([]ListOpenReportsRow, error)
	ListPendingScholarProfiles(ctx context.Context, arg ListPendingScholarProfilesParams) ([]ListPendingScholarProfilesRow, error)
	ListPopularSubjects(ctx context.Context, lim int32) ([]ListPopularSubjectsRow, error)
	ListReadingSessions(ctx context.Context, arg ListReadingSessionsParams) ([]ReadingSession, error)
	// The logged-out / empty-following home page: newest substantive reviews
	// platform-wide. Reverse-chronological, capped, and it never pretends to be
	// personalized.
	ListRecentReviewsAcrossCommunity(ctx context.Context, arg ListRecentReviewsAcrossCommunityParams) ([]ListRecentReviewsAcrossCommunityRow, error)
	ListReviewsByUser(ctx context.Context, arg ListReviewsByUserParams) ([]ListReviewsByUserRow, error)
	ListReviewsForWork(ctx context.Context, arg ListReviewsForWorkParams) ([]ListReviewsForWorkRow, error)
	ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]ListSessionsForUserRow, error)
	// The library view. One row per shelved work, with the most recent reading
	// session joined laterally so rereads never multiply rows.
	ListShelfItemsWithWork(ctx context.Context, arg ListShelfItemsWithWorkParams) ([]ListShelfItemsWithWorkRow, error)
	ListShelvesForUser(ctx context.Context, userID uuid.UUID) ([]ListShelvesForUserRow, error)
	ListSubjectsForWork(ctx context.Context, workID uuid.UUID) ([]Subject, error)
	ListTrustedReaders(ctx context.Context, arg ListTrustedReadersParams) ([]ListTrustedReadersRow, error)
	ListWebAuthnCredentialsForUser(ctx context.Context, userID uuid.UUID) ([]WebauthnCredential, error)
	// Paging cursor for a full Meilisearch reindex: keyset pagination on id, which
	// stays O(log n) where OFFSET would degrade badly on a large catalogue.
	ListWorkIDsForIndex(ctx context.Context, arg ListWorkIDsForIndexParams) ([]uuid.UUID, error)
	// The catalogue listing. Every filter is optional and expressed as a
	// NULL-or-match predicate so sqlc generates one plan and the caller never
	// builds SQL strings.
	//
	// Ordering is explicit and non-algorithmic: `rating` is a Bayesian-weighted
	// average (never a raw mean, which puts a single 5★ above 400 4.8★ ratings),
	// `recent` is publication year, `added` is ingest order. There is no
	// engagement-weighted sort, by design.
	ListWorks(ctx context.Context, arg ListWorksParams) ([]ListWorksRow, error)
	ListWorksBySubject(ctx context.Context, arg ListWorksBySubjectParams) ([]Work, error)
	ListWorksForAuthor(ctx context.Context, arg ListWorksForAuthorParams) ([]ListWorksForAuthorRow, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error)
	MarkEmailFailed(ctx context.Context, arg MarkEmailFailedParams) (int64, error)
	MarkEmailSent(ctx context.Context, id int64) (int64, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	MarkSessionDNF(ctx context.Context, arg MarkSessionDNFParams) (int64, error)
	// ---- Transactional outbox ---------------------------------------------------
	OutboxAppend(ctx context.Context, arg OutboxAppendParams) error
	OutboxDelete(ctx context.Context, ids []int64) error
	OutboxDepth(ctx context.Context) (int64, error)
	OutboxPeek(ctx context.Context, lim int32) ([]Outbox, error)
	// ---- Transactional email outbox --------------------------------------------
	QueueEmail(ctx context.Context, arg QueueEmailParams) error
	// Powers the histogram on the book page. GROUP BY over the half-star scale so
	// the UI never has to bucket in application code.
	RatingDistributionForWork(ctx context.Context, workID uuid.UUID) ([]RatingDistributionForWorkRow, error)
	ReadingStatsForUser(ctx context.Context, userID uuid.UUID) (ReadingStatsForUserRow, error)
	RecordAuthAttempt(ctx context.Context, arg RecordAuthAttemptParams) error
	RecordContribution(ctx context.Context, arg RecordContributionParams) error
	RecordLogin(ctx context.Context, id uuid.UUID) error
	RecordModerationAction(ctx context.Context, arg RecordModerationActionParams) (ModerationAction, error)
	// Append-only history: every edit is recoverable, which is what makes
	// retracting or disputing a scholarly claim possible.
	RecordNoteRevision(ctx context.Context, arg RecordNoteRevisionParams) error
	RemoveFromShelf(ctx context.Context, arg RemoveFromShelfParams) (int64, error)
	// Moving a book between reading states must not leave it on two shelves at
	// once ("Currently Reading" and "Read" simultaneously is a data bug, not a
	// user preference). Favorites is exempt: it is orthogonal to reading state.
	RemoveWorkFromUserShelves(ctx context.Context, arg RemoveWorkFromUserShelvesParams) (int64, error)
	// The retry-at timestamp is computed by the caller so the backoff policy lives
	// in one testable place (internal/ingest) instead of in SQL arithmetic.
	RequeueIngestJob(ctx context.Context, arg RequeueIngestJobParams) (int64, error)
	ResolveReport(ctx context.Context, arg ResolveReportParams) (int64, error)
	ReviewNote(ctx context.Context, arg ReviewNoteParams) error
	RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) (int64, error)
	RevokeSessionByToken(ctx context.Context, tokenHash []byte) (int64, error)
	RevokeSessionsForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	SetClubMemberRole(ctx context.Context, arg SetClubMemberRoleParams) (int64, error)
	SetCurrentClubRead(ctx context.Context, arg SetCurrentClubReadParams) (ClubRead, error)
	SetEmailVerified(ctx context.Context, id uuid.UUID) error
	SetNoteStatus(ctx context.Context, arg SetNoteStatusParams) (int64, error)
	// The literal is cast explicitly: reusing @status in both an enum assignment
	// and a comparison leaves Postgres unable to deduce the parameter's type.
	SetScholarStatus(ctx context.Context, arg SetScholarStatusParams) (int64, error)
	SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (int64, error)
	SoftDeleteReview(ctx context.Context, arg SoftDeleteReviewParams) (int64, error)
	SoftDeleteReviewComment(ctx context.Context, arg SoftDeleteReviewCommentParams) (int64, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	// Closes any open session, then opens a fresh one: a reread is a new row, never
	// a mutation of history.
	StartReread(ctx context.Context, arg StartRereadParams) (ReadingSession, error)
	SuspendUser(ctx context.Context, arg SuspendUserParams) (int64, error)
	// Denormalized count refreshed on change; keeps list queries free of a
	// correlated aggregate over review_likes.
	SyncReviewLikeCount(ctx context.Context, reviewID uuid.UUID) error
	// DMCA path: immediate, auditable, and it removes the cached object reference
	// so the CDN can no longer serve it.
	TakedownCover(ctx context.Context, id uuid.UUID) (int64, error)
	UnblockUser(ctx context.Context, arg UnblockUserParams) (int64, error)
	UnfollowUser(ctx context.Context, arg UnfollowUserParams) (int64, error)
	UnlikeReview(ctx context.Context, arg UnlikeReviewParams) (int64, error)
	UpdateAnnotationBody(ctx context.Context, arg UpdateAnnotationBodyParams) (int64, error)
	UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error)
	UpdateScholarNote(ctx context.Context, arg UpdateScholarNoteParams) (ScholarNote, error)
	UpdateShelfPrivacy(ctx context.Context, arg UpdateShelfPrivacyParams) (int64, error)
	UpdateWebAuthnCredentialAfterAssertion(ctx context.Context, arg UpdateWebAuthnCredentialAfterAssertionParams) error
	// ---- Authors ----------------------------------------------------------------
	UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) (Author, error)
	UpsertEdition(ctx context.Context, arg UpsertEditionParams) (Edition, error)
	UpsertExternalIdentifier(ctx context.Context, arg UpsertExternalIdentifierParams) error
	// Gutenberg texts have no ISBN, so they need their own conflict target.
	// Reusing UpsertEdition here would insert a new row on every catalog refresh,
	// because a NULL isbn13 never conflicts.
	UpsertGutenbergEdition(ctx context.Context, arg UpsertGutenbergEditionParams) (Edition, error)
	// Project Gutenberg ingestion and public-domain text access.
	//
	// Compliance shape, mirrored in internal/ingest/gutenberg.go:
	//   * we consume Gutenberg's OFFICIAL offline catalog feeds, never the website
	//   * each text is downloaded once and cached to our own object storage; we do
	//     not hotlink or proxy gutenberg.org at read time
	//   * the Gutenberg trademark notice and license header are preserved in
	//     metadata, and the reading text is stripped of boilerplate separately
	//     (stored apart from the notice, so the notice is never lost)
	UpsertGutenbergText(ctx context.Context, arg UpsertGutenbergTextParams) (GutenbergText, error)
	UpsertProfile(ctx context.Context, arg UpsertProfileParams) (Profile, error)
	// ---- Reading sessions -------------------------------------------------------
	// Upserts the single open session for (user, work). Reaching 100% closes it and
	// stamps the finish date; the partial unique index guarantees one open session.
	UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) (ReadingSession, error)
	// Scholar system: verified contributors, peer-reviewed notes, citations.
	//
	// Two invariants the schema and these queries enforce together:
	//   1. a published note has at least one citation
	//   2. a note reaches `published` only after two approvals from distinct
	//      verified scholars, and never from its own author
	UpsertScholarProfile(ctx context.Context, arg UpsertScholarProfileParams) (ScholarProfile, error)
	// ---- Subjects ---------------------------------------------------------------
	UpsertSubject(ctx context.Context, arg UpsertSubjectParams) (Subject, error)
	UpsertWork(ctx context.Context, arg UpsertWorkParams) (Work, error)
	UsernameIsTaken(ctx context.Context, username string) (bool, error)
	// Search projections.
	//
	// Meilisearch is fed from Postgres, never written to directly by request
	// handlers: the database stays the source of truth and the index is a derived,
	// rebuildable projection. These queries shape exactly one index document each,
	// so reindexing is a pure function of the catalogue.
	//
	// Nested arrays are returned as JSON and unmarshalled in Go (internal/search),
	// which keeps sqlc's types honest instead of smuggling strings through SQL.
	WorkSearchDocuments(ctx context.Context, arg WorkSearchDocumentsParams) ([]WorkSearchDocumentsRow, error)
	WorkSlugIsTaken(ctx context.Context, slug string) (bool, error)
	// ---- reading-life projections (right rail) -----------------------------------
	// These exist so the UI never has to invent a number: every figure on the
	// reader's right rail is derived from their own sessions, annotations and
	// reviews, and shows zero when there is genuinely nothing yet.
	YearStatsForUser(ctx context.Context, arg YearStatsForUserParams) (YearStatsForUserRow, error)
}

var _ Querier = (*Queries)(nil)
