// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reviews.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countContributionsSince = `-- name: CountContributionsSince :one
SELECT count(*) FROM contribution_ledger
 WHERE user_id = $1 AND kind = $2 AND created_at > $3
`

type CountContributionsSinceParams struct {
	UserID uuid.UUID          `json:"user_id"`
	Kind   string             `json:"kind"`
	Since  pgtype.Timestamptz `json:"since"`
}

// Posting caps are computed by counting ledger rows in a trailing window:
// cheap, transparent, and impossible to game without actually posting.
func (q *Queries) CountContributionsSince(ctx context.Context, arg CountContributionsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContributionsSince, arg.UserID, arg.Kind, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsForWork = `-- name: CountReviewsForWork :one
SELECT count(*) FROM reviews WHERE work_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountReviewsForWork(ctx context.Context, workID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsForWork, workID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one

INSERT INTO reviews (user_id, work_id, edition_id, rating, title, body, has_spoilers, prompt_why)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8)
RETURNING id, user_id, work_id, edition_id, rating, title, body, has_spoilers, prompt_why, like_count, created_at, updated_at, deleted_at
`

type CreateReviewParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	WorkID      uuid.UUID   `json:"work_id"`
	EditionID   pgtype.UUID `json:"edition_id"`
	Rating      int32       `json:"rating"`
	Title       string      `json:"title"`
	Body        string      `json:"body"`
	HasSpoilers bool        `json:"has_spoilers"`
	PromptWhy   string      `json:"prompt_why"`
}

// Reviews, likes, and comments — the human-written core of Alexandria.
//
// The rating aggregate (works.rating_sum / rating_count) is maintained by the
// apply_review_rating() trigger from migration 0005, so no query here recomputes
// it and none can drift from it.
func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.UserID,
		arg.WorkID,
		arg.EditionID,
		arg.Rating,
		arg.Title,
		arg.Body,
		arg.HasSpoilers,
		arg.PromptWhy,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkID,
		&i.EditionID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.HasSpoilers,
		&i.PromptWhy,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createReviewComment = `-- name: CreateReviewComment :one

INSERT INTO review_comments (review_id, user_id, body) VALUES ($1, $2, $3)
RETURNING id, review_id, user_id, body, created_at, updated_at, deleted_at
`

type CreateReviewCommentParams struct {
	ReviewID uuid.UUID `json:"review_id"`
	UserID   uuid.UUID `json:"user_id"`
	Body     string    `json:"body"`
}

// ---- Comments ---------------------------------------------------------------
func (q *Queries) CreateReviewComment(ctx context.Context, arg CreateReviewCommentParams) (ReviewComment, error) {
	row := q.db.QueryRow(ctx, createReviewComment, arg.ReviewID, arg.UserID, arg.Body)
	var i ReviewComment
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT r.id, r.user_id, r.work_id, r.edition_id, r.rating, r.title, r.body, r.has_spoilers, r.prompt_why, r.like_count, r.created_at, r.updated_at, r.deleted_at, u.username, p.display_name, p.avatar_key,
       w.slug AS work_slug, w.title AS work_title
  FROM reviews r
  JOIN users u ON u.id = r.user_id
  LEFT JOIN profiles p ON p.user_id = u.id
  JOIN works w ON w.id = r.work_id
 WHERE r.id = $1 AND r.deleted_at IS NULL
`

type GetReviewByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	WorkID      uuid.UUID          `json:"work_id"`
	EditionID   pgtype.UUID        `json:"edition_id"`
	Rating      int32              `json:"rating"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	HasSpoilers bool               `json:"has_spoilers"`
	PromptWhy   string             `json:"prompt_why"`
	LikeCount   int32              `json:"like_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
	AvatarKey   *string            `json:"avatar_key"`
	WorkSlug    string             `json:"work_slug"`
	WorkTitle   string             `json:"work_title"`
}

func (q *Queries) GetReviewByID(ctx context.Context, id uuid.UUID) (GetReviewByIDRow, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i GetReviewByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkID,
		&i.EditionID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.HasSpoilers,
		&i.PromptWhy,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarKey,
		&i.WorkSlug,
		&i.WorkTitle,
	)
	return i, err
}

const getReviewByUserAndWork = `-- name: GetReviewByUserAndWork :one
SELECT id, user_id, work_id, edition_id, rating, title, body, has_spoilers, prompt_why, like_count, created_at, updated_at, deleted_at FROM reviews
 WHERE user_id = $1 AND work_id = $2 AND deleted_at IS NULL
`

type GetReviewByUserAndWorkParams struct {
	UserID uuid.UUID `json:"user_id"`
	WorkID uuid.UUID `json:"work_id"`
}

func (q *Queries) GetReviewByUserAndWork(ctx context.Context, arg GetReviewByUserAndWorkParams) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByUserAndWork, arg.UserID, arg.WorkID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkID,
		&i.EditionID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.HasSpoilers,
		&i.PromptWhy,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReviewComment = `-- name: GetReviewComment :one
SELECT id, review_id, user_id, body, created_at, updated_at, deleted_at FROM review_comments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetReviewComment(ctx context.Context, id uuid.UUID) (ReviewComment, error) {
	row := q.db.QueryRow(ctx, getReviewComment, id)
	var i ReviewComment
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hasUserLikedReview = `-- name: HasUserLikedReview :one
SELECT EXISTS (SELECT 1 FROM review_likes
                WHERE review_id = $1 AND user_id = $2) AS liked
`

type HasUserLikedReviewParams struct {
	ReviewID uuid.UUID `json:"review_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) HasUserLikedReview(ctx context.Context, arg HasUserLikedReviewParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserLikedReview, arg.ReviewID, arg.UserID)
	var liked bool
	err := row.Scan(&liked)
	return liked, err
}

const likeReview = `-- name: LikeReview :execrows

INSERT INTO review_likes (review_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LikeReviewParams struct {
	ReviewID uuid.UUID `json:"review_id"`
	UserID   uuid.UUID `json:"user_id"`
}

// ---- Likes ------------------------------------------------------------------
func (q *Queries) LikeReview(ctx context.Context, arg LikeReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, likeReview, arg.ReviewID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCommentsForReview = `-- name: ListCommentsForReview :many
SELECT c.id, c.review_id, c.user_id, c.body, c.created_at, c.updated_at, c.deleted_at, u.username, p.display_name
  FROM review_comments c
  JOIN users u ON u.id = c.user_id
  LEFT JOIN profiles p ON p.user_id = u.id
 WHERE c.review_id = $1 AND c.deleted_at IS NULL
 ORDER BY c.created_at ASC
 LIMIT $3 OFFSET $2
`

type ListCommentsForReviewParams struct {
	ReviewID uuid.UUID `json:"review_id"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

type ListCommentsForReviewRow struct {
	ID          uuid.UUID          `json:"id"`
	ReviewID    uuid.UUID          `json:"review_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
}

func (q *Queries) ListCommentsForReview(ctx context.Context, arg ListCommentsForReviewParams) ([]ListCommentsForReviewRow, error) {
	rows, err := q.db.Query(ctx, listCommentsForReview, arg.ReviewID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsForReviewRow{}
	for rows.Next() {
		var i ListCommentsForReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikedReviewIDsForUser = `-- name: ListLikedReviewIDsForUser :many
SELECT review_id FROM review_likes WHERE user_id = $1
`

func (q *Queries) ListLikedReviewIDsForUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLikedReviewIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var review_id uuid.UUID
		if err := rows.Scan(&review_id); err != nil {
			return nil, err
		}
		items = append(items, review_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByUser = `-- name: ListReviewsByUser :many
SELECT r.id, r.user_id, r.work_id, r.edition_id, r.rating, r.title, r.body, r.has_spoilers, r.prompt_why, r.like_count, r.created_at, r.updated_at, r.deleted_at, w.slug AS work_slug, w.title AS work_title, w.first_published,
       (SELECT a.name FROM work_authors wa JOIN authors a ON a.id = wa.author_id
         WHERE wa.work_id = w.id ORDER BY wa.position LIMIT 1) AS primary_author,
       (SELECT ca.object_key FROM editions e
          JOIN cover_assets ca ON ca.edition_id = e.id AND ca.is_primary
         WHERE e.work_id = w.id AND e.deleted_at IS NULL LIMIT 1) AS cover_key
  FROM reviews r
  JOIN works w ON w.id = r.work_id AND w.deleted_at IS NULL
 WHERE r.user_id = $1 AND r.deleted_at IS NULL
 ORDER BY r.created_at DESC
 LIMIT $3 OFFSET $2
`

type ListReviewsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Off    int32     `json:"off"`
	Lim    int32     `json:"lim"`
}

type ListReviewsByUserRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	WorkID         uuid.UUID          `json:"work_id"`
	EditionID      pgtype.UUID        `json:"edition_id"`
	Rating         int32              `json:"rating"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	HasSpoilers    bool               `json:"has_spoilers"`
	PromptWhy      string             `json:"prompt_why"`
	LikeCount      int32              `json:"like_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	WorkSlug       string             `json:"work_slug"`
	WorkTitle      string             `json:"work_title"`
	FirstPublished *int32             `json:"first_published"`
	PrimaryAuthor  string             `json:"primary_author"`
	CoverKey       *string            `json:"cover_key"`
}

func (q *Queries) ListReviewsByUser(ctx context.Context, arg ListReviewsByUserParams) ([]ListReviewsByUserRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByUser, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByUserRow{}
	for rows.Next() {
		var i ListReviewsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkID,
			&i.EditionID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.HasSpoilers,
			&i.PromptWhy,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.WorkSlug,
			&i.WorkTitle,
			&i.FirstPublished,
			&i.PrimaryAuthor,
			&i.CoverKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsForWork = `-- name: ListReviewsForWork :many
SELECT r.id, r.user_id, r.work_id, r.edition_id, r.rating, r.title, r.body, r.has_spoilers, r.prompt_why, r.like_count, r.created_at, r.updated_at, r.deleted_at, u.username, p.display_name, p.avatar_key, u.role AS author_role
  FROM reviews r
  JOIN users u ON u.id = r.user_id
  LEFT JOIN profiles p ON p.user_id = u.id
 WHERE r.work_id = $1 AND r.deleted_at IS NULL
 ORDER BY
   CASE $2::text
     WHEN 'highest' THEN r.rating
     WHEN 'lowest'  THEN -r.rating
     WHEN 'liked'   THEN r.like_count
     ELSE 0
   END DESC,
   r.created_at DESC
 LIMIT $4 OFFSET $3
`

type ListReviewsForWorkParams struct {
	WorkID uuid.UUID `json:"work_id"`
	Sort   string    `json:"sort"`
	Off    int32     `json:"off"`
	Lim    int32     `json:"lim"`
}

type ListReviewsForWorkRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	WorkID      uuid.UUID          `json:"work_id"`
	EditionID   pgtype.UUID        `json:"edition_id"`
	Rating      int32              `json:"rating"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	HasSpoilers bool               `json:"has_spoilers"`
	PromptWhy   string             `json:"prompt_why"`
	LikeCount   int32              `json:"like_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
	AvatarKey   *string            `json:"avatar_key"`
	AuthorRole  UserRole           `json:"author_role"`
}

func (q *Queries) ListReviewsForWork(ctx context.Context, arg ListReviewsForWorkParams) ([]ListReviewsForWorkRow, error) {
	rows, err := q.db.Query(ctx, listReviewsForWork,
		arg.WorkID,
		arg.Sort,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsForWorkRow{}
	for rows.Next() {
		var i ListReviewsForWorkRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkID,
			&i.EditionID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.HasSpoilers,
			&i.PromptWhy,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarKey,
			&i.AuthorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ratingDistributionForWork = `-- name: RatingDistributionForWork :many
SELECT rating, count(*)::bigint AS n
  FROM reviews
 WHERE work_id = $1 AND deleted_at IS NULL
 GROUP BY rating
 ORDER BY rating
`

type RatingDistributionForWorkRow struct {
	Rating int32 `json:"rating"`
	N      int64 `json:"n"`
}

// Powers the histogram on the book page. GROUP BY over the half-star scale so
// the UI never has to bucket in application code.
func (q *Queries) RatingDistributionForWork(ctx context.Context, workID uuid.UUID) ([]RatingDistributionForWorkRow, error) {
	rows, err := q.db.Query(ctx, ratingDistributionForWork, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RatingDistributionForWorkRow{}
	for rows.Next() {
		var i RatingDistributionForWorkRow
		if err := rows.Scan(&i.Rating, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordContribution = `-- name: RecordContribution :exec
INSERT INTO contribution_ledger (user_id, kind) VALUES ($1, $2)
`

type RecordContributionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Kind   string    `json:"kind"`
}

func (q *Queries) RecordContribution(ctx context.Context, arg RecordContributionParams) error {
	_, err := q.db.Exec(ctx, recordContribution, arg.UserID, arg.Kind)
	return err
}

const softDeleteReview = `-- name: SoftDeleteReview :execrows
UPDATE reviews SET deleted_at = now() WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteReviewParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteReview(ctx context.Context, arg SoftDeleteReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteReview, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteReviewComment = `-- name: SoftDeleteReviewComment :execrows
UPDATE review_comments SET deleted_at = now()
 WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteReviewCommentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteReviewComment(ctx context.Context, arg SoftDeleteReviewCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteReviewComment, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const syncReviewLikeCount = `-- name: SyncReviewLikeCount :exec
UPDATE reviews r
   SET like_count = (SELECT count(*)::integer FROM review_likes rl WHERE rl.review_id = r.id)
 WHERE r.id = $1
`

// Denormalized count refreshed on change; keeps list queries free of a
// correlated aggregate over review_likes.
func (q *Queries) SyncReviewLikeCount(ctx context.Context, reviewID uuid.UUID) error {
	_, err := q.db.Exec(ctx, syncReviewLikeCount, reviewID)
	return err
}

const unlikeReview = `-- name: UnlikeReview :execrows
DELETE FROM review_likes WHERE review_id = $1 AND user_id = $2
`

type UnlikeReviewParams struct {
	ReviewID uuid.UUID `json:"review_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) UnlikeReview(ctx context.Context, arg UnlikeReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlikeReview, arg.ReviewID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
   SET rating       = $1,
       title        = $2,
       body         = $3,
       has_spoilers = $4,
       prompt_why   = $5,
       edition_id   = COALESCE($6, edition_id)
 WHERE id = $7 AND user_id = $8 AND deleted_at IS NULL
RETURNING id, user_id, work_id, edition_id, rating, title, body, has_spoilers, prompt_why, like_count, created_at, updated_at, deleted_at
`

type UpdateReviewParams struct {
	Rating      int32       `json:"rating"`
	Title       string      `json:"title"`
	Body        string      `json:"body"`
	HasSpoilers bool        `json:"has_spoilers"`
	PromptWhy   string      `json:"prompt_why"`
	EditionID   pgtype.UUID `json:"edition_id"`
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview,
		arg.Rating,
		arg.Title,
		arg.Body,
		arg.HasSpoilers,
		arg.PromptWhy,
		arg.EditionID,
		arg.ID,
		arg.UserID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkID,
		&i.EditionID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.HasSpoilers,
		&i.PromptWhy,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
