// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scholars.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addNoteCitation = `-- name: AddNoteCitation :exec
INSERT INTO note_citations (note_id, citation, url, position)
VALUES ($1, $2, $3, $4)
`

type AddNoteCitationParams struct {
	NoteID   uuid.UUID `json:"note_id"`
	Citation string    `json:"citation"`
	Url      *string   `json:"url"`
	Position int32     `json:"position"`
}

func (q *Queries) AddNoteCitation(ctx context.Context, arg AddNoteCitationParams) error {
	_, err := q.db.Exec(ctx, addNoteCitation,
		arg.NoteID,
		arg.Citation,
		arg.Url,
		arg.Position,
	)
	return err
}

const countNoteApprovals = `-- name: CountNoteApprovals :one
SELECT count(*) FROM note_reviews nr
  JOIN scholar_profiles sp ON sp.user_id = nr.reviewer_id AND sp.status = 'verified'
 WHERE nr.note_id = $1 AND nr.approved AND nr.reviewer_id <> $2
`

type CountNoteApprovalsParams struct {
	NoteID   uuid.UUID `json:"note_id"`
	AuthorID uuid.UUID `json:"author_id"`
}

// Distinct verified scholars, excluding the author: the peer-review gate.
func (q *Queries) CountNoteApprovals(ctx context.Context, arg CountNoteApprovalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNoteApprovals, arg.NoteID, arg.AuthorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNoteCitations = `-- name: CountNoteCitations :one
SELECT count(*) FROM note_citations WHERE note_id = $1
`

func (q *Queries) CountNoteCitations(ctx context.Context, noteID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNoteCitations, noteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScholarNote = `-- name: CreateScholarNote :one
INSERT INTO scholar_notes (work_id, author_id, chapter_ref, anchor_quote, title, body, kind, status, is_community)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9)
RETURNING id, work_id, author_id, chapter_ref, anchor_quote, title, body, kind, status, is_community, version, created_at, updated_at
`

type CreateScholarNoteParams struct {
	WorkID      uuid.UUID  `json:"work_id"`
	AuthorID    uuid.UUID  `json:"author_id"`
	ChapterRef  string     `json:"chapter_ref"`
	AnchorQuote string     `json:"anchor_quote"`
	Title       string     `json:"title"`
	Body        string     `json:"body"`
	Kind        string     `json:"kind"`
	Status      NoteStatus `json:"status"`
	IsCommunity bool       `json:"is_community"`
}

func (q *Queries) CreateScholarNote(ctx context.Context, arg CreateScholarNoteParams) (ScholarNote, error) {
	row := q.db.QueryRow(ctx, createScholarNote,
		arg.WorkID,
		arg.AuthorID,
		arg.ChapterRef,
		arg.AnchorQuote,
		arg.Title,
		arg.Body,
		arg.Kind,
		arg.Status,
		arg.IsCommunity,
	)
	var i ScholarNote
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.AuthorID,
		&i.ChapterRef,
		&i.AnchorQuote,
		&i.Title,
		&i.Body,
		&i.Kind,
		&i.Status,
		&i.IsCommunity,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNoteCitation = `-- name: DeleteNoteCitation :execrows
DELETE FROM note_citations WHERE id = $1 AND note_id = $2
`

type DeleteNoteCitationParams struct {
	ID     uuid.UUID `json:"id"`
	NoteID uuid.UUID `json:"note_id"`
}

func (q *Queries) DeleteNoteCitation(ctx context.Context, arg DeleteNoteCitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNoteCitation, arg.ID, arg.NoteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScholarNote = `-- name: GetScholarNote :one
SELECT n.id, n.work_id, n.author_id, n.chapter_ref, n.anchor_quote, n.title, n.body, n.kind, n.status, n.is_community, n.version, n.created_at, n.updated_at, u.username, p.display_name,
       sp.field, sp.affiliation, sp.status AS scholar_status,
       w.slug AS work_slug, w.title AS work_title
  FROM scholar_notes n
  JOIN users u ON u.id = n.author_id
  LEFT JOIN profiles p ON p.user_id = u.id
  LEFT JOIN scholar_profiles sp ON sp.user_id = n.author_id
  JOIN works w ON w.id = n.work_id
 WHERE n.id = $1
`

type GetScholarNoteRow struct {
	ID            uuid.UUID          `json:"id"`
	WorkID        uuid.UUID          `json:"work_id"`
	AuthorID      uuid.UUID          `json:"author_id"`
	ChapterRef    string             `json:"chapter_ref"`
	AnchorQuote   string             `json:"anchor_quote"`
	Title         string             `json:"title"`
	Body          string             `json:"body"`
	Kind          string             `json:"kind"`
	Status        NoteStatus         `json:"status"`
	IsCommunity   bool               `json:"is_community"`
	Version       int32              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Username      string             `json:"username"`
	DisplayName   *string            `json:"display_name"`
	Field         *string            `json:"field"`
	Affiliation   *string            `json:"affiliation"`
	ScholarStatus NullScholarStatus  `json:"scholar_status"`
	WorkSlug      string             `json:"work_slug"`
	WorkTitle     string             `json:"work_title"`
}

func (q *Queries) GetScholarNote(ctx context.Context, id uuid.UUID) (GetScholarNoteRow, error) {
	row := q.db.QueryRow(ctx, getScholarNote, id)
	var i GetScholarNoteRow
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.AuthorID,
		&i.ChapterRef,
		&i.AnchorQuote,
		&i.Title,
		&i.Body,
		&i.Kind,
		&i.Status,
		&i.IsCommunity,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.DisplayName,
		&i.Field,
		&i.Affiliation,
		&i.ScholarStatus,
		&i.WorkSlug,
		&i.WorkTitle,
	)
	return i, err
}

const getScholarProfile = `-- name: GetScholarProfile :one
SELECT user_id, field, affiliation, orcid, status, verified_by, verified_at, coi_statement, created_at, updated_at FROM scholar_profiles WHERE user_id = $1
`

func (q *Queries) GetScholarProfile(ctx context.Context, userID uuid.UUID) (ScholarProfile, error) {
	row := q.db.QueryRow(ctx, getScholarProfile, userID)
	var i ScholarProfile
	err := row.Scan(
		&i.UserID,
		&i.Field,
		&i.Affiliation,
		&i.Orcid,
		&i.Status,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.CoiStatement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isVerifiedScholar = `-- name: IsVerifiedScholar :one
SELECT EXISTS (SELECT 1 FROM scholar_profiles
                WHERE user_id = $1 AND status = 'verified') AS verified
`

func (q *Queries) IsVerifiedScholar(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isVerifiedScholar, userID)
	var verified bool
	err := row.Scan(&verified)
	return verified, err
}

const listNoteCitations = `-- name: ListNoteCitations :many
SELECT id, note_id, citation, url, position FROM note_citations WHERE note_id = $1 ORDER BY position, citation
`

func (q *Queries) ListNoteCitations(ctx context.Context, noteID uuid.UUID) ([]NoteCitation, error) {
	rows, err := q.db.Query(ctx, listNoteCitations, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NoteCitation{}
	for rows.Next() {
		var i NoteCitation
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.Citation,
			&i.Url,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteReviews = `-- name: ListNoteReviews :many
SELECT nr.note_id, nr.reviewer_id, nr.approved, nr.comments, nr.created_at, u.username, sp.field
  FROM note_reviews nr
  JOIN users u ON u.id = nr.reviewer_id
  LEFT JOIN scholar_profiles sp ON sp.user_id = nr.reviewer_id
 WHERE nr.note_id = $1
 ORDER BY nr.created_at
`

type ListNoteReviewsRow struct {
	NoteID     uuid.UUID          `json:"note_id"`
	ReviewerID uuid.UUID          `json:"reviewer_id"`
	Approved   bool               `json:"approved"`
	Comments   string             `json:"comments"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Username   string             `json:"username"`
	Field      *string            `json:"field"`
}

func (q *Queries) ListNoteReviews(ctx context.Context, noteID uuid.UUID) ([]ListNoteReviewsRow, error) {
	rows, err := q.db.Query(ctx, listNoteReviews, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNoteReviewsRow{}
	for rows.Next() {
		var i ListNoteReviewsRow
		if err := rows.Scan(
			&i.NoteID,
			&i.ReviewerID,
			&i.Approved,
			&i.Comments,
			&i.CreatedAt,
			&i.Username,
			&i.Field,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteRevisions = `-- name: ListNoteRevisions :many
SELECT id, note_id, version, title, body, edited_by, created_at FROM note_revisions WHERE note_id = $1 ORDER BY version DESC
`

func (q *Queries) ListNoteRevisions(ctx context.Context, noteID uuid.UUID) ([]NoteRevision, error) {
	rows, err := q.db.Query(ctx, listNoteRevisions, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NoteRevision{}
	for rows.Next() {
		var i NoteRevision
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.Version,
			&i.Title,
			&i.Body,
			&i.EditedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesAwaitingReview = `-- name: ListNotesAwaitingReview :many
SELECT n.id, n.work_id, n.author_id, n.chapter_ref, n.anchor_quote, n.title, n.body, n.kind, n.status, n.is_community, n.version, n.created_at, n.updated_at, u.username, w.title AS work_title, w.slug AS work_slug
  FROM scholar_notes n
  JOIN users u ON u.id = n.author_id
  JOIN works w ON w.id = n.work_id
 WHERE n.status = 'in_review'
 ORDER BY n.created_at ASC
 LIMIT $2 OFFSET $1
`

type ListNotesAwaitingReviewParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

type ListNotesAwaitingReviewRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkID      uuid.UUID          `json:"work_id"`
	AuthorID    uuid.UUID          `json:"author_id"`
	ChapterRef  string             `json:"chapter_ref"`
	AnchorQuote string             `json:"anchor_quote"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Kind        string             `json:"kind"`
	Status      NoteStatus         `json:"status"`
	IsCommunity bool               `json:"is_community"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Username    string             `json:"username"`
	WorkTitle   string             `json:"work_title"`
	WorkSlug    string             `json:"work_slug"`
}

func (q *Queries) ListNotesAwaitingReview(ctx context.Context, arg ListNotesAwaitingReviewParams) ([]ListNotesAwaitingReviewRow, error) {
	rows, err := q.db.Query(ctx, listNotesAwaitingReview, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotesAwaitingReviewRow{}
	for rows.Next() {
		var i ListNotesAwaitingReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkID,
			&i.AuthorID,
			&i.ChapterRef,
			&i.AnchorQuote,
			&i.Title,
			&i.Body,
			&i.Kind,
			&i.Status,
			&i.IsCommunity,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.WorkTitle,
			&i.WorkSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesForWork = `-- name: ListNotesForWork :many
SELECT n.id, n.work_id, n.author_id, n.chapter_ref, n.anchor_quote, n.title, n.body, n.kind, n.status, n.is_community, n.version, n.created_at, n.updated_at, u.username, p.display_name,
       sp.field, sp.affiliation, sp.status AS scholar_status,
       (SELECT count(*)::bigint FROM note_citations c WHERE c.note_id = n.id) AS citation_count
  FROM scholar_notes n
  JOIN users u ON u.id = n.author_id
  LEFT JOIN profiles p ON p.user_id = u.id
  LEFT JOIN scholar_profiles sp ON sp.user_id = n.author_id
 WHERE n.work_id = $1
   AND (n.status = 'published'
        OR ($2::uuid IS NOT NULL AND n.author_id = $2
            AND n.status IN ('draft', 'in_review')))
   AND ($3::text IS NULL OR n.chapter_ref = $3)
 ORDER BY n.chapter_ref, n.created_at DESC
 LIMIT $5 OFFSET $4
`

type ListNotesForWorkParams struct {
	WorkID     uuid.UUID   `json:"work_id"`
	ViewerID   pgtype.UUID `json:"viewer_id"`
	ChapterRef *string     `json:"chapter_ref"`
	Off        int32       `json:"off"`
	Lim        int32       `json:"lim"`
}

type ListNotesForWorkRow struct {
	ID            uuid.UUID          `json:"id"`
	WorkID        uuid.UUID          `json:"work_id"`
	AuthorID      uuid.UUID          `json:"author_id"`
	ChapterRef    string             `json:"chapter_ref"`
	AnchorQuote   string             `json:"anchor_quote"`
	Title         string             `json:"title"`
	Body          string             `json:"body"`
	Kind          string             `json:"kind"`
	Status        NoteStatus         `json:"status"`
	IsCommunity   bool               `json:"is_community"`
	Version       int32              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Username      string             `json:"username"`
	DisplayName   *string            `json:"display_name"`
	Field         *string            `json:"field"`
	Affiliation   *string            `json:"affiliation"`
	ScholarStatus NullScholarStatus  `json:"scholar_status"`
	CitationCount int64              `json:"citation_count"`
}

// Readers see published notes, plus their own drafts so an author can resume
// editing. Community-contributor notes are returned with is_community set, and
// the UI labels them differently from verified-scholar notes — no elitism, but
// no false equivalence either.
func (q *Queries) ListNotesForWork(ctx context.Context, arg ListNotesForWorkParams) ([]ListNotesForWorkRow, error) {
	rows, err := q.db.Query(ctx, listNotesForWork,
		arg.WorkID,
		arg.ViewerID,
		arg.ChapterRef,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotesForWorkRow{}
	for rows.Next() {
		var i ListNotesForWorkRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkID,
			&i.AuthorID,
			&i.ChapterRef,
			&i.AnchorQuote,
			&i.Title,
			&i.Body,
			&i.Kind,
			&i.Status,
			&i.IsCommunity,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.Field,
			&i.Affiliation,
			&i.ScholarStatus,
			&i.CitationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingScholarProfiles = `-- name: ListPendingScholarProfiles :many
SELECT sp.user_id, sp.field, sp.affiliation, sp.orcid, sp.status, sp.verified_by, sp.verified_at, sp.coi_statement, sp.created_at, sp.updated_at, u.username, u.email
  FROM scholar_profiles sp JOIN users u ON u.id = sp.user_id
 WHERE sp.status = 'pending'
 ORDER BY sp.created_at ASC
 LIMIT $2 OFFSET $1
`

type ListPendingScholarProfilesParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

type ListPendingScholarProfilesRow struct {
	UserID       uuid.UUID          `json:"user_id"`
	Field        string             `json:"field"`
	Affiliation  *string            `json:"affiliation"`
	Orcid        *string            `json:"orcid"`
	Status       ScholarStatus      `json:"status"`
	VerifiedBy   pgtype.UUID        `json:"verified_by"`
	VerifiedAt   pgtype.Timestamptz `json:"verified_at"`
	CoiStatement string             `json:"coi_statement"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
}

func (q *Queries) ListPendingScholarProfiles(ctx context.Context, arg ListPendingScholarProfilesParams) ([]ListPendingScholarProfilesRow, error) {
	rows, err := q.db.Query(ctx, listPendingScholarProfiles, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingScholarProfilesRow{}
	for rows.Next() {
		var i ListPendingScholarProfilesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Field,
			&i.Affiliation,
			&i.Orcid,
			&i.Status,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.CoiStatement,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordNoteRevision = `-- name: RecordNoteRevision :exec
INSERT INTO note_revisions (note_id, version, title, body, edited_by)
VALUES ($1, $2, $3, $4, $5)
`

type RecordNoteRevisionParams struct {
	NoteID   uuid.UUID   `json:"note_id"`
	Version  int32       `json:"version"`
	Title    string      `json:"title"`
	Body     string      `json:"body"`
	EditedBy pgtype.UUID `json:"edited_by"`
}

// Append-only history: every edit is recoverable, which is what makes
// retracting or disputing a scholarly claim possible.
func (q *Queries) RecordNoteRevision(ctx context.Context, arg RecordNoteRevisionParams) error {
	_, err := q.db.Exec(ctx, recordNoteRevision,
		arg.NoteID,
		arg.Version,
		arg.Title,
		arg.Body,
		arg.EditedBy,
	)
	return err
}

const reviewNote = `-- name: ReviewNote :exec
INSERT INTO note_reviews (note_id, reviewer_id, approved, comments)
VALUES ($1, $2, $3, $4)
ON CONFLICT (note_id, reviewer_id) DO UPDATE SET
  approved = EXCLUDED.approved, comments = EXCLUDED.comments
`

type ReviewNoteParams struct {
	NoteID     uuid.UUID `json:"note_id"`
	ReviewerID uuid.UUID `json:"reviewer_id"`
	Approved   bool      `json:"approved"`
	Comments   string    `json:"comments"`
}

func (q *Queries) ReviewNote(ctx context.Context, arg ReviewNoteParams) error {
	_, err := q.db.Exec(ctx, reviewNote,
		arg.NoteID,
		arg.ReviewerID,
		arg.Approved,
		arg.Comments,
	)
	return err
}

const setNoteStatus = `-- name: SetNoteStatus :execrows
UPDATE scholar_notes SET status = $1 WHERE id = $2
`

type SetNoteStatusParams struct {
	Status NoteStatus `json:"status"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) SetNoteStatus(ctx context.Context, arg SetNoteStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNoteStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setScholarStatus = `-- name: SetScholarStatus :execrows
UPDATE scholar_profiles
   SET status = $1,
       verified_by = CASE WHEN $1 = 'verified'::scholar_status THEN $2 ELSE verified_by END,
       verified_at = CASE WHEN $1 = 'verified'::scholar_status THEN now() ELSE verified_at END
 WHERE user_id = $3
`

type SetScholarStatusParams struct {
	Status     ScholarStatus `json:"status"`
	VerifiedBy pgtype.UUID   `json:"verified_by"`
	UserID     uuid.UUID     `json:"user_id"`
}

// The literal is cast explicitly: reusing @status in both an enum assignment
// and a comparison leaves Postgres unable to deduce the parameter's type.
func (q *Queries) SetScholarStatus(ctx context.Context, arg SetScholarStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setScholarStatus, arg.Status, arg.VerifiedBy, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateScholarNote = `-- name: UpdateScholarNote :one
UPDATE scholar_notes
   SET title = $1, body = $2, chapter_ref = $3,
       anchor_quote = $4, kind = $5,
       version = scholar_notes.version + 1
 WHERE id = $6 AND author_id = $7
RETURNING id, work_id, author_id, chapter_ref, anchor_quote, title, body, kind, status, is_community, version, created_at, updated_at
`

type UpdateScholarNoteParams struct {
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	ChapterRef  string    `json:"chapter_ref"`
	AnchorQuote string    `json:"anchor_quote"`
	Kind        string    `json:"kind"`
	ID          uuid.UUID `json:"id"`
	AuthorID    uuid.UUID `json:"author_id"`
}

func (q *Queries) UpdateScholarNote(ctx context.Context, arg UpdateScholarNoteParams) (ScholarNote, error) {
	row := q.db.QueryRow(ctx, updateScholarNote,
		arg.Title,
		arg.Body,
		arg.ChapterRef,
		arg.AnchorQuote,
		arg.Kind,
		arg.ID,
		arg.AuthorID,
	)
	var i ScholarNote
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.AuthorID,
		&i.ChapterRef,
		&i.AnchorQuote,
		&i.Title,
		&i.Body,
		&i.Kind,
		&i.Status,
		&i.IsCommunity,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertScholarProfile = `-- name: UpsertScholarProfile :one

INSERT INTO scholar_profiles (user_id, field, affiliation, orcid, coi_statement, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
ON CONFLICT (user_id) DO UPDATE SET
  field         = EXCLUDED.field,
  affiliation   = EXCLUDED.affiliation,
  orcid         = EXCLUDED.orcid,
  coi_statement = EXCLUDED.coi_statement
RETURNING user_id, field, affiliation, orcid, status, verified_by, verified_at, coi_statement, created_at, updated_at
`

type UpsertScholarProfileParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Field        string    `json:"field"`
	Affiliation  *string   `json:"affiliation"`
	Orcid        *string   `json:"orcid"`
	CoiStatement string    `json:"coi_statement"`
}

// Scholar system: verified contributors, peer-reviewed notes, citations.
//
// Two invariants the schema and these queries enforce together:
//  1. a published note has at least one citation
//  2. a note reaches `published` only after two approvals from distinct
//     verified scholars, and never from its own author
func (q *Queries) UpsertScholarProfile(ctx context.Context, arg UpsertScholarProfileParams) (ScholarProfile, error) {
	row := q.db.QueryRow(ctx, upsertScholarProfile,
		arg.UserID,
		arg.Field,
		arg.Affiliation,
		arg.Orcid,
		arg.CoiStatement,
	)
	var i ScholarProfile
	err := row.Scan(
		&i.UserID,
		&i.Field,
		&i.Affiliation,
		&i.Orcid,
		&i.Status,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.CoiStatement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
