// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: search.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const authorSearchDocuments = `-- name: AuthorSearchDocuments :many
SELECT a.id, a.slug, a.name, a.sort_name, a.bio, a.birth_year, a.death_year,
       a.is_claimed,
       (SELECT count(*)::bigint FROM work_authors wa JOIN works w ON w.id = wa.work_id
         WHERE wa.author_id = a.id AND w.deleted_at IS NULL) AS work_count
  FROM authors a
 WHERE a.deleted_at IS NULL
   AND ($1::uuid[] IS NULL OR a.id = ANY($1::uuid[]))
 ORDER BY a.id
 LIMIT $3 OFFSET $2
`

type AuthorSearchDocumentsParams struct {
	Ids []uuid.UUID `json:"ids"`
	Off int32       `json:"off"`
	Lim int32       `json:"lim"`
}

type AuthorSearchDocumentsRow struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	SortName  string    `json:"sort_name"`
	Bio       string    `json:"bio"`
	BirthYear *int32    `json:"birth_year"`
	DeathYear *int32    `json:"death_year"`
	IsClaimed bool      `json:"is_claimed"`
	WorkCount int64     `json:"work_count"`
}

func (q *Queries) AuthorSearchDocuments(ctx context.Context, arg AuthorSearchDocumentsParams) ([]AuthorSearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, authorSearchDocuments, arg.Ids, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthorSearchDocumentsRow{}
	for rows.Next() {
		var i AuthorSearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.SortName,
			&i.Bio,
			&i.BirthYear,
			&i.DeathYear,
			&i.IsClaimed,
			&i.WorkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clubSearchDocuments = `-- name: ClubSearchDocuments :many
SELECT c.id, c.slug, c.name, c.description, c.is_private,
       (SELECT count(*)::bigint FROM club_memberships cm WHERE cm.club_id = c.id) AS member_count
  FROM clubs c
 WHERE c.deleted_at IS NULL AND NOT c.is_private
 ORDER BY c.id
 LIMIT $2 OFFSET $1
`

type ClubSearchDocumentsParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

type ClubSearchDocumentsRow struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsPrivate   bool      `json:"is_private"`
	MemberCount int64     `json:"member_count"`
}

func (q *Queries) ClubSearchDocuments(ctx context.Context, arg ClubSearchDocumentsParams) ([]ClubSearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, clubSearchDocuments, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClubSearchDocumentsRow{}
	for rows.Next() {
		var i ClubSearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IsPrivate,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndexedWorkIDs = `-- name: ListIndexedWorkIDs :many
SELECT id FROM works WHERE deleted_at IS NULL ORDER BY id LIMIT $2 OFFSET $1
`

type ListIndexedWorkIDsParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

func (q *Queries) ListIndexedWorkIDs(ctx context.Context, arg ListIndexedWorkIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listIndexedWorkIDs, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workSearchDocuments = `-- name: WorkSearchDocuments :many

SELECT w.id, w.slug, w.title, w.subtitle, w.description, w.first_published,
       w.original_language, w.is_public_domain, w.rating_sum, w.rating_count,
       coalesce((
         SELECT json_agg(json_build_object('name', a.name, 'slug', a.slug, 'role', wa.role)
                         ORDER BY wa.position)
           FROM work_authors wa JOIN authors a ON a.id = wa.author_id
          WHERE wa.work_id = w.id), '[]'::json) AS authors_json,
       coalesce((
         SELECT json_agg(DISTINCT s.name)
           FROM work_subjects ws JOIN subjects s ON s.id = ws.subject_id
          WHERE ws.work_id = w.id), '[]'::json) AS subjects_json,
       (SELECT e.gutenberg_id FROM editions e
         WHERE e.work_id = w.id AND e.gutenberg_id IS NOT NULL AND e.deleted_at IS NULL
         ORDER BY e.gutenberg_id LIMIT 1) AS gutenberg_id,
       -- Edition/cover facts arrive as ONE nullable json object. Scalar
       -- subqueries are NULL when a work has no edition yet, and sqlc cannot
       -- see that through casts; a json column is nullable by construction and
       -- is parsed defensively in Go, so the scan can never fail on an
       -- edition-less work.
       (SELECT json_build_object(
                  'edition_id', e.id::text,
                  'cover_key',  ca.object_key,
                  'license',    ca.license::text)
          FROM editions e
          LEFT JOIN cover_assets ca ON ca.edition_id = e.id AND ca.is_primary
         WHERE e.work_id = w.id AND e.deleted_at IS NULL
         ORDER BY e.published_on DESC NULLS LAST
         LIMIT 1) AS edition_json,
       (SELECT count(*)::bigint FROM reviews r
         WHERE r.work_id = w.id AND r.deleted_at IS NULL) AS review_count
  FROM works w
 WHERE w.deleted_at IS NULL
   AND ($1::uuid[] IS NULL OR w.id = ANY($1::uuid[]))
 ORDER BY w.id
 LIMIT $3 OFFSET $2
`

type WorkSearchDocumentsParams struct {
	Ids []uuid.UUID `json:"ids"`
	Off int32       `json:"off"`
	Lim int32       `json:"lim"`
}

type WorkSearchDocumentsRow struct {
	ID               uuid.UUID   `json:"id"`
	Slug             string      `json:"slug"`
	Title            string      `json:"title"`
	Subtitle         *string     `json:"subtitle"`
	Description      string      `json:"description"`
	FirstPublished   *int32      `json:"first_published"`
	OriginalLanguage string      `json:"original_language"`
	IsPublicDomain   bool        `json:"is_public_domain"`
	RatingSum        int64       `json:"rating_sum"`
	RatingCount      int64       `json:"rating_count"`
	AuthorsJson      interface{} `json:"authors_json"`
	SubjectsJson     interface{} `json:"subjects_json"`
	GutenbergID      *int32      `json:"gutenberg_id"`
	EditionJson      []byte      `json:"edition_json"`
	ReviewCount      int64       `json:"review_count"`
}

// Search projections.
//
// Meilisearch is fed from Postgres, never written to directly by request
// handlers: the database stays the source of truth and the index is a derived,
// rebuildable projection. These queries shape exactly one index document each,
// so reindexing is a pure function of the catalogue.
//
// Nested arrays are returned as JSON and unmarshalled in Go (internal/search),
// which keeps sqlc's types honest instead of smuggling strings through SQL.
func (q *Queries) WorkSearchDocuments(ctx context.Context, arg WorkSearchDocumentsParams) ([]WorkSearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, workSearchDocuments, arg.Ids, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkSearchDocumentsRow{}
	for rows.Next() {
		var i WorkSearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.FirstPublished,
			&i.OriginalLanguage,
			&i.IsPublicDomain,
			&i.RatingSum,
			&i.RatingCount,
			&i.AuthorsJson,
			&i.SubjectsJson,
			&i.GutenbergID,
			&i.EditionJson,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
