// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: social.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const blockUser = `-- name: BlockUser :execrows
INSERT INTO user_blocks (blocker_id, blocked_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type BlockUserParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countFollows = `-- name: CountFollows :one
SELECT
  (SELECT count(*)::bigint FROM follows f1 WHERE f1.follower_id = $1) AS following,
  (SELECT count(*)::bigint FROM follows f2 WHERE f2.followee_id = $1) AS followers
`

type CountFollowsRow struct {
	Following int64 `json:"following"`
	Followers int64 `json:"followers"`
}

func (q *Queries) CountFollows(ctx context.Context, userID uuid.UUID) (CountFollowsRow, error) {
	row := q.db.QueryRow(ctx, countFollows, userID)
	var i CountFollowsRow
	err := row.Scan(&i.Following, &i.Followers)
	return i, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (user_id, kind, payload) VALUES ($1, $2, $3)
RETURNING id, user_id, kind, payload, read_at, created_at
`

type CreateNotificationParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Kind    string    `json:"kind"`
	Payload []byte    `json:"payload"`
}

// ---- Notifications ----------------------------------------------------------
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.UserID, arg.Kind, arg.Payload)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const followUser = `-- name: FollowUser :execrows

INSERT INTO follows (follower_id, followee_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

// Social graph and the chronological feed.
//
// The feed is a UNION over activity types ordered by time. There is no score
// column, no engagement weighting, and no ranking function — that absence is
// the product decision. "Community Picks" elsewhere is collaborative filtering
// over co-occurrence (readers of X also read Y), which is computed in the
// worker and stored, never blended into this stream.
func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS (SELECT 1 FROM user_blocks
                WHERE (blocker_id = $1 AND blocked_id = $2)
                   OR (blocker_id = $2 AND blocked_id = $1)) AS blocked
`

type IsBlockedParams struct {
	A uuid.UUID `json:"a"`
	B uuid.UUID `json:"b"`
}

// Checked in BOTH directions: a block is not an invitation to be replied to.
func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, arg.A, arg.B)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (SELECT 1 FROM follows
                WHERE follower_id = $1 AND followee_id = $2) AS following
`

type IsFollowingParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FolloweeID)
	var following bool
	err := row.Scan(&following)
	return following, err
}

const listBlockedUsers = `-- name: ListBlockedUsers :many
SELECT u.id, u.username, b.created_at
  FROM user_blocks b JOIN users u ON u.id = b.blocked_id
 WHERE b.blocker_id = $1
 ORDER BY b.created_at DESC
`

type ListBlockedUsersRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListBlockedUsers(ctx context.Context, userID uuid.UUID) ([]ListBlockedUsersRow, error) {
	rows, err := q.db.Query(ctx, listBlockedUsers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlockedUsersRow{}
	for rows.Next() {
		var i ListBlockedUsersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoOccurringWorks = `-- name: ListCoOccurringWorks :many
WITH co_shelves AS (
  -- Shelves containing the source work. Private shelves are excluded so a
  -- reader's private library never influences anybody's recommendations.
  SELECT DISTINCT si.shelf_id
    FROM shelf_items si
    JOIN shelves s ON s.id = si.shelf_id AND NOT s.is_private
   WHERE si.work_id = $2
),
candidates AS (
  -- The minimum-shared threshold is a HAVING, not an outer WHERE: sqlc cannot
  -- resolve CTE aliases in the outer predicate, and filtering here keeps the
  -- join set small either way.
  SELECT si.work_id, count(*)::float AS shared
    FROM shelf_items si
    JOIN shelves s ON s.id = si.shelf_id AND NOT s.is_private
   WHERE si.shelf_id IN (SELECT shelf_id FROM co_shelves)
     AND si.work_id <> $2
   GROUP BY si.work_id
  HAVING count(*) >= $3
),
popularity AS (
  SELECT si.work_id, count(*)::float AS total
    FROM shelf_items si
    JOIN shelves s ON s.id = si.shelf_id AND NOT s.is_private
   GROUP BY si.work_id
)
SELECT w.id, w.slug, w.title, w.first_published, w.rating_sum, w.rating_count,
       (c.shared / (1.0 + p.total))::float AS affinity,
       (SELECT a.name FROM work_authors wa JOIN authors a ON a.id = wa.author_id
         WHERE wa.work_id = w.id ORDER BY wa.position LIMIT 1) AS primary_author,
       (SELECT ca.object_key FROM editions e
          JOIN cover_assets ca ON ca.edition_id = e.id AND ca.is_primary
         WHERE e.work_id = w.id AND e.deleted_at IS NULL LIMIT 1) AS cover_key
  FROM candidates c
  JOIN popularity p ON p.work_id = c.work_id
  JOIN works w ON w.id = c.work_id AND w.deleted_at IS NULL
 ORDER BY affinity DESC
 LIMIT $1
`

type ListCoOccurringWorksParams struct {
	Lim       int32       `json:"lim"`
	WorkID    uuid.UUID   `json:"work_id"`
	MinShared interface{} `json:"min_shared"`
}

type ListCoOccurringWorksRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Title          string    `json:"title"`
	FirstPublished *int32    `json:"first_published"`
	RatingSum      int64     `json:"rating_sum"`
	RatingCount    int64     `json:"rating_count"`
	Affinity       float64   `json:"affinity"`
	PrimaryAuthor  string    `json:"primary_author"`
	CoverKey       *string   `json:"cover_key"`
}

// "Readers of this also read", computed from shared shelves. Collaborative
// filtering over co-occurrence, not engagement: a book ranks here because
// people who shelved X also shelved Y, weighted by how selective Y is
// (inverse popularity), which is what keeps blockbusters from swallowing every
// recommendation slot.
func (q *Queries) ListCoOccurringWorks(ctx context.Context, arg ListCoOccurringWorksParams) ([]ListCoOccurringWorksRow, error) {
	rows, err := q.db.Query(ctx, listCoOccurringWorks, arg.Lim, arg.WorkID, arg.MinShared)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoOccurringWorksRow{}
	for rows.Next() {
		var i ListCoOccurringWorksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.FirstPublished,
			&i.RatingSum,
			&i.RatingCount,
			&i.Affinity,
			&i.PrimaryAuthor,
			&i.CoverKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowers = `-- name: ListFollowers :many
SELECT u.id, u.username, p.display_name, p.avatar_key, f.created_at AS followed_at
  FROM follows f
  JOIN users u ON u.id = f.follower_id AND u.deleted_at IS NULL
  LEFT JOIN profiles p ON p.user_id = u.id
 WHERE f.followee_id = $1
 ORDER BY f.created_at DESC
 LIMIT $3 OFFSET $2
`

type ListFollowersParams struct {
	UserID uuid.UUID `json:"user_id"`
	Off    int32     `json:"off"`
	Lim    int32     `json:"lim"`
}

type ListFollowersRow struct {
	ID          uuid.UUID          `json:"id"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
	AvatarKey   *string            `json:"avatar_key"`
	FollowedAt  pgtype.Timestamptz `json:"followed_at"`
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersRow{}
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarKey,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u.id, u.username, p.display_name, p.avatar_key, f.created_at AS followed_at
  FROM follows f
  JOIN users u ON u.id = f.followee_id AND u.deleted_at IS NULL
  LEFT JOIN profiles p ON p.user_id = u.id
 WHERE f.follower_id = $1
 ORDER BY f.created_at DESC
 LIMIT $3 OFFSET $2
`

type ListFollowingParams struct {
	UserID uuid.UUID `json:"user_id"`
	Off    int32     `json:"off"`
	Lim    int32     `json:"lim"`
}

type ListFollowingRow struct {
	ID          uuid.UUID          `json:"id"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
	AvatarKey   *string            `json:"avatar_key"`
	FollowedAt  pgtype.Timestamptz `json:"followed_at"`
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.Query(ctx, listFollowing, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingRow{}
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarKey,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingFeed = `-- name: ListFollowingFeed :many

WITH activity AS (
  SELECT r.id           AS entity_id,
         'review'::text AS kind,
         r.user_id      AS actor_id,
         r.work_id      AS work_id,
         r.created_at   AS created_at,
         r.rating       AS rating,
         left(r.body, 320) AS excerpt,
         r.has_spoilers AS has_spoilers
    FROM reviews r
   WHERE r.deleted_at IS NULL
  UNION ALL
  SELECT si.id, 'shelf_add'::text, s.user_id, si.work_id, si.added_at,
         NULL::integer, NULL::text, false
    FROM shelf_items si
    JOIN shelves s ON s.id = si.shelf_id
   WHERE NOT s.is_private
)
SELECT a.entity_id, a.kind, a.actor_id, a.work_id, a.created_at, a.rating,
       a.excerpt, a.has_spoilers,
       u.username, p.display_name, p.avatar_key,
       w.slug AS work_slug, w.title AS work_title,
       (SELECT au.name FROM work_authors wa JOIN authors au ON au.id = wa.author_id
         WHERE wa.work_id = w.id ORDER BY wa.position LIMIT 1) AS primary_author,
       (SELECT ca.object_key FROM editions e
          JOIN cover_assets ca ON ca.edition_id = e.id AND ca.is_primary
         WHERE e.work_id = w.id AND e.deleted_at IS NULL LIMIT 1) AS cover_key
  FROM activity a
  JOIN follows f  ON f.followee_id = a.actor_id
  JOIN users u    ON u.id = a.actor_id AND u.deleted_at IS NULL
  LEFT JOIN profiles p ON p.user_id = u.id
  JOIN works w    ON w.id = a.work_id AND w.deleted_at IS NULL
 WHERE f.follower_id = $1
   AND NOT EXISTS (SELECT 1 FROM user_blocks b
                    WHERE (b.blocker_id = $1 AND b.blocked_id = a.actor_id)
                       OR (b.blocker_id = a.actor_id AND b.blocked_id = $1))
   AND ($2::timestamptz IS NULL OR a.created_at < $2)
 ORDER BY a.created_at DESC
 LIMIT $3
`

type ListFollowingFeedParams struct {
	UserID uuid.UUID          `json:"user_id"`
	Since  pgtype.Timestamptz `json:"since"`
	Lim    int32              `json:"lim"`
}

type ListFollowingFeedRow struct {
	EntityID      uuid.UUID          `json:"entity_id"`
	Kind          string             `json:"kind"`
	ActorID       uuid.UUID          `json:"actor_id"`
	WorkID        uuid.UUID          `json:"work_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Rating        int32              `json:"rating"`
	Excerpt       string             `json:"excerpt"`
	HasSpoilers   bool               `json:"has_spoilers"`
	Username      string             `json:"username"`
	DisplayName   *string            `json:"display_name"`
	AvatarKey     *string            `json:"avatar_key"`
	WorkSlug      string             `json:"work_slug"`
	WorkTitle     string             `json:"work_title"`
	PrimaryAuthor string             `json:"primary_author"`
	CoverKey      *string            `json:"cover_key"`
}

// ---- Feed -------------------------------------------------------------------
// Chronological activity from accounts the reader follows. Blocked accounts are
// excluded in both directions; private shelves never appear.
func (q *Queries) ListFollowingFeed(ctx context.Context, arg ListFollowingFeedParams) ([]ListFollowingFeedRow, error) {
	rows, err := q.db.Query(ctx, listFollowingFeed, arg.UserID, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingFeedRow{}
	for rows.Next() {
		var i ListFollowingFeedRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Kind,
			&i.ActorID,
			&i.WorkID,
			&i.CreatedAt,
			&i.Rating,
			&i.Excerpt,
			&i.HasSpoilers,
			&i.Username,
			&i.DisplayName,
			&i.AvatarKey,
			&i.WorkSlug,
			&i.WorkTitle,
			&i.PrimaryAuthor,
			&i.CoverKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, kind, payload, read_at, created_at FROM notifications
 WHERE user_id = $1
   AND ($2::boolean IS NULL OR NOT $2::boolean OR read_at IS NULL)
 ORDER BY created_at DESC
 LIMIT $4 OFFSET $3
`

type ListNotificationsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	UnreadOnly *bool     `json:"unread_only"`
	Off        int32     `json:"off"`
	Lim        int32     `json:"lim"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentReviewsAcrossCommunity = `-- name: ListRecentReviewsAcrossCommunity :many
SELECT r.id, r.user_id, r.work_id, r.edition_id, r.rating, r.title, r.body, r.has_spoilers, r.prompt_why, r.like_count, r.created_at, r.updated_at, r.deleted_at, u.username, p.display_name,
       w.slug AS work_slug, w.title AS work_title,
       (SELECT au.name FROM work_authors wa JOIN authors au ON au.id = wa.author_id
         WHERE wa.work_id = w.id ORDER BY wa.position LIMIT 1) AS primary_author,
       (SELECT ca.object_key FROM editions e
          JOIN cover_assets ca ON ca.edition_id = e.id AND ca.is_primary
         WHERE e.work_id = w.id AND e.deleted_at IS NULL LIMIT 1) AS cover_key
  FROM reviews r
  JOIN users u ON u.id = r.user_id AND u.deleted_at IS NULL
  LEFT JOIN profiles p ON p.user_id = u.id
  JOIN works w ON w.id = r.work_id AND w.deleted_at IS NULL
 WHERE r.deleted_at IS NULL AND NOT r.has_spoilers
 ORDER BY r.created_at DESC
 LIMIT $2 OFFSET $1
`

type ListRecentReviewsAcrossCommunityParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

type ListRecentReviewsAcrossCommunityRow struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	WorkID        uuid.UUID          `json:"work_id"`
	EditionID     pgtype.UUID        `json:"edition_id"`
	Rating        int32              `json:"rating"`
	Title         string             `json:"title"`
	Body          string             `json:"body"`
	HasSpoilers   bool               `json:"has_spoilers"`
	PromptWhy     string             `json:"prompt_why"`
	LikeCount     int32              `json:"like_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	Username      string             `json:"username"`
	DisplayName   *string            `json:"display_name"`
	WorkSlug      string             `json:"work_slug"`
	WorkTitle     string             `json:"work_title"`
	PrimaryAuthor string             `json:"primary_author"`
	CoverKey      *string            `json:"cover_key"`
}

// The logged-out / empty-following home page: newest substantive reviews
// platform-wide. Reverse-chronological, capped, and it never pretends to be
// personalized.
func (q *Queries) ListRecentReviewsAcrossCommunity(ctx context.Context, arg ListRecentReviewsAcrossCommunityParams) ([]ListRecentReviewsAcrossCommunityRow, error) {
	rows, err := q.db.Query(ctx, listRecentReviewsAcrossCommunity, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentReviewsAcrossCommunityRow{}
	for rows.Next() {
		var i ListRecentReviewsAcrossCommunityRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkID,
			&i.EditionID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.HasSpoilers,
			&i.PromptWhy,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Username,
			&i.DisplayName,
			&i.WorkSlug,
			&i.WorkTitle,
			&i.PrimaryAuthor,
			&i.CoverKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = now() WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unblockUser = `-- name: UnblockUser :execrows
DELETE FROM user_blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unfollowUser = `-- name: UnfollowUser :execrows
DELETE FROM follows WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowUserParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FolloweeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
