// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: works.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimAuthorProfile = `-- name: ClaimAuthorProfile :execrows
UPDATE authors SET is_claimed = true, claimed_by = $1, bio = $2
 WHERE id = $3 AND NOT is_claimed
`

type ClaimAuthorProfileParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Bio      string      `json:"bio"`
	AuthorID uuid.UUID   `json:"author_id"`
}

// Indie authors claim an author record; claims are audited, never paid.
func (q *Queries) ClaimAuthorProfile(ctx context.Context, arg ClaimAuthorProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimAuthorProfile, arg.UserID, arg.Bio, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearPrimaryCover = `-- name: ClearPrimaryCover :exec
UPDATE cover_assets SET is_primary = false WHERE edition_id = $1 AND is_primary
`

func (q *Queries) ClearPrimaryCover(ctx context.Context, editionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPrimaryCover, editionID)
	return err
}

const countWorks = `-- name: CountWorks :one
SELECT count(*) FROM works WHERE deleted_at IS NULL
`

func (q *Queries) CountWorks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT id, name, sort_name, bio, birth_year, death_year, openlibrary_id, wikidata_id, is_claimed, claimed_by, created_at, updated_at, deleted_at, slug FROM authors WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAuthorByID(ctx context.Context, id uuid.UUID) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorByID, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortName,
		&i.Bio,
		&i.BirthYear,
		&i.DeathYear,
		&i.OpenlibraryID,
		&i.WikidataID,
		&i.IsClaimed,
		&i.ClaimedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Slug,
	)
	return i, err
}

const getAuthorByName = `-- name: GetAuthorByName :one
SELECT id, name, sort_name, bio, birth_year, death_year, openlibrary_id, wikidata_id, is_claimed, claimed_by, created_at, updated_at, deleted_at, slug FROM authors WHERE name = $1 AND deleted_at IS NULL LIMIT 1
`

// Dedup key for authors that arrive without a stable external identifier
// (Gutenberg catalog names, indie authors). Exact match, case-insensitive.
func (q *Queries) GetAuthorByName(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorByName, name)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortName,
		&i.Bio,
		&i.BirthYear,
		&i.DeathYear,
		&i.OpenlibraryID,
		&i.WikidataID,
		&i.IsClaimed,
		&i.ClaimedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Slug,
	)
	return i, err
}

const getAuthorBySlug = `-- name: GetAuthorBySlug :one
SELECT id, name, sort_name, bio, birth_year, death_year, openlibrary_id, wikidata_id, is_claimed, claimed_by, created_at, updated_at, deleted_at, slug FROM authors WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAuthorBySlug(ctx context.Context, slug string) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorBySlug, slug)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortName,
		&i.Bio,
		&i.BirthYear,
		&i.DeathYear,
		&i.OpenlibraryID,
		&i.WikidataID,
		&i.IsClaimed,
		&i.ClaimedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Slug,
	)
	return i, err
}

const getEditionByGutenbergID = `-- name: GetEditionByGutenbergID :one
SELECT id, work_id, title, isbn10, isbn13, format, publisher, published_on, language, page_count, gutenberg_id, openlibrary_id, metadata, created_at, updated_at, deleted_at FROM editions WHERE gutenberg_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEditionByGutenbergID(ctx context.Context, gutenbergID *int32) (Edition, error) {
	row := q.db.QueryRow(ctx, getEditionByGutenbergID, gutenbergID)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.Title,
		&i.Isbn10,
		&i.Isbn13,
		&i.Format,
		&i.Publisher,
		&i.PublishedOn,
		&i.Language,
		&i.PageCount,
		&i.GutenbergID,
		&i.OpenlibraryID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEditionByID = `-- name: GetEditionByID :one
SELECT e.id, e.work_id, e.title, e.isbn10, e.isbn13, e.format, e.publisher, e.published_on, e.language, e.page_count, e.gutenberg_id, e.openlibrary_id, e.metadata, e.created_at, e.updated_at, e.deleted_at, w.slug AS work_slug, w.title AS work_title
  FROM editions e JOIN works w ON w.id = e.work_id
 WHERE e.id = $1 AND e.deleted_at IS NULL
`

type GetEditionByIDRow struct {
	ID            uuid.UUID          `json:"id"`
	WorkID        uuid.UUID          `json:"work_id"`
	Title         string             `json:"title"`
	Isbn10        *string            `json:"isbn10"`
	Isbn13        *string            `json:"isbn13"`
	Format        EditionFormat      `json:"format"`
	Publisher     *string            `json:"publisher"`
	PublishedOn   pgtype.Date        `json:"published_on"`
	Language      string             `json:"language"`
	PageCount     *int32             `json:"page_count"`
	GutenbergID   *int32             `json:"gutenberg_id"`
	OpenlibraryID *string            `json:"openlibrary_id"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	WorkSlug      string             `json:"work_slug"`
	WorkTitle     string             `json:"work_title"`
}

func (q *Queries) GetEditionByID(ctx context.Context, id uuid.UUID) (GetEditionByIDRow, error) {
	row := q.db.QueryRow(ctx, getEditionByID, id)
	var i GetEditionByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.Title,
		&i.Isbn10,
		&i.Isbn13,
		&i.Format,
		&i.Publisher,
		&i.PublishedOn,
		&i.Language,
		&i.PageCount,
		&i.GutenbergID,
		&i.OpenlibraryID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.WorkSlug,
		&i.WorkTitle,
	)
	return i, err
}

const getPrimaryCoverForEdition = `-- name: GetPrimaryCoverForEdition :one
SELECT id, edition_id, source, source_url, license, license_url, attribution_text, object_key, cacheable, cache_expires_at, uploaded_by, is_primary, created_at FROM cover_assets WHERE edition_id = $1 AND is_primary
`

func (q *Queries) GetPrimaryCoverForEdition(ctx context.Context, editionID uuid.UUID) (CoverAsset, error) {
	row := q.db.QueryRow(ctx, getPrimaryCoverForEdition, editionID)
	var i CoverAsset
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.Source,
		&i.SourceUrl,
		&i.License,
		&i.LicenseUrl,
		&i.AttributionText,
		&i.ObjectKey,
		&i.Cacheable,
		&i.CacheExpiresAt,
		&i.UploadedBy,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkByID = `-- name: GetWorkByID :one
SELECT id, slug, title, subtitle, original_language, first_published, description, is_public_domain, openlibrary_id, rating_sum, rating_count, created_at, updated_at, deleted_at FROM works WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkByID(ctx context.Context, id uuid.UUID) (Work, error) {
	row := q.db.QueryRow(ctx, getWorkByID, id)
	var i Work
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.OriginalLanguage,
		&i.FirstPublished,
		&i.Description,
		&i.IsPublicDomain,
		&i.OpenlibraryID,
		&i.RatingSum,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkByOpenLibraryID = `-- name: GetWorkByOpenLibraryID :one
SELECT id, slug, title, subtitle, original_language, first_published, description, is_public_domain, openlibrary_id, rating_sum, rating_count, created_at, updated_at, deleted_at FROM works WHERE openlibrary_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkByOpenLibraryID(ctx context.Context, openlibraryID *string) (Work, error) {
	row := q.db.QueryRow(ctx, getWorkByOpenLibraryID, openlibraryID)
	var i Work
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.OriginalLanguage,
		&i.FirstPublished,
		&i.Description,
		&i.IsPublicDomain,
		&i.OpenlibraryID,
		&i.RatingSum,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkBySlug = `-- name: GetWorkBySlug :one

SELECT id, slug, title, subtitle, original_language, first_published, description, is_public_domain, openlibrary_id, rating_sum, rating_count, created_at, updated_at, deleted_at FROM works WHERE slug = $1 AND deleted_at IS NULL
`

// Bibliography: the FRBR core (Work → Edition) plus authors and subjects.
//
// Duplicate books are the failure mode that kills every community-maintained
// catalogue, so every write path here is an idempotent upsert keyed on a
// stable external identifier, never on a title string.
func (q *Queries) GetWorkBySlug(ctx context.Context, slug string) (Work, error) {
	row := q.db.QueryRow(ctx, getWorkBySlug, slug)
	var i Work
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.OriginalLanguage,
		&i.FirstPublished,
		&i.Description,
		&i.IsPublicDomain,
		&i.OpenlibraryID,
		&i.RatingSum,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertCoverAsset = `-- name: InsertCoverAsset :one

INSERT INTO cover_assets (edition_id, source, source_url, license, license_url,
                          attribution_text, object_key, cacheable, cache_expires_at,
                          uploaded_by, is_primary)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8,
        $9, $10, $11)
RETURNING id, edition_id, source, source_url, license, license_url, attribution_text, object_key, cacheable, cache_expires_at, uploaded_by, is_primary, created_at
`

type InsertCoverAssetParams struct {
	EditionID       uuid.UUID          `json:"edition_id"`
	Source          string             `json:"source"`
	SourceUrl       *string            `json:"source_url"`
	License         CoverLicense       `json:"license"`
	LicenseUrl      *string            `json:"license_url"`
	AttributionText *string            `json:"attribution_text"`
	ObjectKey       *string            `json:"object_key"`
	Cacheable       bool               `json:"cacheable"`
	CacheExpiresAt  pgtype.Timestamptz `json:"cache_expires_at"`
	UploadedBy      pgtype.UUID        `json:"uploaded_by"`
	IsPrimary       bool               `json:"is_primary"`
}

// ---- Covers (rights-aware) --------------------------------------------------
func (q *Queries) InsertCoverAsset(ctx context.Context, arg InsertCoverAssetParams) (CoverAsset, error) {
	row := q.db.QueryRow(ctx, insertCoverAsset,
		arg.EditionID,
		arg.Source,
		arg.SourceUrl,
		arg.License,
		arg.LicenseUrl,
		arg.AttributionText,
		arg.ObjectKey,
		arg.Cacheable,
		arg.CacheExpiresAt,
		arg.UploadedBy,
		arg.IsPrimary,
	)
	var i CoverAsset
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.Source,
		&i.SourceUrl,
		&i.License,
		&i.LicenseUrl,
		&i.AttributionText,
		&i.ObjectKey,
		&i.Cacheable,
		&i.CacheExpiresAt,
		&i.UploadedBy,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const insertWork = `-- name: InsertWork :one
INSERT INTO works (slug, title, subtitle, original_language, first_published,
                   description, is_public_domain)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
RETURNING id, slug, title, subtitle, original_language, first_published, description, is_public_domain, openlibrary_id, rating_sum, rating_count, created_at, updated_at, deleted_at
`

type InsertWorkParams struct {
	Slug             string  `json:"slug"`
	Title            string  `json:"title"`
	Subtitle         *string `json:"subtitle"`
	OriginalLanguage string  `json:"original_language"`
	FirstPublished   *int32  `json:"first_published"`
	Description      string  `json:"description"`
	IsPublicDomain   bool    `json:"is_public_domain"`
}

// For works with no external identifier yet (indie authors, Gutenberg texts
// whose Open Library work record is missing). Slug uniqueness is enforced by
// the schema; callers resolve collisions before inserting.
func (q *Queries) InsertWork(ctx context.Context, arg InsertWorkParams) (Work, error) {
	row := q.db.QueryRow(ctx, insertWork,
		arg.Slug,
		arg.Title,
		arg.Subtitle,
		arg.OriginalLanguage,
		arg.FirstPublished,
		arg.Description,
		arg.IsPublicDomain,
	)
	var i Work
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.OriginalLanguage,
		&i.FirstPublished,
		&i.Description,
		&i.IsPublicDomain,
		&i.OpenlibraryID,
		&i.RatingSum,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const linkWorkAuthor = `-- name: LinkWorkAuthor :exec
INSERT INTO work_authors (work_id, author_id, role, position)
VALUES ($1, $2, $3, $4)
ON CONFLICT (work_id, author_id, role) DO UPDATE SET position = EXCLUDED.position
`

type LinkWorkAuthorParams struct {
	WorkID   uuid.UUID `json:"work_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Role     string    `json:"role"`
	Position int32     `json:"position"`
}

func (q *Queries) LinkWorkAuthor(ctx context.Context, arg LinkWorkAuthorParams) error {
	_, err := q.db.Exec(ctx, linkWorkAuthor,
		arg.WorkID,
		arg.AuthorID,
		arg.Role,
		arg.Position,
	)
	return err
}

const linkWorkSubject = `-- name: LinkWorkSubject :exec
INSERT INTO work_subjects (work_id, subject_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkWorkSubjectParams struct {
	WorkID    uuid.UUID `json:"work_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

func (q *Queries) LinkWorkSubject(ctx context.Context, arg LinkWorkSubjectParams) error {
	_, err := q.db.Exec(ctx, linkWorkSubject, arg.WorkID, arg.SubjectID)
	return err
}

const listAuthorsForWork = `-- name: ListAuthorsForWork :many
SELECT a.id, a.name, a.sort_name, a.bio, a.birth_year, a.death_year, a.openlibrary_id, a.wikidata_id, a.is_claimed, a.claimed_by, a.created_at, a.updated_at, a.deleted_at, a.slug, wa.role, wa.position
  FROM work_authors wa
  JOIN authors a ON a.id = wa.author_id
 WHERE wa.work_id = $1 AND a.deleted_at IS NULL
 ORDER BY wa.position, wa.role
`

type ListAuthorsForWorkRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	SortName      string             `json:"sort_name"`
	Bio           string             `json:"bio"`
	BirthYear     *int32             `json:"birth_year"`
	DeathYear     *int32             `json:"death_year"`
	OpenlibraryID *string            `json:"openlibrary_id"`
	WikidataID    *string            `json:"wikidata_id"`
	IsClaimed     bool               `json:"is_claimed"`
	ClaimedBy     pgtype.UUID        `json:"claimed_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	Slug          string             `json:"slug"`
	Role          string             `json:"role"`
	Position      int32              `json:"position"`
}

func (q *Queries) ListAuthorsForWork(ctx context.Context, workID uuid.UUID) ([]ListAuthorsForWorkRow, error) {
	rows, err := q.db.Query(ctx, listAuthorsForWork, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorsForWorkRow{}
	for rows.Next() {
		var i ListAuthorsForWorkRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortName,
			&i.Bio,
			&i.BirthYear,
			&i.DeathYear,
			&i.OpenlibraryID,
			&i.WikidataID,
			&i.IsClaimed,
			&i.ClaimedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Slug,
			&i.Role,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoversForWork = `-- name: ListCoversForWork :many
SELECT ca.id, ca.edition_id, ca.source, ca.source_url, ca.license, ca.license_url, ca.attribution_text, ca.object_key, ca.cacheable, ca.cache_expires_at, ca.uploaded_by, ca.is_primary, ca.created_at, e.id AS edition_id, e.title AS edition_title
  FROM cover_assets ca JOIN editions e ON e.id = ca.edition_id
 WHERE e.work_id = $1 AND e.deleted_at IS NULL
 ORDER BY ca.is_primary DESC, ca.created_at DESC
`

type ListCoversForWorkRow struct {
	ID              uuid.UUID          `json:"id"`
	EditionID       uuid.UUID          `json:"edition_id"`
	Source          string             `json:"source"`
	SourceUrl       *string            `json:"source_url"`
	License         CoverLicense       `json:"license"`
	LicenseUrl      *string            `json:"license_url"`
	AttributionText *string            `json:"attribution_text"`
	ObjectKey       *string            `json:"object_key"`
	Cacheable       bool               `json:"cacheable"`
	CacheExpiresAt  pgtype.Timestamptz `json:"cache_expires_at"`
	UploadedBy      pgtype.UUID        `json:"uploaded_by"`
	IsPrimary       bool               `json:"is_primary"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	EditionID_2     uuid.UUID          `json:"edition_id_2"`
	EditionTitle    string             `json:"edition_title"`
}

func (q *Queries) ListCoversForWork(ctx context.Context, workID uuid.UUID) ([]ListCoversForWorkRow, error) {
	rows, err := q.db.Query(ctx, listCoversForWork, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoversForWorkRow{}
	for rows.Next() {
		var i ListCoversForWorkRow
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.Source,
			&i.SourceUrl,
			&i.License,
			&i.LicenseUrl,
			&i.AttributionText,
			&i.ObjectKey,
			&i.Cacheable,
			&i.CacheExpiresAt,
			&i.UploadedBy,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.EditionID_2,
			&i.EditionTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEditionsForWork = `-- name: ListEditionsForWork :many

SELECT e.id, e.work_id, e.title, e.isbn10, e.isbn13, e.format, e.publisher, e.published_on, e.language, e.page_count, e.gutenberg_id, e.openlibrary_id, e.metadata, e.created_at, e.updated_at, e.deleted_at,
       ca.object_key       AS cover_key,
       ca.license          AS cover_license,
       ca.attribution_text AS cover_attribution
  FROM editions e
  LEFT JOIN cover_assets ca ON ca.edition_id = e.id AND ca.is_primary
 WHERE e.work_id = $1 AND e.deleted_at IS NULL
 ORDER BY e.published_on DESC NULLS LAST
`

type ListEditionsForWorkRow struct {
	ID               uuid.UUID          `json:"id"`
	WorkID           uuid.UUID          `json:"work_id"`
	Title            string             `json:"title"`
	Isbn10           *string            `json:"isbn10"`
	Isbn13           *string            `json:"isbn13"`
	Format           EditionFormat      `json:"format"`
	Publisher        *string            `json:"publisher"`
	PublishedOn      pgtype.Date        `json:"published_on"`
	Language         string             `json:"language"`
	PageCount        *int32             `json:"page_count"`
	GutenbergID      *int32             `json:"gutenberg_id"`
	OpenlibraryID    *string            `json:"openlibrary_id"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CoverKey         *string            `json:"cover_key"`
	CoverLicense     NullCoverLicense   `json:"cover_license"`
	CoverAttribution *string            `json:"cover_attribution"`
}

// ---- Editions ---------------------------------------------------------------
func (q *Queries) ListEditionsForWork(ctx context.Context, workID uuid.UUID) ([]ListEditionsForWorkRow, error) {
	rows, err := q.db.Query(ctx, listEditionsForWork, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEditionsForWorkRow{}
	for rows.Next() {
		var i ListEditionsForWorkRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkID,
			&i.Title,
			&i.Isbn10,
			&i.Isbn13,
			&i.Format,
			&i.Publisher,
			&i.PublishedOn,
			&i.Language,
			&i.PageCount,
			&i.GutenbergID,
			&i.OpenlibraryID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CoverKey,
			&i.CoverLicense,
			&i.CoverAttribution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalIdentifiers = `-- name: ListExternalIdentifiers :many
SELECT id, edition_id, namespace, value FROM external_identifiers WHERE edition_id = $1 ORDER BY namespace
`

func (q *Queries) ListExternalIdentifiers(ctx context.Context, editionID uuid.UUID) ([]ExternalIdentifier, error) {
	rows, err := q.db.Query(ctx, listExternalIdentifiers, editionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalIdentifier{}
	for rows.Next() {
		var i ExternalIdentifier
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.Namespace,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopularSubjects = `-- name: ListPopularSubjects :many
SELECT s.id, s.slug, s.name, s.kind, count(ws.work_id) AS work_count
  FROM subjects s
  JOIN work_subjects ws ON ws.subject_id = s.id
 GROUP BY s.id
 ORDER BY work_count DESC
 LIMIT $1
`

type ListPopularSubjectsRow struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	WorkCount int64     `json:"work_count"`
}

func (q *Queries) ListPopularSubjects(ctx context.Context, lim int32) ([]ListPopularSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listPopularSubjects, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPopularSubjectsRow{}
	for rows.Next() {
		var i ListPopularSubjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.WorkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectsForWork = `-- name: ListSubjectsForWork :many
SELECT s.id, s.slug, s.name, s.kind FROM work_subjects ws JOIN subjects s ON s.id = ws.subject_id
 WHERE ws.work_id = $1
 ORDER BY s.name
`

func (q *Queries) ListSubjectsForWork(ctx context.Context, workID uuid.UUID) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjectsForWork, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkIDsForIndex = `-- name: ListWorkIDsForIndex :many
SELECT id FROM works
 WHERE deleted_at IS NULL AND id > $1
 ORDER BY id
 LIMIT $2
`

type ListWorkIDsForIndexParams struct {
	AfterID uuid.UUID `json:"after_id"`
	Lim     int32     `json:"lim"`
}

// Paging cursor for a full Meilisearch reindex: keyset pagination on id, which
// stays O(log n) where OFFSET would degrade badly on a large catalogue.
func (q *Queries) ListWorkIDsForIndex(ctx context.Context, arg ListWorkIDsForIndexParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listWorkIDsForIndex, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorks = `-- name: ListWorks :many
SELECT w.id, w.slug, w.title, w.subtitle, w.original_language, w.first_published, w.description, w.is_public_domain, w.openlibrary_id, w.rating_sum, w.rating_count, w.created_at, w.updated_at, w.deleted_at,
       (SELECT count(*) FROM editions e
         WHERE e.work_id = w.id AND e.deleted_at IS NULL) AS edition_count,
       (SELECT e.gutenberg_id FROM editions e
         WHERE e.work_id = w.id AND e.gutenberg_id IS NOT NULL
         ORDER BY e.gutenberg_id LIMIT 1) AS gutenberg_id
  FROM works w
 WHERE w.deleted_at IS NULL
   AND ($1::text IS NULL OR EXISTS (
         SELECT 1 FROM work_subjects ws JOIN subjects s ON s.id = ws.subject_id
          WHERE ws.work_id = w.id AND s.slug = $1))
   AND ($2::uuid IS NULL OR EXISTS (
         SELECT 1 FROM work_authors wa
          WHERE wa.work_id = w.id AND wa.author_id = $2))
   AND ($3::text IS NULL OR w.original_language = $3)
   AND ($4::boolean IS NULL
        OR NOT $4::boolean
        OR w.is_public_domain)
   AND ($5::integer IS NULL OR w.first_published >= $5)
   AND ($6::integer IS NULL OR w.first_published <= $6)
   AND ($7::text IS NULL OR w.title ILIKE $7 || '%')
 ORDER BY
   CASE $8::text
     WHEN 'rating'  THEN (w.rating_sum + 20.0 * 3.5) / (w.rating_count + 20.0)
     WHEN 'recent'  THEN coalesce(w.first_published, -9999)
     WHEN 'title'   THEN 0
     ELSE 0
   END DESC,
   CASE WHEN $8 = 'title' THEN w.title END ASC,
   w.rating_count DESC,
   w.created_at DESC
 LIMIT $10 OFFSET $9
`

type ListWorksParams struct {
	SubjectSlug      *string     `json:"subject_slug"`
	AuthorID         pgtype.UUID `json:"author_id"`
	Language         *string     `json:"language"`
	PublicDomainOnly *bool       `json:"public_domain_only"`
	PublishedAfter   *int32      `json:"published_after"`
	PublishedBefore  *int32      `json:"published_before"`
	TitlePrefix      *string     `json:"title_prefix"`
	Sort             string      `json:"sort"`
	Off              int32       `json:"off"`
	Lim              int32       `json:"lim"`
}

type ListWorksRow struct {
	ID               uuid.UUID          `json:"id"`
	Slug             string             `json:"slug"`
	Title            string             `json:"title"`
	Subtitle         *string            `json:"subtitle"`
	OriginalLanguage string             `json:"original_language"`
	FirstPublished   *int32             `json:"first_published"`
	Description      string             `json:"description"`
	IsPublicDomain   bool               `json:"is_public_domain"`
	OpenlibraryID    *string            `json:"openlibrary_id"`
	RatingSum        int64              `json:"rating_sum"`
	RatingCount      int64              `json:"rating_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	EditionCount     int64              `json:"edition_count"`
	GutenbergID      *int32             `json:"gutenberg_id"`
}

// The catalogue listing. Every filter is optional and expressed as a
// NULL-or-match predicate so sqlc generates one plan and the caller never
// builds SQL strings.
//
// Ordering is explicit and non-algorithmic: `rating` is a Bayesian-weighted
// average (never a raw mean, which puts a single 5★ above 400 4.8★ ratings),
// `recent` is publication year, `added` is ingest order. There is no
// engagement-weighted sort, by design.
func (q *Queries) ListWorks(ctx context.Context, arg ListWorksParams) ([]ListWorksRow, error) {
	rows, err := q.db.Query(ctx, listWorks,
		arg.SubjectSlug,
		arg.AuthorID,
		arg.Language,
		arg.PublicDomainOnly,
		arg.PublishedAfter,
		arg.PublishedBefore,
		arg.TitlePrefix,
		arg.Sort,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorksRow{}
	for rows.Next() {
		var i ListWorksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.OriginalLanguage,
			&i.FirstPublished,
			&i.Description,
			&i.IsPublicDomain,
			&i.OpenlibraryID,
			&i.RatingSum,
			&i.RatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EditionCount,
			&i.GutenbergID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorksBySubject = `-- name: ListWorksBySubject :many
SELECT w.id, w.slug, w.title, w.subtitle, w.original_language, w.first_published, w.description, w.is_public_domain, w.openlibrary_id, w.rating_sum, w.rating_count, w.created_at, w.updated_at, w.deleted_at FROM works w
  JOIN work_subjects ws ON ws.work_id = w.id
  JOIN subjects s ON s.id = ws.subject_id
 WHERE s.slug = $1 AND w.deleted_at IS NULL
 ORDER BY (w.rating_sum + 20.0 * 3.5) / (w.rating_count + 20.0) DESC, w.rating_count DESC
 LIMIT $3 OFFSET $2
`

type ListWorksBySubjectParams struct {
	Slug string `json:"slug"`
	Off  int32  `json:"off"`
	Lim  int32  `json:"lim"`
}

func (q *Queries) ListWorksBySubject(ctx context.Context, arg ListWorksBySubjectParams) ([]Work, error) {
	rows, err := q.db.Query(ctx, listWorksBySubject, arg.Slug, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Work{}
	for rows.Next() {
		var i Work
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.OriginalLanguage,
			&i.FirstPublished,
			&i.Description,
			&i.IsPublicDomain,
			&i.OpenlibraryID,
			&i.RatingSum,
			&i.RatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorksForAuthor = `-- name: ListWorksForAuthor :many
SELECT w.id, w.slug, w.title, w.subtitle, w.original_language, w.first_published, w.description, w.is_public_domain, w.openlibrary_id, w.rating_sum, w.rating_count, w.created_at, w.updated_at, w.deleted_at, wa.role
  FROM work_authors wa
  JOIN works w ON w.id = wa.work_id
 WHERE wa.author_id = $1 AND w.deleted_at IS NULL
 ORDER BY coalesce(w.first_published, -9999) ASC
 LIMIT $3 OFFSET $2
`

type ListWorksForAuthorParams struct {
	AuthorID uuid.UUID `json:"author_id"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

type ListWorksForAuthorRow struct {
	ID               uuid.UUID          `json:"id"`
	Slug             string             `json:"slug"`
	Title            string             `json:"title"`
	Subtitle         *string            `json:"subtitle"`
	OriginalLanguage string             `json:"original_language"`
	FirstPublished   *int32             `json:"first_published"`
	Description      string             `json:"description"`
	IsPublicDomain   bool               `json:"is_public_domain"`
	OpenlibraryID    *string            `json:"openlibrary_id"`
	RatingSum        int64              `json:"rating_sum"`
	RatingCount      int64              `json:"rating_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	Role             string             `json:"role"`
}

func (q *Queries) ListWorksForAuthor(ctx context.Context, arg ListWorksForAuthorParams) ([]ListWorksForAuthorRow, error) {
	rows, err := q.db.Query(ctx, listWorksForAuthor, arg.AuthorID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorksForAuthorRow{}
	for rows.Next() {
		var i ListWorksForAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.OriginalLanguage,
			&i.FirstPublished,
			&i.Description,
			&i.IsPublicDomain,
			&i.OpenlibraryID,
			&i.RatingSum,
			&i.RatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takedownCover = `-- name: TakedownCover :execrows
UPDATE cover_assets
   SET is_primary = false, cacheable = false, object_key = NULL,
       license = 'unknown', attribution_text = 'Removed following a rights request.'
 WHERE id = $1
`

// DMCA path: immediate, auditable, and it removes the cached object reference
// so the CDN can no longer serve it.
func (q *Queries) TakedownCover(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, takedownCover, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAuthor = `-- name: UpsertAuthor :one

INSERT INTO authors (name, sort_name, bio, birth_year, death_year, slug, openlibrary_id, wikidata_id)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
ON CONFLICT (openlibrary_id) DO UPDATE SET
  name      = EXCLUDED.name,
  sort_name = EXCLUDED.sort_name,
  bio       = CASE WHEN EXCLUDED.bio <> '' THEN EXCLUDED.bio ELSE authors.bio END,
  birth_year = COALESCE(authors.birth_year, EXCLUDED.birth_year),
  death_year = COALESCE(authors.death_year, EXCLUDED.death_year)
RETURNING id, name, sort_name, bio, birth_year, death_year, openlibrary_id, wikidata_id, is_claimed, claimed_by, created_at, updated_at, deleted_at, slug
`

type UpsertAuthorParams struct {
	Name          string  `json:"name"`
	SortName      string  `json:"sort_name"`
	Bio           string  `json:"bio"`
	BirthYear     *int32  `json:"birth_year"`
	DeathYear     *int32  `json:"death_year"`
	Slug          string  `json:"slug"`
	OpenlibraryID *string `json:"openlibrary_id"`
	WikidataID    *string `json:"wikidata_id"`
}

// ---- Authors ----------------------------------------------------------------
func (q *Queries) UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, upsertAuthor,
		arg.Name,
		arg.SortName,
		arg.Bio,
		arg.BirthYear,
		arg.DeathYear,
		arg.Slug,
		arg.OpenlibraryID,
		arg.WikidataID,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortName,
		&i.Bio,
		&i.BirthYear,
		&i.DeathYear,
		&i.OpenlibraryID,
		&i.WikidataID,
		&i.IsClaimed,
		&i.ClaimedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Slug,
	)
	return i, err
}

const upsertEdition = `-- name: UpsertEdition :one
INSERT INTO editions (work_id, title, isbn10, isbn13, format, publisher, published_on,
                      language, page_count, gutenberg_id, openlibrary_id, metadata)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8,
        $9, $10,
        $11, $12)
ON CONFLICT (isbn13) WHERE isbn13 IS NOT NULL DO UPDATE SET
  publisher  = COALESCE(EXCLUDED.publisher, editions.publisher),
  page_count = COALESCE(EXCLUDED.page_count, editions.page_count),
  metadata   = editions.metadata || EXCLUDED.metadata
RETURNING id, work_id, title, isbn10, isbn13, format, publisher, published_on, language, page_count, gutenberg_id, openlibrary_id, metadata, created_at, updated_at, deleted_at
`

type UpsertEditionParams struct {
	WorkID        uuid.UUID     `json:"work_id"`
	Title         string        `json:"title"`
	Isbn10        *string       `json:"isbn10"`
	Isbn13        *string       `json:"isbn13"`
	Format        EditionFormat `json:"format"`
	Publisher     *string       `json:"publisher"`
	PublishedOn   pgtype.Date   `json:"published_on"`
	Language      string        `json:"language"`
	PageCount     *int32        `json:"page_count"`
	GutenbergID   *int32        `json:"gutenberg_id"`
	OpenlibraryID *string       `json:"openlibrary_id"`
	Metadata      []byte        `json:"metadata"`
}

func (q *Queries) UpsertEdition(ctx context.Context, arg UpsertEditionParams) (Edition, error) {
	row := q.db.QueryRow(ctx, upsertEdition,
		arg.WorkID,
		arg.Title,
		arg.Isbn10,
		arg.Isbn13,
		arg.Format,
		arg.Publisher,
		arg.PublishedOn,
		arg.Language,
		arg.PageCount,
		arg.GutenbergID,
		arg.OpenlibraryID,
		arg.Metadata,
	)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.Title,
		&i.Isbn10,
		&i.Isbn13,
		&i.Format,
		&i.Publisher,
		&i.PublishedOn,
		&i.Language,
		&i.PageCount,
		&i.GutenbergID,
		&i.OpenlibraryID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertExternalIdentifier = `-- name: UpsertExternalIdentifier :exec
INSERT INTO external_identifiers (edition_id, namespace, value)
VALUES ($1, $2, $3)
ON CONFLICT (namespace, value) DO NOTHING
`

type UpsertExternalIdentifierParams struct {
	EditionID uuid.UUID `json:"edition_id"`
	Namespace string    `json:"namespace"`
	Value     string    `json:"value"`
}

func (q *Queries) UpsertExternalIdentifier(ctx context.Context, arg UpsertExternalIdentifierParams) error {
	_, err := q.db.Exec(ctx, upsertExternalIdentifier, arg.EditionID, arg.Namespace, arg.Value)
	return err
}

const upsertGutenbergEdition = `-- name: UpsertGutenbergEdition :one
INSERT INTO editions (work_id, title, format, publisher, language, page_count, gutenberg_id, metadata)
VALUES ($1, $2, 'gutenberg', $3, $4,
        $5, $6, $7)
ON CONFLICT (gutenberg_id) WHERE gutenberg_id IS NOT NULL DO UPDATE SET
  title    = EXCLUDED.title,
  metadata = editions.metadata || EXCLUDED.metadata
RETURNING id, work_id, title, isbn10, isbn13, format, publisher, published_on, language, page_count, gutenberg_id, openlibrary_id, metadata, created_at, updated_at, deleted_at
`

type UpsertGutenbergEditionParams struct {
	WorkID      uuid.UUID `json:"work_id"`
	Title       string    `json:"title"`
	Publisher   *string   `json:"publisher"`
	Language    string    `json:"language"`
	PageCount   *int32    `json:"page_count"`
	GutenbergID *int32    `json:"gutenberg_id"`
	Metadata    []byte    `json:"metadata"`
}

// Gutenberg texts have no ISBN, so they need their own conflict target.
// Reusing UpsertEdition here would insert a new row on every catalog refresh,
// because a NULL isbn13 never conflicts.
func (q *Queries) UpsertGutenbergEdition(ctx context.Context, arg UpsertGutenbergEditionParams) (Edition, error) {
	row := q.db.QueryRow(ctx, upsertGutenbergEdition,
		arg.WorkID,
		arg.Title,
		arg.Publisher,
		arg.Language,
		arg.PageCount,
		arg.GutenbergID,
		arg.Metadata,
	)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.Title,
		&i.Isbn10,
		&i.Isbn13,
		&i.Format,
		&i.Publisher,
		&i.PublishedOn,
		&i.Language,
		&i.PageCount,
		&i.GutenbergID,
		&i.OpenlibraryID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertSubject = `-- name: UpsertSubject :one

INSERT INTO subjects (slug, name, kind) VALUES ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, kind = EXCLUDED.kind
RETURNING id, slug, name, kind
`

type UpsertSubjectParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Kind string `json:"kind"`
}

// ---- Subjects ---------------------------------------------------------------
func (q *Queries) UpsertSubject(ctx context.Context, arg UpsertSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, upsertSubject, arg.Slug, arg.Name, arg.Kind)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
	)
	return i, err
}

const upsertWork = `-- name: UpsertWork :one
INSERT INTO works (slug, title, subtitle, original_language, first_published,
                   description, is_public_domain, openlibrary_id)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8)
ON CONFLICT (openlibrary_id) DO UPDATE SET
  title       = EXCLUDED.title,
  subtitle    = COALESCE(EXCLUDED.subtitle, works.subtitle),
  description = CASE WHEN EXCLUDED.description <> '' THEN EXCLUDED.description ELSE works.description END,
  is_public_domain = works.is_public_domain OR EXCLUDED.is_public_domain
RETURNING id, slug, title, subtitle, original_language, first_published, description, is_public_domain, openlibrary_id, rating_sum, rating_count, created_at, updated_at, deleted_at
`

type UpsertWorkParams struct {
	Slug             string  `json:"slug"`
	Title            string  `json:"title"`
	Subtitle         *string `json:"subtitle"`
	OriginalLanguage string  `json:"original_language"`
	FirstPublished   *int32  `json:"first_published"`
	Description      string  `json:"description"`
	IsPublicDomain   bool    `json:"is_public_domain"`
	OpenlibraryID    *string `json:"openlibrary_id"`
}

func (q *Queries) UpsertWork(ctx context.Context, arg UpsertWorkParams) (Work, error) {
	row := q.db.QueryRow(ctx, upsertWork,
		arg.Slug,
		arg.Title,
		arg.Subtitle,
		arg.OriginalLanguage,
		arg.FirstPublished,
		arg.Description,
		arg.IsPublicDomain,
		arg.OpenlibraryID,
	)
	var i Work
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.OriginalLanguage,
		&i.FirstPublished,
		&i.Description,
		&i.IsPublicDomain,
		&i.OpenlibraryID,
		&i.RatingSum,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const workSlugIsTaken = `-- name: WorkSlugIsTaken :one
SELECT EXISTS (SELECT 1 FROM works WHERE slug = $1) AS taken
`

func (q *Queries) WorkSlugIsTaken(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, workSlugIsTaken, slug)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}
